### ISSUE TITLE
User authentication and encryption

### ISSUE THREAD

**Issue by GoogleCodeExporter** [danieleteti/delphimvcframework#1]
```
I started doing some testing with DMVCFramework and found it very good. Easy to 
work with and a very acceptable performance.

I only have a few questions:

1 - What is the best way to work with user authentication?
2 - Are there mechanisms and SSL encryption?


```

Original issue reported on code.google.com by `ezequiel...@gmail.com` on 22 Nov 2013 at 11:29

**Comment by danieleteti** [comment]
Encription can be used passing an ioSSLHandler to the constructor of the restclient.
About the server side, the encryption is provided by the webbroker framework or by the webserver.
