### ISSUE TITLE
SSL and Compression 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [danieleteti/delphimvcframework#10]
```
Hello Daniele 

I made ​​some small changes to work with SSL and Compression in RESTClient. 

Added the .pas attached, analyze it and if possible add to the main sources.

```

Original issue reported on code.google.com by `ezequiel...@gmail.com` on 21 Oct 2014 at 11:56

Attachments:
* [MVCFramework.RESTClient.pas](https://storage.googleapis.com/google-code-attachments/delphimvcframework/issue-10/comment-0/MVCFramework.RESTClient.pas)

**Comment by ezequieljuliano** [comment]
Since this feature has been added.
