### ISSUE TITLE
objectmapper :  ObjectToJSONObjectString

### ISSUE THREAD

**Issue by drcrck** [danieleteti/delphimvcframework#100]
hi , method ObjectToJSONObjectString calls : 

  Result := JObj.ToString;  

should be 

{$IFDEF XE7ORBETTER}
  Result := JObj.ToJson;
{$ELSE}
  Result := JObj.ToString;  
{$ENDIF});

**Comment by danieleteti** [comment]
Please, switch to the version 3.x ASAP
