### ISSUE TITLE
indy XE6 dmvcframework.common.pas

### ISSUE THREAD

**Issue by talpa** [danieleteti/delphimvcframework#102]
xe6 indy havent  **IdGlobal.iPv4ToUInt32(AIP)**

_concrete dmvcframework.common.pas line 460_ 

function IP2Long(const AIP: string): UInt32;
begin
  Result := IdGlobal.iPv4ToUInt32(AIP);
end;

**Comment by danieleteti** [comment]
If there aren't maintainers for XE6 and older release, dmvcframewoek 3.0 will not support versions older than XE7.
