### ISSUE TITLE
[dcc32 Error] MVCFramework.Serializer.Intf.pas(66): E2010 Incompatible types: 'TMVCIgnoredList' and 'Set'

### ISSUE THREAD

**Issue by talpa** [danieleteti/delphimvcframework#104]
XE6 compilator error

MVCFramework.Serializer.Intf  
  const AIgnoredAttributes: TMVCIgnoredList = []  
      );
-->

  const AIgnoredAttributes: TMVCIgnoredList =nil
      );

**Comment by danieleteti** [comment]
Sorry, XE6 is no more supported if no one can take care of it. The core team don't have anymore XE6. We need an XE6 mantainer othewise we'll drop the support.
