### ISSUE TITLE
FIX versions who don't have TJSONBool (Delphi XE8 or older)

### ISSUE THREAD

**Issue by dipold** [danieleteti/delphimvcframework#105]
Fix 3.0 RC8 for Delphi versions who don't have TJSONBool (Delphi XE8 or older)

A same problem has been fixed in this commit by 2.x release: 

https://github.com/danieleteti/delphimvcframework/commit/32caa1edcd4f83797faea8b4b31411f43936adb4#diff-79e33efc57f922fc08bc9abf132bcd63

**Comment by danieleteti** [comment]
FIXED IN RC9
