### ISSUE TITLE
TRESTAdapter<T>.DoInvoke ignores httpDelete

### ISSUE THREAD

**Issue by jadeade** [danieleteti/delphimvcframework#107]
Hi

I am writing a rest client and I've realised that TRESTAdapter<T>.DoInvoke will do nothing if I use a httpDELETE as http method when declaring an API interface (eg, [RestResource(httpDELETE, '/mypath')] function ...)

Seems that this is because on the mentioned method, there's a case statement that doesn't include httpDELETE:

```
case _restresourceattr.HTTPMethodType of
    httpGET:
      Resp := FRESTClient.doGET(URL, []);
    httpPUT:
      Resp := FRESTClient.doPUT(URL, [], Body);
    httpPOST:
      Resp := FRESTClient.doPOST(URL, [], Body);
  end;

```
is this done intentionally on purpose and there is some reason that prevents it to work, or it's just something that needs to be finished? It seems that there's not much work needed for it to work, but I would like to know that there's no reason that could prevent it to work before trying it myself

Thank you in advance!!

**Comment by Joc02** [comment]
Hi,

I have the same problem. I have completed the code waiting for the correction.
```      
case _restresourceattr.HTTPMethodType of
    httpGET:
      Resp := FRESTClient.doGET(URL, []);
    httpPUT:
      Resp := FRESTClient.doPUT(URL, [], Body);
    httpPOST:
      Resp := FRESTClient.doPOST(URL, [], Body);
    httpDELETE:
      Resp := FRESTClient.doDELETE(URL, []);
  end;
````

**Comment by danieleteti** [comment]
Fixed in RC11
