### ISSUE TITLE
Compilation error on Delphi 10.1 update1 MVCFramework.DataSet.Utils

### ISSUE THREAD

**Issue by birkangit** [danieleteti/delphimvcframework#110]
Compilation error  at  MVCFramework.DataSet.Utils line 69. 
if not(Value.IsObjectInstance and (Value.AsObject is TJsonArray)) then... 

TValue.IsObjectInstance is not exists on versions prior to 10.2. Tokyo

**Comment by danieleteti** [comment]
FIXED IN RC12
