### ISSUE TITLE
Should add new type TMVCNameCase.ncFirstCharLowerCase?

### ISSUE THREAD

**Issue by seabig6** [danieleteti/delphimvcframework#113]
Should add new type TMVCNameCase.ncFirstCharLowerCase? It is standard json?

TMVCNameCase = (ncAsIs, ncUpperCase, ncLowerCase);

**Comment by joaoduarte19** [comment]
I think this problem was resolved with the addition of `TMVCNameCase.ncCamelCase`.

**Comment by danieleteti** [comment]
Yes, It Is.
