### ISSUE TITLE
New Foundation Middleware

### ISSUE THREAD

**Issue by nkaku** [danieleteti/delphimvcframework#116]
I am thinking of developing a new middleware... sort of standard functionalities for DMVC.

1. User, Groups/Roles, Controller Actions authentication and authorisation via MySQL server
2. API Analytics 

What do you guys think?

**Comment by danieleteti** [comment]
Nice and quite simple to do. It is a specific implementation of `IMVCAuthenticationHandler`.
About the API analytics I was thinking about it some weeks ago. It is even simpler.

However I think that these should be 2 different middleware and not only one.

Where the analytics should write its "statistics" in your opinion? LoggerPro already there :-)

**Comment by danieleteti** [comment]
Any news on this?

**Comment by nkaku** [comment]
Its ready and operational. I have been using it for months. I completely 
forgot about it! Sorry!!

Will upload it tomorrow. :-)

Nirav

**Comment by danieleteti** [comment]
Great! Will be in the 3.1.0 lithium

**Comment by danieleteti** [comment]
Released in 3_1_1-beryllium RC1
Check the sample `\samples\middleware_analytics\`
