### ISSUE TITLE
About "procedure TMVCJsonDataObjectsSerializer.SerializeDynamicArray"

### ISSUE THREAD

**Issue by seabig6** [danieleteti/delphimvcframework#117]
There was commented method at last v3. Do you have any plan to enable?
At line 1006: "if not AValue.GetArrayElement(I).IsObject then"
change to "if not AValue.GetArrayElement(0).IsObject then" and it's ok.

**Comment by danieleteti** [comment]
Has been removed because there are some problems in deserialization. 
However, you can define an alias type for your arrays and use a custom serializer for that type.

```delphi
type 
  TMyArray = TArray<String>;

```

**Comment by seabig6** [comment]
Because Rest.Json unit method TJson.JsonToObject<T> does not support TObjectList<T>, Only Support TArray<T>. Client will use Rest.Json to reflect.
