### ISSUE TITLE
Missing files in 3.x RC11

### ISSUE THREAD

**Issue by fredycc** [danieleteti/delphimvcframework#118]
Some folders such as CSS, JS or PICS have been omitted in the RC versions of version 3.X like RC11, with the latest implementations if I copy these folders from the version 2.X repository there are some exceptions like: EInvalidCast.

This occurs when generating the JSON to be sent through a PUT.

Example (winecellarserver):

main.js

> {"id": "10", <- It is necessary to be treated as an integer: only 10 not "10"
  "name": "DOMAINE SERENEIO",
  "grapes": "Pinot"
  ...}

Thanks

regards

**Comment by danieleteti** [comment]
FIXED IN RC12
