### ISSUE TITLE
function TJWT.IsValidToken(const Token: String; out Error: String): Boolean; fails from example application JWTServer and JWTClient

### ISSUE THREAD

**Issue by littleearth** [danieleteti/delphimvcframework#120]
If I change line 531 in MVCFramework.JWT

` lJPayload := TJSONObject.ParseJSONValue(B64Decode(lPieces[1])) as TJSONObject;`

to

` lJPayload := TJSONObject.ParseJSONValue(URLSafeB64Decode(lPieces[1])) as TJSONObject;
`
it works

**Comment by danieleteti** [comment]
FIXED some times ago, please use RC12+
