### ISSUE TITLE
CORS: JWT is missing in header 

### ISSUE THREAD

**Issue by tbegsr** [danieleteti/delphimvcframework#121]
If you use the cool LiveValidityWindowInSeconds feature in an Angular application you have to include the Access-Control-Expose-Headers. Otherwise the JWT is not available in the header
unit MVCFramework.Middleware.CORS;
procedure TMVCCORSMiddleware.OnBeforeRouting(AContext: TWebContext; var AHandled: Boolean);
add line
AContext.Response.RawWebResponse.CustomHeaders.Values['Access-Control-Expose-Headers'] := 'authentication,authorization';

**Comment by danieleteti** [comment]
FIXED in RC12
