### ISSUE TITLE
Cannot find type for data type tinyint on sql server when Serialization as dataset

### ISSUE THREAD

**Issue by rioda78** [danieleteti/delphimvcframework#122]
i got this error when using function return to dataset;

{function TDM.Findtabelspduad(Search: string): TDataSet;}

DelphiMVCFramework: Error Raised

HTTP Return Code: 500
HTTP Reason Text: "Cannot find type for field "kd_bank" [EMVCSerializationException]"

Exception Class Name : EMVCSerializationException
Exception Message    : Cannot find type for field "kd_bank"

field kd_bank is tinyint in sql server 2008.

on firedac tinyint recognize as ftbyte not as integer type

it resolve/fix with data type mapping in firedac to smallint -> integer type.

**Comment by danieleteti** [comment]
FIXED in RC12
