### ISSUE TITLE
memory leak in procedure TMVCMustacheView.Execute

### ISSUE THREAD

**Issue by pony5551** [danieleteti/delphimvcframework#123]
procedure TMVCMustacheView.Execute;
var
  LFileName: String;
  LTemplate: RawUTF8;
  LMEngine: TSynMustache;
  LPair: TPair<String, TJSONValue>;
  LJContext: TJSONObject;
begin
  LFileName := GetRealFileName(ViewName);
  if not FileExists(LFileName) then
    raise EMVCFrameworkView.CreateFmt('View [%s] not found', [ViewName]);
  LTemplate := StringToUTF8(TFile.ReadAllText(LFileName, TEncoding.UTF8));
  LMEngine := TSynMustache.Parse(LTemplate);
  LJContext := TJSONObject.Create;
  try
    if FViewModel <> nil then
    begin
      for LPair in FViewModel do
      begin
        LJContext.AddPair(LPair.Key, LPair.Value)
      end;
    end;
  except
    LJContext.Free;
    raise;
  end;

  FOutput := UTF8ToString(LMEngine.RenderJSON(LJContext.ToJSON));
end;

There is no release

**Comment by pony5551** [comment]
A memory block has been leaked. The size is: 20

This block was allocated by thread 0x296C, and the stack trace (return addresses) at the time was:
407342 [System.pas][System][@GetMem$qqri][4755]
40899F [System.pas][System][TObject.NewInstance][16919]
4091BE [System.pas][System][@ClassCreate$qqrpvzc][18252]
68851A [System.JSON.pas][System.JSON][Json.TJSONPair.Create][1181]
6A76E2 [MVCFramework.Commons][Generics.Collections.%TDictionary__2$20System.UnicodeStringp22System.Json.TJSONValue%.TPairEnumerator.Create]
6898E2 [System.JSON.pas][System.JSON][Json.TJSONObject.AddPair][1813]
9350F2 [MVCFramework.View.pas][MVCFramework.View][View.TMVCMustacheView.Execute][191]
947760 [MVCFramework.pas][MVCFramework][TMVCController.GetRenderedView][1988]
9478CE [MVCFramework.pas][MVCFramework][TMVCController.LoadView][2015]
40A9BF [System.pas][System][@NewUnicodeString$qqri][24647]
94E3D9 [WebSiteControllerU.pas][WebSiteControllerU][TWebSiteController.PeopleList][88]

The block is currently used for an object of class: TJSONPair

**Comment by pony5551** [comment]
`procedure TMVCMustacheView.Execute;
var
  LFileName: String;
  LTemplate: RawUTF8;
  LMEngine: TSynMustache;
  LPair: TPair<String, TJSONValue>;
  LJContext: TJSONObject;
begin
  LFileName := GetRealFileName(ViewName);
  if not FileExists(LFileName) then
    raise EMVCFrameworkView.CreateFmt('View [%s] not found', [ViewName]);
  LTemplate := StringToUTF8(TFile.ReadAllText(LFileName, TEncoding.UTF8));
  LMEngine := TSynMustache.Parse(LTemplate);
  LJContext := TJSONObject.Create;
  try
    try
      if FViewModel <> nil then
      begin
        for LPair in FViewModel do
        begin
          LPair.Value.Owned := False;
          LJContext.AddPair(LPair.Key, LPair.Value)
        end;
      end;
    except
      LJContext.Free;
      raise;
    end;

    FOutput := UTF8ToString(LMEngine.RenderJSON(LJContext.ToJSON));
  finally
    LJContext.Free;

  end;
end;`


LPair.Value.Owned := False;

and 

//free root node
LJContext.Free;

**Comment by danieleteti** [comment]
Please, use the RC12+, your version seems old.
