### ISSUE TITLE
MVCFramework.Logger.pas Unit 'LoggerPro' not found.

### ISSUE THREAD

**Issue by marcioih** [danieleteti/delphimvcframework#124]
Hello,

I was wondering how do I find delphi for MVCFramework.Logger.pas?
I already put the source path inside the Library Path of the Tool Options ..

Thanks.

**Comment by danieleteti** [comment]
Did you used the correct zip file from the release (do not download the github master zip)? All the dependencies are there.

The latest release is always here: https://github.com/danieleteti/delphimvcframework/releases/latest
