### ISSUE TITLE
Not getting started in 5 minutes

### ISSUE THREAD

**Issue by raelb** [danieleteti/delphimvcframework#127]
Hello,

Unfortunately I have not had a good experience with "Getting Started in 5 minutes".

First you say that one can download the zip file (this is alot quicker than downloading the whole repository), however how will that work? One still needs `lib/dmustache` and `lib/loggerpro` and that is not included in the zip. So anyway I need to download the whole repository...

So I clone the repository and now try to call "Submodule update" on root folder. I get this error response:

git.exe submodule update --init --recursive -- "lib/dmustache"

fatal: No url found for submodule path 'lib/dmustache' in .gitmodules
git.exe submodule update --init --recursive -- "lib/loggerpro"

fatal: No url found for submodule path 'lib/loggerpro' in .gitmodules
git.exe submodule update --init --recursive -- "lib\dmustache"

fatal: No url found for submodule path 'lib/dmustache' in .gitmodules
git.exe submodule update --init --recursive -- "lib\loggerpro"

fatal: No url found for submodule path 'lib/loggerpro' in .gitmodules

git did not exit cleanly (exit code 128) (4781 ms @ 2018/03/19 7:53:10 PM)

**Comment by danieleteti** [comment]
Sorry, you didn't follow the guide (https://danieleteti.gitbooks.io/delphimvcframework/content/chapter_getting_started.html)
The zip file to dowload is not the repo zip file, but the release zip file (https://github.com/danieleteti/delphimvcframework/releases/latest).

Please, follow the steps and let us know.
