### ISSUE TITLE
Body ContentType application/x-www-form-urlencoded not supported

### ISSUE THREAD

**Issue by shariful2011** [danieleteti/delphimvcframework#129]
I can't POST data using Rad Studio's RESTDebuger. I got exception "Body ContentType application/x-www-form-urlencoded not supported". I followed sample "articles_crud_server". Same code just change on database. How do I POST data?
![screenshot_1](https://user-images.githubusercontent.com/634779/38370993-3cbaacea-390d-11e8-811b-410ecf0f2d04.png)

**Comment by shariful2011** [comment]
If I use it on Postman, "Not Found" response received.

**Comment by danieleteti** [comment]
Strange, it works as expected since version 2.x. Check `\samples\serversideviews\`. 
Can you give me more info?

**Comment by shariful2011** [comment]
Please see this video https://mega.nz/#!OoUnxA7Q!y-9HGO3QXCPNB8XzRrfkdczmweeUkuoLX070kjUhXaA. My client will be in other language, how can other can access my server?

**Comment by shariful2011** [comment]
I found the problem, problem was on my Add method.
