### ISSUE TITLE
GUID

### ISSUE THREAD

**Issue by attikov** [danieleteti/delphimvcframework#131]
What is that? :o

{$IFDEF TOKYOORBETTER}
          ftGuid:
            AJsonObject.S[FieldName] := GUIDToString(ADataSet.Fields[I].AsGuid);
{$ENDIF}

there was GUID prior to tokyo too....

          ftGuid:
            AJsonObject.S[FieldName] := ADataSet.Fields[I].AsString;

**Comment by danieleteti** [comment]
On which version do you tested this?

**Comment by attikov** [comment]
Hi Daniel,

If you are telling me how can I identify the version based on the sources I can tell you.
However, this has been fixed in the current sources so I don't know why is this still important.
I think, I'm not sure, that this was the very first 3.0 release and there was more problems with this release (actually with "Dataset.Utils", see FB history). Probably I just had bad luck with the timing, and I also didn't use the lib since then so I can't really help further.
