### ISSUE TITLE
TMVCController as a TDataModule

### ISSUE THREAD

**Issue by marcelologica** [danieleteti/delphimvcframework#134]
I would like the TMVCController to be descended from TDataModule, to have a similar operation to the DataSnap TServerMethods. This would facilitate RAD development by dragging components such as database connections, queries and more.

**Comment by danieleteti** [comment]
You can use the json-rpc interface that support this approach. Is it a viable solution for you?

**Comment by marcelologica** [comment]
Actually what I would like was to drag and drop components like dataset, connections etc inside the controller, without having to create a separate DataModule or create those objects by code.

**Comment by danieleteti** [comment]
Can we close this issue?

**Comment by marcelologica** [comment]
Yes, you can.

Thank you.

De: Daniele Teti <notifications@github.com>
Responder para: danieleteti/delphimvcframework <reply@reply.github.com>
Data: terça-feira, 9 de abril de 2019 02:34
Para: danieleteti/delphimvcframework <delphimvcframework@noreply.github.com>
Cc: Marcelo Varela <marcelonatal@msn.com>, Author <author@noreply.github.com>
Assunto: Re: [danieleteti/delphimvcframework] TMVCController as a TDataModule (#134)


Can we close this issue?
