### ISSUE TITLE
MVCFramework.Console: EnableVirtualTerminalProcessing crashes on OS < Windows 10

### ISSUE THREAD

**Issue by raketenwurm69** [danieleteti/delphimvcframework#140]
When I include MVCFramework.Console.pas in a unit it calls EnableVirtualTerminalProcessing in initialization section where it calls SetConsoleMode. On Windows Server 2011 and 2012 the application closes itself with no error, but leaving an entry in the event log "Error in KERNELBASE.dll". 

Possible solution: Check if OS >= Windows 10 before calling SetConsoleMode and output an error message in the console window.

**Comment by danieleteti** [comment]
Did you fixed the problem? Found a better solution?

**Comment by danieleteti** [comment]
It seems to be supported where you are using it:
https://docs.microsoft.com/en-us/windows/console/setconsolemode#requirements

**Comment by raketenwurm69** [comment]
As I am using console mode only during development and not in the final product, I decided to not use the colored console output in my DMVC-Server anymore.

**Comment by danieleteti** [comment]
Fixed in RC8
