### ISSUE TITLE
How to execute more than 1 call simultaneously by TRestClient Asynch wise

### ISSUE THREAD

**Issue by shariful2011** [danieleteti/delphimvcframework#145]
How to execute more than 1 call simultaneously by TRestClient Asynch wise? I need to send request at least 3 API call to server. All calls will be doGET

**Comment by shariful2011** [comment]
I tried to run 2 API call simultaneously and got AV in TRESTClient.StartAsynchRequest method line number 1541, though I am calling it Synchronizly. This is why asked how to know when Asynch method is completed.

**Comment by joaoduarte19** [comment]
Use the new TMVCRESTClient. You can control the response to your request using anonymous methods.
