### ISSUE TITLE
Access the context in the IMVCAuthenticationHandler.OnAuthentication

### ISSUE THREAD

**Issue by joaoantonio19** [danieleteti/delphimvcframework#146]
I am implementing JWT authentication in my webserver. I missed accessing the context in the OnAuthentication method of the IMVCAuthenticationHandler. In addition to the user and password I provide additional headers to validate the login.
I changed the IMVCAuthenticationHandler interface to add the context. It is working correctly for my use case. Is that correct?

![image](https://user-images.githubusercontent.com/13373632/44264402-da3a1100-a1f8-11e8-83cf-1ad90422cbe3.png)

**Comment by danieleteti** [comment]
If you need al the `WebContext` than it's ok. We are planning to introduce this behaviour in the next version.

However, it is better to don't use `AContext: TObject`, use the correct type `AContext: TWebContext`.
