### ISSUE TITLE
Add `TWebContext` in `IMVCAuthenticationHandler` methods

### ISSUE THREAD

**Issue by danieleteti** [danieleteti/delphimvcframework#147]
Check the need of this user.
https://github.com/danieleteti/delphimvcframework/issues/146

It is the first time that some user ask for this, but it could be e nice addition.

Anyone interested in this? (This change will break all the current code, however it is easily fixable).

**Comment by fastbike** [comment]
This looks like a useful addition, to be able to get access to various request headers etc.
