### ISSUE TITLE
Disable 404 for Unhanded Action

### ISSUE THREAD

**Issue by littleearth** [danieleteti/delphimvcframework#15]
Allowing the MVC Framework to not 404 if a page or action is not found will allow the WebModule to still handle additional requests. This can allow SOAP to remain working.

Not sure if others would have interest in this; fairly simple change, and I have made it a config item.

function TMVCEngine.ExecuteAction(Sender: TObject; Request: TWebRequest;
  Response: TWebResponse): boolean;

 if Config[TMVCConfigKey.AllowUnhandledAction] = 'false' then    //tristan
begin
                 Http404(Context);
                 handled := True;  //tristan
                Log(TLogLevel.levNormal, Request.Method + ':' +
                  Request.RawPathInfo + ' -> NO ACTION ' + ' - ' +
                  Response.StatusCode.ToString + ' ' + Response.ReasonString);
end;

finally
      Context.Response.FlushOnDestroy := Handled; // tristan
      Context.Free;
end;

Changes to TMCVWebResponse to allow a FlushOnDestroy to be stopped. 

 private
    FStreamOutputDone: boolean;
    FFlushOnDestroy: boolean;  // tristan

public
    property FlushOnDestroy: boolean read FFlushOnDestroy write FFlushOnDestroy; // tristan

destructor TMVCWebResponse.Destroy;
begin
  if FFlushOnDestroy then   // tristan
    Flush;
  inherited;
end;

**Comment by danieleteti** [comment]
Interesting, can you give me a real-word case?

**Comment by littleearth** [comment]
I have created a sample application in a pull request

**Comment by danieleteti** [comment]
Merged
