### ISSUE TITLE
CORS-Property "Access-Control-Expose-Headers" can not be set from outside

### ISSUE THREAD

**Issue by raketenwurm69** [danieleteti/delphimvcframework#150]
I am using Angular to access a DMVC-REST-Endpoint. For this I am also using the CORS-Middleware. I want to receive custom header entries with every response on the client side (like "pagination-total-count"). Unfortunally the CORS-Property "Access-Control-Expose-Headers" is set to a fixed value of "authentication, authorization".

It might be a good idea if the "Expose-Headers" could be set from outside. Either by using a property or extending the Create-Method like
constructor TMVCCORSMiddleware.Create(const AAllowedOriginURL: string; const AAllowsCredentials: Boolean; AExposeHeaders: string);

**Comment by danieleteti** [comment]
In 3.1 (lithium) the middleware constructor is:

    constructor Create(
      const AAllowedOriginURL: string = TMVCCORSDefaults.ALLOWS_ORIGIN_URL;
      const AAllowsCredentials: Boolean = TMVCCORSDefaults.ALLOWS_CREDENTIALS;
      const AExposeHeaders: String = TMVCCORSDefaults.EXPOSE_HEADERS;
      const AAllowsHeaders: String = TMVCCORSDefaults.ALLOWS_HEADERS;
      const AAllowsMethods: string = TMVCCORSDefaults.ALLOWS_METHODS
      ); virtual;
