### ISSUE TITLE
Exception when server is in DLL

### ISSUE THREAD

**Issue by przewa** [danieleteti/delphimvcframework#153]
Basic problem is with:

constructor TWebContext.Create(
  const ARequest: TWebRequest;
  const AResponse: TWebResponse;
  const AConfig: TMVCConfig;
  const ASerializers: TDictionary<string, IMVCSerializer>);
begin
  inherited Create;
  FIsSessionStarted := False;
  FSessionMustBeClose := False;
  FWebSession := nil;

  if IsLibrary then
  begin

    {$IFDEF WEBAPACHEHTTP}

    if ARequest is TApacheRequest then
      FRequest := TMVCApacheWebRequest.Create(ARequest, ASerializers)

      {$IFNDEF LINUX}

    else if ARequest is TISAPIRequest then
      FRequest := TMVCISAPIWebRequest.Create(ARequest, ASerializers)

      {$ENDIF}

    else
      raise EMVCException.Create('Unknown request type ' + ARequest.ClassName);

    {$ELSE}

      FRequest := TMVCISAPIWebRequest.Create(ARequest, ASerializers)

    {$ENDIF}

  end
  else
    FRequest := TMVCINDYWebRequest.Create(ARequest, ASerializers);

  FResponse := TMVCWebResponse.Create(AResponse);
  FConfig := AConfig;
  FSerializers := ASerializers;
  FData := TDictionary<string, string>.Create;
  FLoggedUser := nil;
end;

When I change this constructor to:

constructor TWebContext.Create(
  const ARequest: TWebRequest;
  const AResponse: TWebResponse;
  const AConfig: TMVCConfig;
  const ASerializers: TDictionary<string, IMVCSerializer>);
begin
  inherited Create;
  FIsSessionStarted := False;
  FSessionMustBeClose := False;
  FWebSession := nil;

  (*if IsLibrary then
  begin

    {$IFDEF WEBAPACHEHTTP}

    if ARequest is TApacheRequest then
      FRequest := TMVCApacheWebRequest.Create(ARequest, ASerializers)

      {$IFNDEF LINUX}

    else if ARequest is TISAPIRequest then
      FRequest := TMVCISAPIWebRequest.Create(ARequest, ASerializers)

      {$ENDIF}

    else
      raise EMVCException.Create('Unknown request type ' + ARequest.ClassName);

    {$ELSE}

      FRequest := TMVCISAPIWebRequest.Create(ARequest, ASerializers)

    {$ENDIF}

  end
  else*)
    FRequest := TMVCINDYWebRequest.Create(ARequest, ASerializers);

  FResponse := TMVCWebResponse.Create(AResponse);
  FConfig := AConfig;
  FSerializers := ASerializers;
  FData := TDictionary<string, string>.Create;
  FLoggedUser := nil;
end;

Rest communication is working, but program stops on FreeLibrary and hangs.

**Comment by przewa** [comment]
I also tried to create and run server in main application, and move 
fMvcEngine := fMvcEngine.AddController(TMainController)
into dll, but in this case is another problem in:
function TMVCRouter.ExecuteRouting(const ARequestPathInfo: string;
  const ARequestMethodType: TMVCHTTPMethodType;
  const ARequestContentType, ARequestAccept: string;
  const AControllers: TObjectList<TMVCControllerDelegate>;
  const ADefaultContentType: string;
  const ADefaultContentCharset: string;
  var ARequestParams: TMVCRequestParamsTable;
  out AResponseContentMediaType: string;
  out AResponseContentCharset: string): Boolean;

on line 204 LAttributes := LRttiType.GetAttributes; is invalid typecast exception

**Comment by danieleteti** [comment]
Did you fixed the problem? Can you give me a simple example to show the problem?

**Comment by danieleteti** [comment]
This version is fixed and works with the current repo version.

[mvc_dll.zip](https://github.com/danieleteti/delphimvcframework/files/3087148/mvc_dll.zip)

More info about the issue you faced [here](http://jsbattig.blogspot.com/2013/07/dlls-deadlocking-when-getting-unloaded.html) (WARNING! I do not suggest the solution provided in the article. Each case must be analized separately. LoggerPro uses the correct approach.).

**Comment by danieleteti** [comment]
In the repo there is a new sample specific for putting server in DLL (Server_in_DLL)
