### ISSUE TITLE
Unit to manage controller registry

### ISSUE THREAD

**Issue by joaoduarte19** [danieleteti/delphimvcframework#154]
To make it easier to add my controllers to MVCEngine, I created a singleton class that stores a list of my controllers and adds them to my engine.

[MVCFramework.Controllers.Register.zip](https://github.com/danieleteti/delphimvcframework/files/2398347/MVCFramework.Controllers.Register.zip)

To use the unit, add it to the uses of your controller and in the initialization section register your controller:
![image](https://user-images.githubusercontent.com/13373632/45774997-e1ec3b80-bc24-11e8-84ca-acb9bc3260d8.png)

In your WebModule add the controllers to your engine:
![image](https://user-images.githubusercontent.com/13373632/45774955-c08b4f80-bc24-11e8-8395-6051c42b7ba7.png)

I'm not sure if this is a good practice, but it made my work faster and I do not need to add all my controllers to the uses of my webmodule.

**Comment by danieleteti** [comment]
Nice for single `TMVCEngine` but what about the server container?
Check `samples\servercontainer\BasicDemo.dproj`

**Comment by joaoduarte19** [comment]
This class was designed for single engine use. But it can be adapted for use with the server container.

**Comment by joaoduarte19** [comment]
I made an adaptation on the unit to register a controller for a named server
``` pascal
initialization 
  TControllersRegister.Instance.RegisterController(TMyController, 'MyServerName');
end.
```
In your WebModule add the controllers to your engine:
``` pascal
 TControllersRegister.Instance.AddControllersInEngine(FEngine, 'MyServerName');
```
[MVCFramework.Controllers.Register.zip](https://github.com/danieleteti/delphimvcframework/files/2621038/MVCFramework.Controllers.Register.zip)

With these adaptations it can be used with the server container

**Comment by marcosbarreto** [comment]
This is great many iniciants forget to add the controllers on webmodule

**Comment by danieleteti** [comment]
Yes, will be in the next milestone. You can also provide a simple example if you want.

**Comment by joaoduarte19** [comment]
Here is a simple sample server with TControllersRegister.
[demo.zip](https://github.com/danieleteti/delphimvcframework/files/2900311/demo.zip)

**Comment by danieleteti** [comment]
Good job. Your changes are in the repo. Thank you.
