### ISSUE TITLE
TMVCJWTAuthenticationMiddleware: TNetEncoding.URL.Decode for jwtusername

### ISSUE THREAD

**Issue by Ravaut123** [danieleteti/delphimvcframework#156]
The Header don't like characters ä, ç ... 
I did not find something to convert the header like the body. (content-type: application/json; charset=utf-8)
On the client site I encode the jwtusername (cräv --> cr%C3%A4v).
The code catch the username in function TMVCJWTAuthenticationMiddleware.OnBeforeRouting
But there the jwtuserneme is not decode.

Is it possible to change the code?

`UserName := AContext.Request.Headers['jwtusername'];`

change to

`UserName := TNetEncoding.URL.Decode(AContext.Request.Headers['jwtusername']);`

**Comment by danieleteti** [comment]
FIXED IN 3.1 (lithium)

**Comment by tbegsr** [comment]
Hello
I've a problem with an Angular 7 application with JWT.
I put the password in the header. 
With MVC 3.0 it works fine.
But since 3.1 it fails if % is included in the password.
Can we change this?

**Comment by danieleteti** [comment]
Did you urlencoded the header values from client side?

**Comment by tbegsr** [comment]
This is my code
login(username: string, password: string) {
        //Add Username Password to the header
        var headers = new HttpHeaders().set('Content-Type', 'application/json; charset=utf-8');
        headers = headers.set('jwtusername', username);
        headers = headers.set('jwtpassword', password);
        var options =  {
            headers: headers
        };
        
        return this.http.post<any>(`${this.URL}/api/login`,'', options)

**Comment by tbegsr** [comment]
Thx. Now it works fine
        headers = headers.set('jwtusername', encodeURI(username));
