### ISSUE TITLE
Correction in TMVCJsonDataObjectsSerializer.DataSetToJsonArray

### ISSUE THREAD

**Issue by joaoduarte19** [danieleteti/delphimvcframework#159]
Change the TMVCJsonDataObjectsSerializer.DataSetToJsonArray. Add the highlighted line:
![change](https://user-images.githubusercontent.com/13373632/47786347-456c8d00-dcea-11e8-89b9-bbb73edb74d7.png)
This change ensures that the entire dataset is serialized.

**Comment by fastbike** [comment]
I'd do this outside of the dataset, in case you only want to serialise part of it.

**Comment by joaoduarte19** [comment]
That's a good point. But I think most of the time you want to serialize the entire dataset.

**Comment by danieleteti** [comment]
This is the intended behaviour. If you need something different you can inherit from the default serializer and override the methods you need.
