### ISSUE TITLE
AJSONValue.ToJSON is Encoding use TEncoding.Default (Unicode)

### ISSUE THREAD

**Issue by sicmy** [danieleteti/delphimvcframework#16]
With the TEncode.Default Korean is broken because Encode.

unit MVCFrameWork 
InternalRender

{$IF CompilerVersion <= 27}
	JString := AJSONValue.ToString; // requires the patch
{$ELSE}
	JString := AJSONValue.ToJSON; // since XE7 it works using ToJSON
{$ENDIF}

ToString is Well

**Comment by danieleteti** [comment]
Can you write a sample test? I don't know Korean so I cannot write a unit test for it.

**Comment by danieleteti** [comment]
Works with asian characters right now
