### ISSUE TITLE
Error TMVCAbstractSerializer invalid type cast in linux build

### ISSUE THREAD

**Issue by anlopes123** [danieleteti/delphimvcframework#161]
I'm compiling a project in ubuntu linux and the error that I put in the title on the line below: 
LogD ('Registering TypeSerializer for:' + string (ATypeInfo.Name))
I did the correction as per the code below
````
procedure TMVCAbstractSerializer.RegisterTypeSerializer(const ATypeInfo: PTypeInfo; AInstance: IMVCTypeSerializer);
begin
   {$IFNDEF AUTOREFCOUNT}
     LogD('Registering TypeSerializer for: ' + string(ATypeInfo.Name));
  {$ELSE}
     LogD('Registering TypeSerializer for: ' + ATypeInfo.Name.ToString);
  {$ENDIF}
  FTypeSerializers.AddOrSetValue(ATypeInfo, AInstance);
end;

**Comment by igorscherer7** [comment]
Do you have any version started to complement in apache linux?

**Comment by danieleteti** [comment]
DMVCFramework works on linux since 3.x

Are you talking about this issue? Any others?

**Comment by igorscherer7** [comment]
I am testing a version  delphimvcframework-3.1.1-beryllium-RC2  and giving the following error:

[DCC Error] MVCFramework.Serializer.JsonDataObjects.pas(1088): E2010 Incompatible types: 'string' and 'Byte'

**Comment by danieleteti** [comment]
Please, use the last version when report issue please.
