### ISSUE TITLE
now WebRequestPathInfo is One More Decoded

### ISSUE THREAD

**Issue by sicmy** [danieleteti/delphimvcframework#17]
When You Call procedure "/customers/($id)"  In the Render Sample 
example) localhost:8080/customers/($id)  === localhost:8080/customers/권 (권 is korean word)

== i solved   (i don't know this Code ㅠㅠ)
MVCFramework.Router Unit 97 Line

this is 
// daniele
  LWebRequestPathInfo := TIdURI.URLDecode(LWebRequestPathInfo);

// Change
 LWebRequestPathInfo := TIdURI.PathEncode(LWebRequestPathInfo);

**Comment by danieleteti** [comment]
Good point.
Can you give me a testcase?

**Comment by sicmy** [comment]
HI~

Sorry for the late reply.!!


Attached TestCase, Images..

Good bye~!


2015-11-10 23:29 GMT+09:00 Daniele Teti <notifications@github.com>:

**Comment by danieleteti** [comment]
The attachment? J

**Comment by sicmy** [comment]
<a href = "https://s3-ap-northeast-1.amazonaws.com/sicmydelphi/unittests.zip"> download hear </a>

**Comment by danieleteti** [comment]
What's the intended test?
Running DMVCFrameworkTest_KO.dproj I get no errors/fails at all.
Am I missing something?
