### ISSUE TITLE
IsObjectValue not defined prior to 10.2 - MVCFramework.JSONRPC.pas

### ISSUE THREAD

**Issue by tkoscielski** [danieleteti/delphimvcframework#170]
There are three instances of IsObjectInstance used on lines 627, 807, and 847 in `MVCFramework.JSONRPC.pas`. This is not available in 10.1 and there was a previous fix in Issue#110 that fixed `MVCFramework.Dataset.Utils.pas`.  Could that same issue be resolved here.

The fix for that was the following **$IFDEF**.
```
    if not({$IFDEF TOKYOORBETTER}Value.IsObjectInstance and {$ENDIF} (Value.AsObject is TJSONArray)) then
        raise Exception.Create('LoadFromTValue requires a TValue containing a TJDOJsonArray');
```
Could something like this be used here? Below is a sample of the current code.
Line 627: MVCFramework.JSONRPC.pas
```
                if lRes.IsObjectInstance then
                  lRes.AsObject.Free;
```
Thanks.

**Comment by danieleteti** [comment]
FIXED in 3.1 (lithium)
