### ISSUE TITLE
DMVC Master does not compile

### ISSUE THREAD

**Issue by marcosbarreto** [danieleteti/delphimvcframework#171]
1) unit MVCFramework.ActiveRecordController;

procedure TMVCActiveRecordController.GetEntities(const entityname: string);
...
lResp := TMVCActiveRecordListResponse.Create(TMVCActiveRecord.SelectRQL(lARClassRef, lRQL, lMapping, lRQLBackend, GetMaxRecordCount), True);
...
SelectRQL do not have all this parameters, then I removed them, i dont know if this is correct or no!

after this...

2) unit MVCFramework.Middleware.JWT (unit MVCFramework.TypesAliases; do not exists)
replace with System.JSON;

3) then i compile but i get a last error

[dcc32 Error] E2223 $DENYPACKAGEUNIT 'Web.WebBroker' cannot be put into a package

How we can fix this Daniele?

**Comment by danieleteti** [comment]
The HEAD is under heavy refactoring before the features freeze of 3.1 (lithium). For production use please use the 3.0 (hydrogen). ASAP we'll be fixed the head too.
