### ISSUE TITLE
Error compiling activerecord_showcase in Berlin

### ISSUE THREAD

**Issue by raelb** [danieleteti/delphimvcframework#172]
Hello,

I receive the following errors when trying to compile the **activerecord_showcase** project in Berlin. I'm using the latest sources (16 Dec)

[dcc32 Error] MVCFramework.ActiveRecord.pas(222): E2086 Type 'TMVCActiveRecord' is not yet completely defined
[dcc32 Error] MVCFramework.ActiveRecord.pas(224): E2086 Type 'TMVCActiveRecord' is not yet completely defined
[dcc32 Error] MVCFramework.ActiveRecord.pas(225): E2511 Type parameter 'T' must be a class type
[dcc32 Error] MVCFramework.ActiveRecord.pas(232): E2086 Type 'TMVCActiveRecord' is not yet completely defined
[dcc32 Error] MVCFramework.ActiveRecord.pas(233): E2511 Type parameter 'T' must be a class type
[dcc32 Error] MVCFramework.ActiveRecord.pas(235): E2086 Type 'TMVCActiveRecord' is not yet completely defined
[dcc32 Error] MVCFramework.ActiveRecord.pas(236): E2511 Type parameter 'T' must be a class type
[dcc32 Error] MVCFramework.ActiveRecord.pas(237): E2086 Type 'TMVCActiveRecord' is not yet completely defined
[dcc32 Error] MVCFramework.ActiveRecord.pas(239): E2086 Type 'TMVCActiveRecord' is not yet completely defined
[dcc32 Error] MVCFramework.ActiveRecord.pas(245): E2086 Type 'TMVCActiveRecord' is not yet completely defined
[dcc32 Error] MVCFramework.ActiveRecord.pas(245): E2511 Type parameter 'T' must be a class type

Thanks

**Comment by danieleteti** [comment]
Not all the demos have been updated to the very last changes. Please, use the last stable version in production (3.0.0 hydrogen)
