### ISSUE TITLE
DataSetToJsonArray changes the current record position of the DataSet

### ISSUE THREAD

**Issue by elimwang** [danieleteti/delphimvcframework#173]
After using MVCFramework. Serializer. JsonDataObjects. DataSetToJsonArray, the original DataSet record location changed, resulting in the need to remember the record location before using DataSetToJsonArray, and then restore to the previous location after using it. Because DataSetToJsonArray using DataSet.Next...

**Comment by danieleteti** [comment]
That is the intended behaviour. In the majority of the cases, you just need to render the dataset and than free it.
