### ISSUE TITLE
TList<integer>to json string and back

### ISSUE THREAD

**Issue by przewa** [danieleteti/delphimvcframework#175]
Is it possible to use TList<integer> and pass it into controller function?

**Comment by danieleteti** [comment]
What does it mean "controller function"? Action?

You need to post a list of integers to a controller/action endpoint?

If so, the better things is to wrap them into a json array (or whaever serialization format you use).

**Comment by przewa** [comment]
TPracownikAbsencjeGetListElement = class
    private
      fPrc: integer;
    public
      property Prc: integer read fPrc write fPrc;
  end;

  TPracownikAbsencjeGetLis = TObjectList<TPracownikAbsencjeGetListElement>;

  TPracownikAbsencjeRequestTransport = class
    private
      fDataOd: TDate;
      fDataDo: TDate;
      fPrcList: TPracownikAbsencjeGetLis;
    public
      property PrcList: TPracownikAbsencjeGetLis read fPrcList write fPrcList;
      property DataOd: TDate read fDataOd write fDataOd;
      property DataDo: TDate read fDataDo write fDataDo;
      //
      constructor Create; overload;
      destructor Destroy; override;
  end;

Render Result of TPracownikAbsencjeRequestTransport is:

{
    "PrcList": [
        {
            "Prc": 0
        },
{
            "Prc": 1
        }
    ],
    "DataOd": "2019-03-18",
    "DataDo": "2019-03-18"
}


What should the class TPracownikAbsencjeRequestTransport look like that after using Render json it looks like this:

{
    "PrcList": [
        {
           0,1
        }
    ],
    "DataOd": "2019-03-18",
    "DataDo": "2019-03-18"
}

**Comment by joaoduarte19** [comment]
Define your class like this:
```` delphi
  TPracownikAbsencjeGetLis = TArray<Integer>;

  TPracownikAbsencjeRequestTransport = class
  private
    fDataOd: TDate;
    fDataDo: TDate;
    fPrcList: TPracownikAbsencjeGetLis;
  public
    property PrcList: TPracownikAbsencjeGetLis read fPrcList write fPrcList;
    property DataOd: TDate read fDataOd write fDataOd;
    property DataDo: TDate read fDataDo write fDataDo;
  end;
```` 
Your JSON result will look something like this:
```` json
{
	"PrcList": [
		0,
		1,
		2,
		3
	],
	"DataOd": "2019-10-10",
	"DataDo": "2019-10-16"
}
````
I think this is the result you expect.
