### ISSUE TITLE
Problem updating to version 3.1.0 lithium

### ISSUE THREAD

**Issue by maiconsi** [danieleteti/delphimvcframework#177]
When upgrading to the new version my IDE reported me several errors, I'm using the Delphi 10 Seattle
Here are the corrected items:

-> MVCFramework.JSONRPC.pas;

procedure AppendTValueToJsonArray(const Value: TValue; const ParamType: TJSONRPCParamDataType;
  const JSONArr: TJDOJsonArray);

*Line: 364    
    pdtDateTime:
      begin
        JSONArr.Add(DateTimeToISOTimeStamp(Value.AsExtended));
      end;
    pdtDate:
      begin
        JSONArr.Add(DateToISODate(Value.AsExtended));
      end;
    pdtTime:
      begin
        JSONArr.Add(TimeToISOTime(Value.AsExtended));
      end;

-> MVCFramework.Middleware.JWT.pas
procedure TMVCJWTAuthenticationMiddleware.OnBeforeControllerAction(AContext: TWebContext;
  const AControllerQualifiedClassName, AActionName: string; var AHandled: Boolean);

*Line: 183
    AuthToken := Trim(TNetEncoding.URL.Decode(AuthToken));

**Comment by danieleteti** [comment]
Could you send me the unit compilable with Seattle (whithout changing the format style, please).?

**Comment by maiconsi** [comment]
Attached is the requested files.



[DMVC.zip](https://github.com/danieleteti/delphimvcframework/files/2741743/DMVC.zip)

**Comment by danieleteti** [comment]
Fixed in 3.1.1-beryllium RC1
