### ISSUE TITLE
Issue with loggerpro package in Lithium

### ISSUE THREAD

**Issue by MarkBracey** [danieleteti/delphimvcframework#178]
This is my second attempt at installing DelphiMVC. Previous version IDE package installed fine.  

The logger pro package does not install because the links to the source files are not correct.  Should I expect them to be correct out of the box or is this something I am supposed to correct?

**Comment by danieleteti** [comment]
Which package? Delphi version? Error?

**Comment by danieleteti** [comment]
Fixed in the LoggerPro 1.3.1
The next version of DMVCFramework will use that version. You can just overwrite LoggerPro 1.3.1 release over the `dmvcframework\libs\loggerpro` path.

**Comment by danieleteti** [comment]
The fix is simple, but this doesn't affect you if you don't use "Link With Runtime Packages"
