### ISSUE TITLE
TRESTClient httpPATCH method

### ISSUE THREAD

**Issue by veex-ua** [danieleteti/delphimvcframework#179]
https://github.com/danieleteti/delphimvcframework/blob/9acb82b8f80e1f496b8761979cc27d99951a2525/sources/MVCFramework.RESTClient.pas#L1464-L1468
As per Remy Lebeau SO [answer](https://stackoverflow.com/a/24557716/7585036) it has been implemented

**Comment by joaoduarte19** [comment]
I think this problem can be completed, because in the new TMVCRESTClient we have already implemented all supported HTTP methods

**Comment by danieleteti** [comment]
Yes, I think so. The solution is to wait for the 3.2.2-nitrogen (or just use the repo version until then).
