### ISSUE TITLE
Redirect to another controller

### ISSUE THREAD

**Issue by littleearth** [danieleteti/delphimvcframework#18]
Hi, Is the following possible

2 controllers
/customers
/orders

Could the customer controller be redirected to order controller
eg
/customer/3/orders

Tristan

**Comment by fastbike** [comment]
You would be better off restating the URL as /orders?customer=3

**Comment by littleearth** [comment]
Yeah, understand. Was just a question because it kind of looked like it was possible

FMVCEngine.AddController(TControllerCustomers).AddController(TControllerOrders); 

But when you see the code AddController it is not a parent child relationship.
