### ISSUE TITLE
Custom Types Serializer are broken

### ISSUE THREAD

**Issue by wiphi** [danieleteti/delphimvcframework#182]
Version: 3.1.1-RC1
Delphi: 10.2 Tokyo

In the readme is the new registration for custom serializers descriped as
`Changed! Custom Types Serializer must be registered by media-type only, without charset definition (e.g. just application/json and not application/json;charset=utf-8)`

I want to add some custom type handlers, but it seems to be broken.
How to reproduce:
- Open up the `renders_spring4d_nullable` sample
- compile and run
- open the URL `localhost:8080/api/parent/1`
- Exception `EMVCSerializationException` will be raised

Since the registration is:
https://github.com/danieleteti/delphimvcframework/blob/10f36cafc3a80350124fa3ac9c1d0623380d4ad4/samples/renders_spring4d_nullables/WebModuleU.pas#L67-L68
... the serializer do not found them.
When I backport the registration to `BuildContentType('application/json', 'utf-8')` it works again.

**Comment by danieleteti** [comment]
FIXED IN 3.1.1-beryllium-RC3
