### ISSUE TITLE
No response is sent to the client when an exception occurred in Custom Auth Handler.

### ISSUE THREAD

**Issue by davuteryilmaz** [danieleteti/delphimvcframework#184]
https://github.com/danieleteti/delphimvcframework/blob/73573c0130353be588ec825913d8fc6a20610de6/samples/CustomAuth/AuthHandlerU.pas#L56-L69

I added `raise EDivByZero.Create('Division by zero.');` this line to the method above and run the sample app. Could not get any response when post http://localhost:8080/system/users/logged by [Postman](https://www.getpostman.com/). The exception is logged but no respone is sent. Is it posible to send HTTP 500 response when an exception raised in the auth handler? Thanks.

**Comment by danieleteti** [comment]
Will be fixed in 3.1.1-beryllium-RC3
