### ISSUE TITLE
Delphi in React Native

### ISSUE THREAD

**Issue by mahipalsingh7** [danieleteti/delphimvcframework#185]
Can i use Delphi in my react native project. If yes , can you please share any link or doc for reference

**Comment by leogregianin** [comment]
@mahipalsingh7, Delphi and this delphimvcframework are for backend development that generate REST API for the connect frontend, such as react native, reactjs, angular, flutter, vuejs and also delphi projects.

Has some references like [https://github.com/danieleteti/delphimvcframework/tree/master/samples/angular](url) and [https://www.slideshare.net/marcobreveglieri/sviluppo-web-con-delphi-e-react](url)
