### ISSUE TITLE
Problem render properties Nullable type

### ISSUE THREAD

**Issue by cvpereira** [danieleteti/delphimvcframework#188]
I have a model with some properties Nullable types, but when i call the render method an error happens

Cannot serialize "PropertyName" of TypeKind tkRecord

How can i resolve this problem?

**Comment by joaoduarte19** [comment]
Your nullable type must be registered in TMVCEngine.
See .\samples\renders_spring4d_nullables.

**Comment by cvpereira** [comment]
> Your nullable type must be registered in TMVCEngine.
> See .\samples\renders_spring4d_nullables.

Is needed create a class custom to serialize exactly as example? I'm using the ORM (ORMBr) and have the class "ormbr.types.nullable" where have the operations with the Nullable types.

**Comment by danieleteti** [comment]
Custom types serializers works as shown in the example. You have to implement a specific serializer.

**Comment by cvpereira** [comment]
> Custom types serializers works as shown in the example. You have to implement a specific serializer.

thanks
