### ISSUE TITLE
delphi XE7 Install error - LoggerPro - COMPATIBILITY MANTAINER

### ISSUE THREAD

**Issue by DanieleBarbato** [danieleteti/delphimvcframework#199]
There is an issue in LoggerPro.pas:
`[dcc32 Error] LoggerPro.pas(500): E2003 Undeclared identifier: 'Current'
constructor TLogItem.Create(const aType: TLogType; const aMessage, aTag: string);
begin
  Create(aType, aMessage, aTag, now, TThread.Current.ThreadID);
end;
`

a simple solution is to use TThread.CurrentThread.ThreadID:
`constructor TLogItem.Create(const aType: TLogType; const aMessage, aTag: string);
begin
  Create(aType, aMessage, aTag, now, TThread.CurrentThread.ThreadID);
end;
`

**Comment by danieleteti** [comment]
OK, corrected in the repo
