### ISSUE TITLE
delphi XE7 Install error - DMVC - COMPATIBILITY MANTAINER

### ISSUE THREAD

**Issue by DanieleBarbato** [danieleteti/delphimvcframework#200]
Here same issue during my compatibility test:

`[dcc32 Fatal Error] MVCFramework.pas(69): F1026 File not found: '\delphimvcframework\packages\dxe7\Web.ReqMulti.dcu' (unit scope "Web" indicates Win64, Win32 only)
{$IFNDEF VER320}
  Web.ReqMulti,
`

solution:
**{$IFNDEF VER320}
  ReqMulti,**

<hr>

`[dcc32 Error] MVCFramework.JSONRPC.pas(571): E2003 Undeclared identifier: 'tkAnsiString'`

no solution for now

<hr>
[dcc32 Error] MVCFramework.pas(1731): E2003 Undeclared identifier: 'ReadTotalContent'

solution:
from `ARequest.ReadTotalContent;`
to `Assert(Length(ARequest.RawContent) = ARequest.ContentLength);`

<hr>
`[dcc32 Error] MVCFramework.RQL.Parser.pas(619): E2003 Undeclared identifier: 'ToInt64'`

solution: 
from `lRQLLimit.Start := lStart.ToInt64;  `
to  `lRQLLimit.Start := StrToInt64Def(lStart, 0);`

<hr>
`[dcc32 Error] MVCFramework.RQL.Parser.pas(622): E2003 Undeclared identifier: 'ToInt64'`

solution
from `lRQLLimit.Count := Min(lCount.ToInt64, fMaxRecordCount);`
to `lRQLLimit.Count := Min(StrToInt64Def(lCount, 0), fMaxRecordCount);`

<hr>
`[dcc32 Error] MVCFramework.RQL.Parser.pas(626): E2003 Undeclared identifier: 'ToInt64'`

solution
from `lRQLLimit.Count := lCount.ToInt64;`
to `lRQLLimit.Count := StrToInt64Def(lCount, 0);`

<hr>
`[dcc32 Fatal Error] MVCFramework.JSONRPC.Client.pas(31): F1026 File not found: 'System.Net.HttpClient.dcu'`

no solution on XE7 for now

**Comment by danieleteti** [comment]
All fixed but the last one and the first one.
About the first one, do you have ReqMulti on your disk? In some version EMBT forgot to include that fundamental unit.

About the last one (System.Net.HttpClient.dcu) the only solution should be to reimplment the HTTP client using INDY, or remove `MVCFramework.JSONRPC.Client.pas` from the package and lose that functionality.

P:S: Please, create different issues for different anomalies.
