### ISSUE TITLE
delphi XE7 Install error - TMVCActiveRecord - COMPATIBILITY MANTAINER

### ISSUE THREAD

**Issue by DanieleBarbato** [danieleteti/delphimvcframework#201]
On Delphi XE7 there are many error like:
`[dcc32 Error] MVCFramework.ActiveRecord.pas(218): E2086 Type 'TMVCActiveRecord' is not yet completely defined`

for now I continue the tests eliminating ActiveRecord from the package

**Comment by DelphiMan68** [comment]
![Untitled](https://user-images.githubusercontent.com/10184622/56064025-23416580-5d86-11e9-82cd-bdd3a731b947.png)

**Comment by danieleteti** [comment]
https://github.com/danieleteti/delphimvcframework/commit/cc64a564a80d67927ae7dd871fb94f30635e6ee3
