### ISSUE TITLE
delphi XE10.2 Install error with EurekaLog - DMVC - COMPATIBILITY MANTAINER

### ISSUE THREAD

**Issue by DanieleBarbato** [danieleteti/delphimvcframework#202]
With Delphi XE10.2 and EurekaLog 7.7.8.21 RC 21 there is an issue during installation of Dmvc Desing time package:

Cannot load package 'dmvcframeworkRT102.'  It contains unit 'Web.Win.IsapiHTTP', which is also contained in package 'EurekaLogCore250'.

I think that the error is in EurekaLog, now I send him a message.

**Comment by DanieleBarbato** [comment]
after investigation with EurekaLog team,
there is a workaround for now:
[https://support.eurekalog.com/index.php?/Knowledgebase/Article/View/78/11/7x-eurekalogcore-contains-implicit-units-webwinisapihttp-or-it-contains-unit-webwinisapihttp-which-is-also-contained-in-package-eurekalogcore](url)

**Comment by danieleteti** [comment]
OK, good

**Comment by DanieleBarbato** [comment]
problem solved in EurakaLog 7.7.8.24
