### ISSUE TITLE
Slow dataset serialization using TMVCJsonDataObjectsSerializer.DataSetToJsonArray

### ISSUE THREAD

**Issue by dsonda** [danieleteti/delphimvcframework#205]
TMVCJsonDataObjectsSerializer.DataSetToJsonArray is very slow do serialize a dataset containned in a class (DataModule or Form) with high number os class members.

The TMVCAbstractSerializer.GetNameAs and TMVCAbstractSerializer.IsIgnoredComponent are very slow with big classes (high number of fields) to read attributes using RTTI.

Sample attached.
[dmvc_slow_serialization.zip](https://github.com/danieleteti/delphimvcframework/files/3025573/dmvc_slow_serialization.zip)

**Comment by pedrooliveira01** [comment]
Hello,
I Change MVCFramework.Serializer.JsonDataObjects to read one time attributes,
Test for me, please.


[MVCFramework.Serializer.JsonDataObjects.zip](https://github.com/danieleteti/delphimvcframework/files/3038998/MVCFramework.Serializer.JsonDataObjects.zip)

**Comment by dsonda** [comment]
Before, it took about 25 seconds to serialize in my sample.
After changes, it took 0,215 seconds.
Great job!
Could you merge this change in master?

**Comment by danieleteti** [comment]
Good job. Let me do some tests using the 108 unit tests, and then the patch will go in the repo

**Comment by danieleteti** [comment]
Unittests OK. I did just some small changes. @pedrooliveira01 your changes will be merged in the repo. Thank you for your contribution.
