### ISSUE TITLE
letsencrypt support?

### ISSUE THREAD

**Issue by landrix** [danieleteti/delphimvcframework#209]
i'm new at delphimvcframework

is letsencrypt support possible with this component ?

https://github.com/tothpaul/DelphiACME

**Comment by danieleteti** [comment]
Yes, but it's not open source.

**Comment by landrix** [comment]
thanks
not yet

> If I sell 100 licences (5.000€), the component will be released under GPL :)

**Comment by danieleteti** [comment]
Still not open source. Let's close the issue for now.
