### ISSUE TITLE
Escape single quotes in the URL

### ISSUE THREAD

**Issue by cvpereira** [danieleteti/delphimvcframework#210]
Hi guys I'm with a little doubt. I'm try send as parameter a filter to sql clause, something like

NomeMunicipio LIKE 'Para%'

The submitted URL

GET:/municipio/nextpacketwhere/NomeMunicipio%20LIKE%20'Para%25'/None/50/0

But ocurrs an exception

[EMVCException] Not Found (Custom message: "") [dmvcframework]

Even doing the encode of the single quotes to %27

GET:/municipio/nextpacketwhere/NomeMunicipio%20LIKE%20%27Para%25%27/None/50/0

but did not work,

**Comment by danieleteti** [comment]
Use querystring parameters for this kind of stuff, do not user mapped parameters. Also, did you checked the RQL engine? It is for this kind of stuff and is very powerful.

**Comment by andrebbrito** [comment]
Where can I find RQL´s Documentation?  How I can use in MVCFramework? Do you have a simple sampe with Server and Client?
