### ISSUE TITLE
Pas2JS integration for Scripting / ASP.NET Razor pages (style) - Feature request

### ISSUE THREAD

**Issue by CastleSoft** [danieleteti/delphimvcframework#214]
http://wiki.freepascal.org/pas2js

Razor style scripting using pascal would be a nice addition.

@page

<h1>Hello, world!</h1>
<h2>The time on the server is @DateTime.Now</h2>

The ability pass a model the page, interop with javascript, dom, etc..

**Comment by danieleteti** [comment]
How Razor is related to `pas2js`? Did I miss something?

**Comment by CastleSoft** [comment]
Sorry.. I was thinking along the lines of what Blazor/Razor is currently doing.

HTML markup with @ (tags) allowing C# (or in this case Delphi/Pascal) code to be generated serverside.

The Pas2JS would be used to translate the @ pascal code to javascript serverside, removing the requirement for clientside javascript coding (or greatly reducing it..)

ie.  mypage.phtml     (ie. Pascal HTML ?? like the .cshtml ???)

@page
@model RazorPagesMovie.Pages.Movies.IndexModel

@{
    ViewData["Title"] := 'Index';
}

<ul>
@foreach (var item in Model.Movie) {
      <li>
       @Html.DisplayFor(modelItem => item.Title)
     </li>
}
</ul>

**Comment by 1Dragon** [comment]
good morning Daniele,

I don’t have the knowledge to contribute to this feature but I also
share the interest in implementing it, especially with RAZOR,

Thank you very much.


CastleSoft <notifications@github.com> escreveu no dia terça, 14/04/2020
à(s) 11:22:

**Comment by fastbike** [comment]
Not really related to the DMVC framework but better IDE integration of the Pas2JS would help.

**Comment by danieleteti** [comment]
OK, now the request is more clear. More to come.

**Comment by danieleteti** [comment]
Update

SSV (ServerSideViews) allows to use any language you want. Currently mustache and TemplatePro are supported. Both allows to do "something like" RAZOR pages.
