### ISSUE TITLE
error delphi 10.1 in install

### ISSUE THREAD

**Issue by punix0210** [danieleteti/delphimvcframework#216]
class function GetByPK<T: TMVCActiveRecord, constructor>(const aValue: int64): T; overload;

Checking project dependencies...
Compiling dmvcframeworkRT.dproj (Debug, Win32)
dcc32 command line for "dmvcframeworkRT.dpk"
  c:\program files (x86)\embarcadero\studio\18.0\bin\dcc32.exe -$O- -$W+ --no-config -M -Q -TX.bpl -AGenerics.Collections=System.Generics.Collections;
  Generics.Defaults=System.Generics.Defaults;WinTypes=Winapi.Windows;WinProcs=Winapi.Windows;DbiTypes=BDE;DbiProcs=BDE;DbiErrs=BDE -DDEBUG 
  -E.\Win32\Debug -I"c:\program files (x86)\embarcadero\studio\18.0\lib\Win32\debug";"c:\program files (x86)\embarcadero\studio\18.0\lib\Win32\release";
  C:\Users\PAULO\Documents\Embarcadero\Studio\18.0\Imports;"c:\program files (x86)\embarcadero\studio\18.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\18.0\Dcp;"c:\program files (x86)\embarcadero\studio\18.0\include";"C:\Program Files 
  (x86)\FastReports\LibD24";"C:\Program Files (x86)\Embarcadero\Componentes\DevExpress 15.2.2\Library\RAD Studio 10.1" 
  -LEC:\Users\Public\Documents\Embarcadero\Studio\18.0\Bpl -LNC:\Users\Public\Documents\Embarcadero\Studio\18.0\Dcp -NU.\Win32\Debug -NSWinapi;
  System.Win;Data.Win;Datasnap.Win;Web.Win;Soap.Win;Xml.Win;Bde;System;Xml;Data;Datasnap;Web;Soap; -O"c:\program files 
  (x86)\embarcadero\studio\18.0\lib\Win32\release";C:\Users\PAULO\Documents\Embarcadero\Studio\18.0\Imports;"c:\program files 
  (x86)\embarcadero\studio\18.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\18.0\Dcp;"c:\program files (x86)\embarcadero\studio\18.0\include";
  "C:\Program Files (x86)\FastReports\LibD24";"C:\Program Files (x86)\Embarcadero\Componentes\DevExpress 15.2.2\Library\RAD Studio 10.1" -R"c:\program 
  files (x86)\embarcadero\studio\18.0\lib\Win32\release";C:\Users\PAULO\Documents\Embarcadero\Studio\18.0\Imports;"c:\program files 
  (x86)\embarcadero\studio\18.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\18.0\Dcp;"c:\program files (x86)\embarcadero\studio\18.0\include";
  "C:\Program Files (x86)\FastReports\LibD24";"C:\Program Files (x86)\Embarcadero\Componentes\DevExpress 15.2.2\Library\RAD Studio 10.1" -U"c:\program 
  files (x86)\embarcadero\studio\18.0\lib\Win32\debug";"c:\program files (x86)\embarcadero\studio\18.0\lib\Win32\release";
  C:\Users\PAULO\Documents\Embarcadero\Studio\18.0\Imports;"c:\program files (x86)\embarcadero\studio\18.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\18.0\Dcp;"c:\program files (x86)\embarcadero\studio\18.0\include";"C:\Program Files 
  (x86)\FastReports\LibD24";"C:\Program Files (x86)\Embarcadero\Componentes\DevExpress 15.2.2\Library\RAD Studio 10.1" -V -VN -VR 
  --description:"DMVCFramework 3.x" -GD -JL -NBC:\Users\Public\Documents\Embarcadero\Studio\18.0\Dcp 
  -NHC:\Users\Public\Documents\Embarcadero\Studio\18.0\hpp\Win32 -NOC:\Users\Public\Documents\Embarcadero\Studio\18.0\Dcp   dmvcframeworkRT.dpk   
[dcc32 Error] MVCFramework.ActiveRecord.pas(223): E2086 Type 'TMVCActiveRecord' is not yet completely defined
[dcc32 Error] MVCFramework.ActiveRecord.pas(226): E2086 Type 'TMVCActiveRecord' is not yet completely defined
[dcc32 Error] MVCFramework.ActiveRecord.pas(227): E2511 Type parameter 'T' must be a class type
[dcc32 Error] MVCFramework.ActiveRecord.pas(235): E2086 Type 'TMVCActiveRecord' is not yet completely defined
[dcc32 Error] MVCFramework.ActiveRecord.pas(236): E2511 Type parameter 'T' must be a class type
[dcc32 Error] MVCFramework.ActiveRecord.pas(238): E2086 Type 'TMVCActiveRecord' is not yet completely defined
[dcc32 Error] MVCFramework.ActiveRecord.pas(239): E2511 Type parameter 'T' must be a class type
[dcc32 Error] MVCFramework.ActiveRecord.pas(240): E2086 Type 'TMVCActiveRecord' is not yet completely defined
[dcc32 Error] MVCFramework.ActiveRecord.pas(242): E2086 Type 'TMVCActiveRecord' is not yet completely defined
[dcc32 Error] MVCFramework.ActiveRecord.pas(248): E2086 Type 'TMVCActiveRecord' is not yet completely defined
[dcc32 Error] MVCFramework.ActiveRecord.pas(248): E2511 Type parameter 'T' must be a class type
[dcc32 Error] MVCFramework.ActiveRecord.pas(252): E2086 Type 'TMVCActiveRecord' is not yet completely defined
[dcc32 Error] MVCFramework.ActiveRecord.pas(253): E2086 Type 'TMVCActiveRecord' is not yet completely defined
[dcc32 Fatal Error] MVCFramework.ActiveRecord.pas(390): F2063 Could not compile used unit 'MVCFramework.DataSet.Utils.pas'
Failed
Elapsed time: 00:00:00.5

**Comment by danieleteti** [comment]
Check #220
