### ISSUE TITLE
SerializeDataSet returns nil array when Dataset is empty

### ISSUE THREAD

**Issue by fastbike** [danieleteti/delphimvcframework#219]
The method TMVCJsonDataObjectsSerializer.SerializeDataSet returns nil instead of an empty json array when the dataset is empty.  
This subsequently  causes a problem when using DMustache to render  a view that uses the dataset as the method TMVCMustacheViewEngine.PrepareModels cannot type the non existent dataset as an array.

**Comment by danieleteti** [comment]
Which version are you using?

**Comment by fastbike** [comment]
Beryllium.

The issue is on lines 1085
 if (not Assigned(ADataSet)) or (ADataSet.IsEmpty) then
    Exit;

**Comment by danieleteti** [comment]
Fixed in the last commit (still not released as official RC) using the following logic:

```delphi
  if (not Assigned(ADataSet)) then
    Exit('null');
  if ADataSet.IsEmpty then
    Exit('[]'); // https://github.com/danieleteti/delphimvcframework/issues/219

```

**Comment by fastbike** [comment]
Nice, thanks for the update.
