### ISSUE TITLE
Delphi Berlin TMVCActiveRecord install error - 3.1.1-Berílio-Rc5

### ISSUE THREAD

**Issue by RodrigoTartaro** [danieleteti/delphimvcframework#220]
Error installing packages\d101\dmvcframework_group.groupproj

 -NBC:\Users\Public\Documents\Embarcadero\Studio\18.0\Dcp -NHC:\Users\Public\Documents\Embarcadero\Studio\18.0\hpp\Win32 
  -NOC:\Users\Public\Documents\Embarcadero\Studio\18.0\Dcp   dmvcframeworkRT.dpk   
[dcc32 Error] MVCFramework.ActiveRecord.pas(223): E2086 Type 'TMVCActiveRecord' is not yet completely defined
[dcc32 Error] MVCFramework.ActiveRecord.pas(226): E2086 Type 'TMVCActiveRecord' is not yet completely defined
[dcc32 Error] MVCFramework.ActiveRecord.pas(227): E2511 Type parameter 'T' must be a class type
[dcc32 Error] MVCFramework.ActiveRecord.pas(235): E2086 Type 'TMVCActiveRecord' is not yet completely defined
[dcc32 Error] MVCFramework.ActiveRecord.pas(236): E2511 Type parameter 'T' must be a class type
[dcc32 Error] MVCFramework.ActiveRecord.pas(238): E2086 Type 'TMVCActiveRecord' is not yet completely defined
[dcc32 Error] MVCFramework.ActiveRecord.pas(239): E2511 Type parameter 'T' must be a class type
[dcc32 Error] MVCFramework.ActiveRecord.pas(240): E2086 Type 'TMVCActiveRecord' is not yet completely defined
[dcc32 Error] MVCFramework.ActiveRecord.pas(242): E2086 Type 'TMVCActiveRecord' is not yet completely defined
[dcc32 Error] MVCFramework.ActiveRecord.pas(248): E2086 Type 'TMVCActiveRecord' is not yet completely defined
[dcc32 Error] MVCFramework.ActiveRecord.pas(248): E2511 Type parameter 'T' must be a class type
[dcc32 Error] MVCFramework.ActiveRecord.pas(252): E2086 Type 'TMVCActiveRecord' is not yet completely defined
[dcc32 Error] MVCFramework.ActiveRecord.pas(253): E2086 Type 'TMVCActiveRecord' is not yet completely defined
[dcc32 Fatal Error] MVCFramework.ActiveRecord.pas(389): F2063 Could not compile used unit 'MVCFramework.DataSet.Utils.pas'
Failed

**Comment by danieleteti** [comment]
This is an well known bug of the compiler in Berlin and Seattle. I don't have anymore such versions. If you or someone else can workaround the problem, would be great. The solution is to create a `class helper` for the `TMVCActiveRecord` class.

**Comment by danieleteti** [comment]
https://github.com/danieleteti/delphimvcframework/commit/cc64a564a80d67927ae7dd871fb94f30635e6ee3
