### ISSUE TITLE
EMVCException not found

### ISSUE THREAD

**Issue by shariful2011** [danieleteti/delphimvcframework#223]
I am using latest and using IDE plugin after creating a new project after running it got 

message | "[EMVCException] Not Found" in the browser.

how to resolve it?

**Comment by danieleteti** [comment]
What url did you requested?

**Comment by shariful2011** [comment]
Sorry, it was my mistake I only put http://localhost:8080

**Comment by danieleteti** [comment]
Ok

**Comment by thrutch** [comment]
@shariful2011   so what _should_ you have put ?
