### ISSUE TITLE
The url of fileupload demo

### ISSUE THREAD

**Issue by shariful2011** [danieleteti/delphimvcframework#224]
I am trying to use fileupload demo exe for a sample basis on a mobile app. I tried with the URL http://localhost:3000 from my code but I am getting an exception. What extra param do I need to use? In the browser, I am able to upload but no file is uploaded.

**Comment by danieleteti** [comment]
Did you solve the problem? On mobile you cannot use localhost. You need to use the IP of the server where DMVCFramework service is running.

**Comment by shariful2011** [comment]
No, I used the IP Address of the server where DMVC application is running.

**Comment by danieleteti** [comment]
Did you solv the problem? The file upload is very standard.

**Comment by shariful2011** [comment]
It does not upload file.

**Comment by danieleteti** [comment]
If works using the browser, it is correct. IMHO you need to double check your client code.

**Comment by joaoduarte19** [comment]
I recently created endpoints for uploading files to my API. I did it based on the fileupload sample. I had no problem, everything worked as expected.

**Comment by danieleteti** [comment]
@shariful2011 any news?
