### ISSUE TITLE
Standardization with a coding style guide

### ISSUE THREAD

**Issue by ezequieljuliano** [danieleteti/delphimvcframework#23]
Hello Daniele.

I believe it would be good we ride a programming style guide, defining variable names, parameters, methods, classes, namespaces units etc. ..

So all who contribute will be following the same form of programming, leaving more organized the project.

Do not need much documentation, the basics is necessary.

I can help in the assembly and refactoring the code later.

**Comment by danieleteti** [comment]
I agree.
We can define a coding standard and provide a formatting model to use by the Delphi formatter.
It will be simple, but it is necessary.
ASAP I'll define the standard.

**Comment by ezequieljuliano** [comment]
I asked this because I'm trying to refactor the RESTClient DMVC.

I had created a project part to deal with some issues that I need before having access to the source of the project.

I plan to add the features available in this https://github.com/ezequieljuliano/REST4Delphi/blob/master/src/REST4D.Client.pas

I will cover tests with all the old and new features and maintain the current compatibility.

**Comment by danieleteti** [comment]
Merged
