### ISSUE TITLE
AuthHandler: Returning a detailed error message in OnAuthentication() by throwing an exception

### ISSUE THREAD

**Issue by raketenwurm69** [danieleteti/delphimvcframework#230]
When using an AuthHandler, there is currently no way to return a detailed error message to the client, describing what went wrong with the login.

I helped myself by adding an exception handler to TMVCJWTAuthenticationMiddleware.OnBeforeRouting like this
```
...
try
  FAuthenticationHandler.OnAuthentication(   
  UserName, Password, RolesList, IsValid, 
  SessionData);
except
  on e:EMVCException do
  begin
    RenderError(e.ApplicationErrorCode, e.Message, AContext);
    AHandled := True;
    exit;
  end;
end;
...
```
In the CustomAuthHandler I throw an EMVCException with the detailed error message.
raise EMVCException.Create('MyError', 'MyDetailedError', ERROR_WRONG_PASSWORD);

Is there any possibility to add this to the MVC-Framework-Codebase?

**Comment by danieleteti** [comment]
What about a change like this in the try...except block already there? Does it work for you?

```delphi
        except
          on Err: EMVCException do //this handler has been added for specific EMVCException exceptions
          begin
            RenderError(Err.HttpErrorCode, Err.Message, AContext, Err.ClassName);
            AHandled := True;
          end;
          on e: Exception do
          begin
            RenderError(HTTP_STATUS.Forbidden, e.Message, AContext);
            AHandled := True;
          end;
        end;
```

**Comment by raketenwurm69** [comment]
Yes, that would be fine. But instead of the HttpErrorCode I would need to render the ApplicationErrorCode in the output, so I could exactly tell what was causing the error.

```
        except
          on Err: EMVCException do //this handler has been added for specific EMVCException exceptions
          begin
            RenderError(Err.ApplicationErrorCode, Err.Message, AContext, Err.ClassName);
            AHandled := True;
          end;
          on e: Exception do
          begin
            RenderError(HTTP_STATUS.Forbidden, e.Message, AContext);
            AHandled := True;
          end;
        end;
```

**Comment by danieleteti** [comment]
Yes, but the  first parameter of `RenderError` procedure is used to set the response HTTPStatusCode, so you cannot use an application defined code for that - you must stick with the HTTP codes. I've just added one more parameter (default : 0)  for application related error code.


```delphi
        except
          on Err: EMVCException do
          begin
            RenderError(Err.HttpErrorCode, Err.Message, AContext, Err.ClassName, Err.ApplicationErrorCode);
            AHandled := True;
          end;
          on e: Exception do
          begin
            RenderError(HTTP_STATUS.Forbidden, e.Message, AContext);
            AHandled := True;
          end;
        end;
```

The response, in case of `ApplicationErrorCode <> 0`, will contain a property named `errornumber`.

Does it work for you?

**Comment by raketenwurm69** [comment]
Excellent! This is going to work for me.

**Comment by danieleteti** [comment]
Great! In 3.1.1-beryllium-RC6 will be included this change.

**Comment by danieleteti** [comment]
https://github.com/danieleteti/delphimvcframework/commit/d77c77758fdfc190220103ca24bbbc8e9d03aa21
