### ISSUE TITLE
Support nullable types in ActiveRecord

### ISSUE THREAD

**Issue by DelphiMan68** [danieleteti/delphimvcframework#231]
I have a model with some properties Nullable types, but when I use It with active records an error happens

ERROR : Project ActiveRecord.exe raised exception class EInvalidCast with message 'Invalid class typecast'.

How can i resolve this problem?

Sample project + firebird database for test:
[dmvc_problem[ActiveRecords-NullableTypes].zip](https://github.com/danieleteti/delphimvcframework/files/3317657/dmvc_problem.ActiveRecords-NullableTypes.zip)

![typecast error](https://user-images.githubusercontent.com/10184622/59973888-71f75100-95ba-11e9-8803-e9f490d829c0.png)

**Comment by danieleteti** [comment]
A contributor is working on this #239
