### ISSUE TITLE
Error: Request size exceeded the max allowed size [5120 KiB]

### ISSUE THREAD

**Issue by maiconsi** [danieleteti/delphimvcframework#238]
Hi Daniele Teti, I had a problem uploading files larger than 5MB.
I added in the Webmodule's Create line: "FMVCEngine.Config [TMVCConfigKey.MaxRequestSize]: = IntToStr (TMVCConstants.OneMiB * 10);"
to allow files up to 10MB but the DMVC did not respect this new limit, I was able to find a solution in the "ExecuteAction", I added a line to load the MaxRequestsize that is in the Config.
"FConfigCache_MaxRequestSize: = StrToInt64Def (Config [TMVCConfigKey.MaxRequestSize],
     TMVCConstants.DEFAULT_MAX_REQUEST_SIZE); "
![Screenshot_13](https://user-images.githubusercontent.com/46498249/61052750-65e4ff00-a3c2-11e9-9dd8-44df9675ae54.png)
I do not know if this is the best way to solve this but it worked.

**Comment by danieleteti** [comment]
Thank you, we'll look into this ASAP for the next RC6

**Comment by danieleteti** [comment]
Where did you put that config value? The following code works.

```delphi
  MVCEngine := TMVCEngine.Create(self,
    procedure(Config: TMVCConfig)
    begin
      // other config here
      Config[TMVCConfigKey.SessionTimeout] := '0'; // setting cookie
      Config[TMVCConfigKey.PathPrefix] := '';
      Config[TMVCConfigKey.MaxRequestSize] := '10000000'; //this is checked in the ExecuteAction method
    end, nil);

```

**Comment by maiconsi** [comment]
Passing this setting inside the anonymous method worked !! 
Thank you ...
