### ISSUE TITLE
IETF - RFC 6750

### ISSUE THREAD

**Issue by viniciussanchez** [danieleteti/delphimvcframework#244]
The constructor of the TMVCJWTAuthenticationMiddleware class (unit MVCFramework.Middleware.JWT.pas) is outside the IETF - RFC 6750 national convention.

The correct thing is not to pass the parameters in the header. You must use Authorization. Nor should you allow the name of the header authorization to be changed.

**This will break the compatibility. But it will leave the middleware at the IETF standard.**

Can I implement the pattern?

**Comment by danieleteti** [comment]
Yes. We could add a new constructor and mark the previous one as `deprecated`. I think it is a good apporach. In the deprecated message, we'll put something like "This constructor will be removed soon, please use the new one".

I'll wait your PR. Thank you

**Comment by viniciussanchez** [comment]
Ok, thanks

**Comment by viniciussanchez** [comment]
@danieleteti I can't have two builders like this ...
The right thing is that I change the name of one, because the initial parameters are the same. Or remove the wrong builder once and for all ...

```pascal
    constructor Create(
      AAuthenticationHandler: IMVCAuthenticationHandler;
      AConfigClaims: TJWTClaimsSetup;
      ASecret: string = 'D3lph1MVCFram3w0rk';
      ALoginURLSegment: string = '/login';
      AClaimsToCheck: TJWTCheckableClaims = [];
      ALeewaySeconds: Cardinal = 300;
      AAuthorizationHeaderName: string = TMVCJWTDefaults.AUTHORIZATION_HEADER;
      AUserNameHeaderName: string = TMVCJWTDefaults.USERNAME_HEADER;
      APasswordHeaderName: string = TMVCJWTDefaults.PASSWORD_HEADER); overload; virtual; deprecated 'This constructor will be removed soon, please use the new one';
    constructor Create(
      AAuthenticationHandler: IMVCAuthenticationHandler;
      AConfigClaims: TJWTClaimsSetup;
      ASecret: string = 'D3lph1MVCFram3w0rk';
      ALoginURLSegment: string = '/login';
      AClaimsToCheck: TJWTCheckableClaims = [];
      ALeewaySeconds: Cardinal = 300); overload; virtual;
```

![image](https://user-images.githubusercontent.com/16382981/61892137-8abc9480-aee1-11e9-8aa1-159342b28142.png)

**Comment by viniciussanchez** [comment]
![image](https://user-images.githubusercontent.com/16382981/61896043-78932400-aeea-11e9-8149-7398417d2e48.png)

**Comment by joaoduarte19** [comment]
The default headers "jwtusername" and "jwtpassword" should be changed to "username" and "password"

**Comment by viniciussanchez** [comment]
@joaoduarte19 According to IETF - RFC 6750 they must not be used!

**Comment by viniciussanchez** [comment]
Use Authorization Header
