### ISSUE TITLE
Middleware problem capturing static file requests.

### ISSUE THREAD

**Issue by rafaelgalle** [danieleteti/delphimvcframework#249]
Hello

I use middleware so that before each request it checks and redirects to '/login' if the request does not meet my requirements.

Example

procedure OnBeforeRouting...
  if (...) then
  begin
    Context.Response.Location := '/login';
    Context.Response.StatusCode := 302;
    Handled := True;
  end;

  
And if the request is a static file ex: GET "css/index.css" this request should not go through middleware, so says the middleware documentation available at
https://danieleteti.gitbooks.io/delphimvcframework/chapter_middlewares.html

And that worked great, until I upgraded to the latest release available.
I did the tests, with the same project changing only the dmvc version and this works on version 3.1.1RC2, from that it doesn't work and even a request to a static file "css/index.css" is captured by middleware.
I looked for if there was any new configuration needed for the operation but found nothing, so I believe it could be some error.

In version 3.1.1RC3 where this crashed, there was the new TMVCAnalyticsMiddleware, maybe it has something to do with it.

Can you help me?

I await return and thanks for your attention.

-------------------------

Tested Environments
Delphi 10.3 Update 1 Professional
(ISAPI DLL in IIS 10 and StandAlone)

**Comment by juliosenha** [comment]
Hi! 
take a look at PR # 243.

**Comment by viniciussanchez** [comment]
Hi, I modified the OnBeforeRouting procedure to meet an IETF 6750 defined standard. #243 180dc2e98894f466872cd8fc8493c918018b7efc
Previously he had to use the POST method to get a token. That was wrong. The change may have interfered with you.
But we can't go back as before! If this is really the problem, we need to see a way to adjust...

![image](https://user-images.githubusercontent.com/16382981/61900734-99f90d80-aef4-11e9-9db2-79e778a433fe.png)

**Comment by rafaelgalle** [comment]
Sorry I had not seen the PR243

I really need static files to escape the validation done on my Middleware, but I understand that modifications are required to meet the standard.

I can add a check to identify if the request is from a static file or some controller call action with FileExists

procedure TMyMiddleware.OnBeforeRouting ... 
FileExists( FDocumentRoot + Context.Request.PathInfo )

If it exists then it is static, knowing that I can get on with the work, I just need to add one more check without affecting my process.

Just a note
"First it will check for static files. If the requested url is a static file it will be rendered and the execution is finished. If the url is not a static file the OnBeforeRouting procedure of all added Middleware objects will be fired. "
https://danieleteti.gitbooks.io/delphimvcframework/chapter_middlewares.html

This link says that the OnBeforeRouting event is only called if the url is not a static file, when the final version is closed and published you will need to update this link by removing this information, as now static files also call the OnBeforeRouting event.

Thank you very much for your attention and sorry for the inconvenience.

> Oi, eu modifiquei o procedimento OnBeforeRouting para atender a um padrão definido pelo IETF 6750. [# 243 ](https://github.com/danieleteti/delphimvcframework/pull/243) [180dc2e](https://github.com/danieleteti/delphimvcframework/commit/180dc2e98894f466872cd8fc8493c918018b7efc)
> Anteriormente, ele precisava usar o método POST para obter um token. Isso estava errado. A mudança pode ter interferido em você. 
> Mas não podemos voltar como antes! Se este é realmente o problema, precisamos ver uma maneira de ajustar ...
> 
> ![imagem](https://user-images.githubusercontent.com/16382981/61900734-99f90d80-aef4-11e9-9db2-79e778a433fe.png)

**Comment by viniciussanchez** [comment]
It's all right...
One solution would also be for you to create your authentication middleware, inheriting from the class we have today.
Then you can make your particularities in it ...

**Comment by marcosnielsen** [comment]
Hello,

I agree that authentication is not being done correctly according to the standards cited in rfc6750, but authentication correction should not interfere with how DMVC middleware handles requests, since we are not talking about authentication middlware but normal middlware (IMVCMiddleware ), this change is breaking the product documentation: https://danieleteti.gitbooks.io/delphimvcframework/chapter_middlewares.html

I have always been using the development version of the master version and looking at this problem we had to make an IMVCMiddleware interceptor to validate if the file is static.

> procedure TMVCMiddlewareIntercepter.OnBeforeRouting(Context: TWebContext; var Handled: Boolean);
begin
  //if is statits file
  if not FileExists( FDocumentRoot + Context.Request.PathInfo ) then
  begin
    //do anything
  end;
end;
> 

and internally this has already been resolved, but this change needs to be reviewed.

**Comment by danieleteti** [comment]
yes, the documentation is outdated. In dmvcframework handbook will be explained the reason of the change. However the main reason is that while before at each request, the router first check if the URI refers to a static file and then (if not) will start all the routing phase to find the controller/action pair, now first try to find the controller/acrion pair, and then, if not found, before the "404 Not Found" checks for static file. Mainly has been done for performance reasons, as second reason (more serious) is that before you could overwrite a controller/action using a "malicius named" file, while not is not possible.

**Comment by marcosnielsen** [comment]
We are excited and curious to see your new book! dmvcframework handbook

**Comment by danieleteti** [comment]
[DMVCFramework Handbook](https://leanpub.com/delphimvcframework) should be ready in a couple of months, at least the first version.
