### ISSUE TITLE
Needed unit not found

### ISSUE THREAD

**Issue by KrIvanov** [danieleteti/delphimvcframework#25]
There is in MVCFramework.pas used unit 'StompTypes'. Now it is gone. At least in my last update (I'm not sure how long I had it) there was a Folder 'delphistompclient'. Now this is no more there too, but MVCFramework.pas need it...

I just wonder how tests passt!? What must I make to compile MVCFramework?

**Comment by danieleteti** [comment]
Hi,
Update git submodules and you will have all the needed units.

DT
Il 20 gen 2016 3:21 PM, "KrIvanov" <notifications@github.com> ha scritto:

**Comment by KrIvanov** [comment]
Oh, Yes, I see! I make SVN update and of course, didn't get submodules. Thank you!

**Comment by danieleteti** [comment]
You are welcome.

DT

2016-01-20 17:38 GMT+01:00 KrIvanov <notifications@github.com>:

> Oh, Yes, I see! I make SVN update and of course, didn't get submodules.
> Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danieleteti/delphimvcframework/issues/25#issuecomment-173265090>
> .
>



-- 
*Daniele Teti*
CEO
bit Time Professionals
web: www.bittimeprofessionals.it <http://www.bittime.it>
blog: www.danieleteti.it
books: www.danieleteti.it/delphi-cookbook
mobile: +39 3496626822
office: +39 06 83393029

**Comment by danieleteti** [comment]
closed
