### ISSUE TITLE
Use System.JSON in MVCFramework.pas

### ISSUE THREAD

**Issue by viniciussanchez** [danieleteti/delphimvcframework#252]
It would be very useful if the BodyAs <T> function returned a TJSONObject. For this I would need to add the use of the System.JSON unit. The code would look like this:

```pascal
function TMVCWebRequest.BodyAs<T>: T;
var
  Obj: TObject;
  lSerializer: IMVCSerializer;
begin
  Result := nil;
  if T.ClassName = TJSONObject.ClassName then
  begin
    Result := (TJSONObject.ParseJSONValue(TEncoding.ASCII.GetBytes(Body), 0) as TJSONObject) as T;
    Exit;
  end;
  if FSerializers.TryGetValue(ContentMediaType, lSerializer) then
  begin
    Obj := TMVCSerializerHelper.CreateObject(TClass(T).QualifiedClassName);
    try
      lSerializer.DeserializeObject(Body, Obj);
      Result := Obj as T;
    except
      on E: Exception do
      begin
        FreeAndNil(Obj);
        raise;
      end;
    end;
  end
  else
    raise EMVCDeserializationException.CreateFmt('Body ContentType "%s" not supported', [ContentType]);
end;
```

I can't use the TJDOJsonObject class because my controllers don't expect this type.

If this implementation is not possible, I will have to cast all my controllers.

Can I make use of System.JSON?

**Comment by marcosnielsen** [comment]
328/5000
I believe this change would break compatibility with existing systems, this can be bad, but I think you just need to write an MVCFramework.Helper.pas class helper to the MVCFramework.pas class and reference MVCFramework.Helper.pas
on your controllers with their function.

That would be very simple.

**Comment by danieleteti** [comment]
Such kind of helpers are already there. Check MVCFramework.SystemJSONUtils.pas.

IMHO Call a function is enough in this case.
