### ISSUE TITLE
Delphi 10.2.3  Undeclared identifier: 'Clone'  , MVCFramework.Serializer.JsonDataObjects

### ISSUE THREAD

**Issue by jairgza** [danieleteti/delphimvcframework#262]
Compiling any sample or createing empty new mvc application, got this error

[dcc32 Error] MVCFramework.Serializer.JsonDataObjects.pas(1268): E2003 Undeclared identifier: 'Clone'

these are the lines:
  if AObject is TJsonBaseObject then
    Exit(TJsonBaseObject(AObject).Clone as TJDOJsonObject);

**Comment by danieleteti** [comment]
Probably you have an old jsondataobjects.pas in the path.

**Comment by jairgza** [comment]
Ups,  You are right ,  I didn't stop to check the dependencies,  my bad
regards
