### ISSUE TITLE
Can I assign a role to a method without put it in the path ?

### ISSUE THREAD

**Issue by jairgza** [danieleteti/delphimvcframework#267]
Right now I see is needed to put the role in the path, is this mandatory ?  for example, I want a path  "/sales"  but only authorizations for role1 is it posible ?,  may be something like this:

    [MVCPath('/sales')]
    [MVCProduces('text/html')]
    [MVCHTTPMethod([httpGET])]
    [MVCRoles('role1 role2 role3 roleSuper')]
    procedure GetSales;

thanks

**Comment by jairgza** [comment]
OK, again I respond to myself,  now I see the  TAuthenticationSample.OnAuthorization method where validate the AccionName parameter, so every ActionName (method name) needs be compared or maybe use some prefix in the name to identify the role.

Can I ask for a sugestion/enanchment ?  create an MVCRolesAttribute and in OnAuthorization send the ActionRoles ?  I think it's easier to validate AccionRoles vs UserRoles instead of method names, don't you think ?

thanks

**Comment by fastbike** [comment]
I created a custom attribute and  an interface/class that checks for the role. This is called in the OnAuthorisation handler.

**Comment by jairgza** [comment]
@fastbike   thanks for your sugestion,   I found a unit than do exactly what you say,  MVCFramework.Middleware.Authentication.RoleBasedAuthHandler

Im going to do something similar for jwt middleware

thanks
