### ISSUE TITLE
Compression failure IIS

### ISSUE THREAD

**Issue by viniciussanchez** [danieleteti/delphimvcframework#269]
Hello, I have a compression problem using IIS. The code chunk below works perfectly running the server as stand alone. But if running as ISAPI, it does not work and returns me an empty content with statuscode 200.

unit **MVCFramework.Middleware.Compression**

```pascal
  lContentStream.Position := 0;
  lMemStream := TMemoryStream.Create;
  try
    {TODO -oDanieleT -cGeneral : Use directly lContentStream?}
    lZStream := TZCompressionStream.Create(lMemStream, TZCompressionLevel.zcMax, MVC_COMPRESSION_ZLIB_WINDOW_BITS[lRespCompressionType]);
    try
      lZStream.CopyFrom(lContentStream, 0);
    finally
      lZStream.Free;
    end;
    lMemStream.Position := 0;

    Context.Response.Content := '';
    lContentStream.Size := 0;
    lContentStream.CopyFrom(lMemStream, 0);
{$IF Defined(SeattleOrBetter)}
    Context.Response.RawWebResponse.ContentEncoding := MVC_COMPRESSION_TYPE_AS_STRING[lRespCompressionType];
{$ELSE}
    Context.Response.RawWebResponse.ContentEncoding := AnsiString(MVC_COMPRESSION_TYPE_AS_STRING[lRespCompressionType]);
{$ENDIF}
  finally
    lMemStream.Free;
  end;
```

**Comment by danieleteti** [comment]
Delphi version? dmvcframework version?
Can you trace the middleware code in debug?

**Comment by viniciussanchez** [comment]
Delphi version: **10.3.2**
DMVC version: **branch master** (https://github.com/danieleteti/delphimvcframework.git)
Can you trace the middleware code in debug? How to debug running on IIS? Running as stand alone application I can

**Comment by viniciussanchez** [comment]
@danieleteti we haven't found the problem here yet. To view this fact, open the sample project "delphimvcframework \ samples \ ISAPI \ ISAPI" and compile.
Make a request at **http://localhost/test/test.dll/api/wines** and it will list the records.
To view the problem, add the command below and generate the dll.
`FMVC.AddMiddleware (TMVCCompressionMiddleware.Create);`
Run the same request and you will see that the data will no longer be listed. A statuscode 200 with empty content will be returned.

**Comment by viniciussanchez** [comment]
We tested the same project on Delphi 10.3.2 and Delphi 10.2.3

**Comment by viniciussanchez** [comment]
No método **"ExecuteAction"** da classe **"TMVCEngine"**, antes da linha destacada na imagem abaixo, use o **Ctrl+F7** e digite **"LContext.Response.RawWebResponse.ContentStream.Size"**. A resposta é destructed. Se faz o mesmo teste com uma aplicação autônoma, isso não ocorre, mesmo dando um Free em LContext.

![image](https://user-images.githubusercontent.com/16382981/63291431-e0465000-c299-11e9-95a6-fb36b2bb54f6.png)

**Comment by viniciussanchez** [comment]
In **"samples\outputcompression"** it says that only the line below is required to configure response compression. Is any configuration missing?

```pascal
  // To enable compression, just add this middleware as the last one
  FMVC.AddMiddleware(TMVCCompressionMiddleware.Create);
```

**Comment by danieleteti** [comment]
@viniciussanchez no, no other configurations are needed to make the compression middleware works.
However, the compression middleware is useful when you don't have to publish dmvcframework behind a full-flagged web server. In case you publish you service behind IIS (or nginx, or Apache or anything) just let the web server to do the actual compression. Just IFDEF the middleware in the ISAPI. It is intended to work as is.

**Comment by viniciussanchez** [comment]
Got it ... so when working using IIS is not advisable to use compression middleware? I will close this topic then.
