### ISSUE TITLE
JSON-RPC: Floating point parameters are not recognized when there is no decimal point

### ISSUE THREAD

**Issue by raketenwurm69** [danieleteti/delphimvcframework#270]
In v3.1.1 of DMVC. When using floating point parameters in a JSON-RPC function like
`    function TimestampSetLocation(times_nr, location: string; lat: extended; lng: extended): TXTTimestamp;
`
The function is not recognized anymore when the parameter given has no decimal point. E.g. I have to write "0.0" instead of just "0" so the JRPC-Function is found.

This worked with v3.0.0 of DMVC.

**Comment by danieleteti** [comment]
Please, use this unit (replacing the current one) and let me know.
[MVCFramework.JSONRPC.pas.zip](https://github.com/danieleteti/delphimvcframework/files/3533965/MVCFramework.JSONRPC.pas.zip)
