### ISSUE TITLE
TLoggerProFileAppender never frees writers

### ISSUE THREAD

**Issue by fastbike** [danieleteti/delphimvcframework#273]
TLoggerProFileAppender maintains a dictionary of log writers (TStreamWriter). When a log item is written the dictionary is checked to see if a log writer exists and one is created if not already in the dictionary.

In the case of unique log files being created for each request, the Dictionary gets big very fast as each request adds a writer.
Any thoughts on how to manage the lifetime of the writers ?

**Comment by danieleteti** [comment]
A writer is created for each TAG_LOG. Having a lot of TAG_LOG (one hundred?) is a bad practice. Did I Get the point?

**Comment by fastbike** [comment]
We have an application that received request tagged with a custom header, a GUID, that refers back to the gateway that has forwarded on the system.  For ease of debugging we use this tag as the log tag. In practice this means that each request generates a unique file (nice for debugging), but the number of writers balloons out.  I have created an overridden class that internally manages the writers.  Or get a better log viewer.
We can probably close this ticket unless there are better ideas.

**Comment by danieleteti** [comment]
I think that your current solution (a specific appender) is the best (without involve external systems).

**Comment by fastbike** [comment]
Thx, I'll close the ticket
