### ISSUE TITLE
New property for Context to hold Objects

### ISSUE THREAD

**Issue by fastbike** [danieleteti/delphimvcframework#274]
Context has a Data property which is a dictionary of strings. This is useful for storing text based data related to each request.

I would find it useful to be able to store objects created by my MVC application that relate to each request.  These objects are transient in nature being created when the request is received and destroyed once the request has been processed.

Ideally this storage will accept IInterface or TObject based instances.

Initial thoughts are to add a new property to TWebContext ....
````
    property Objects: TDictionary<string, IInterafce> read FObjects;
//or
    property Objects: TDictionary<string, TObject> read FObjects;
````

A real world example is a project we are working on that handles medical information in an XML format. As part of the response we send back a structured XML object. It would be useful for us to create the structured XML object  via middleware as soon as the request is received so that we can add nodes to it in other middleware before it hits the targeted  controller action.

**Comment by danieleteti** [comment]
That would be a nice addition. Do you have some tested code about this change?

**Comment by fastbike** [comment]
I think a dictionary of TObjects would be generally more useful than a dictionary of IInterfaces.

However my use case is a dictionary of interfaced objects.

I tried to use a dictionary of TObjects and casting the interfaced objects when I added them but ran into lifetime management issues.

I can provide a code sample soon.

**Comment by fastbike** [comment]
I think I have a fix for the lifetime management issue ... will pull down the latest code and see how it fits.

**Comment by fastbike** [comment]
Code changes made and  examples  provided in the attached zip file

[MVCContextObjects.zip](https://github.com/danieleteti/delphimvcframework/files/3623735/MVCContextObjects.zip)

**Comment by fastbike** [comment]
Still working my way through some more test examples ...

**Comment by danieleteti** [comment]
Thank would be nice, but the only compellig reason to add these objects is to pass some high-level info between controller and middlewares or between middlewares and middlewares. Do you have other real world case for this?

**Comment by fastbike** [comment]
We're currently using it in our FHIR (see http://hl7.org/fhir) server implementation to create any high level objects that will be required by various plug in classes that service requests.  We then add them to the Context Objects collection and add class helper so that these objects appear as read only properties (helper class has getter functions)
This means we don't have to pass around lots of objects - as long as the classes serving the request have access to the Context object they can access the high level objects.
You might call the second part (the helper class) syntactic sugar - but it makes the application code a lot easier to read, and the method signatures much smaller.

I will try to make some time to follow up with a better worked example.  Our own project is too large to upload here  and also contains application level IP that my company would not be prepared to publish.

**Comment by fastbike** [comment]
I'm finding the IInterface lifetime management too tricky to implement if I use a TDictionary<string, TObject>.  So my latest code uses a TDictionary<string, IInterface>.  
I will post up the amended code once I have synchronized it with the latest github changes.

**Comment by fastbike** [comment]
> Thank would be nice, but the only compellig reason to add these objects is to pass some high-level info between controller and middlewares or between middlewares and middlewares. Do you have other real world case for this?

My use case is to make it easier to write the logic in the  Controller and associated logic classes.  By using this new property, and a class extension on TWebContext, I can write code in a fluent style, accessing the additional objects as a pseudo property of the Context object.  Given that the Context object  is available in most places, it means my method signatures become shorter as I normally will only need to pass in Context, rather than the other application specific objects.

**Comment by danieleteti** [comment]
I understand your needs, but I think that this is not a good solution.

**Comment by fastbike** [comment]
Thanks for the update @danieleteti .  I'll take another look at my use case and refine the enhancement request :)

**Comment by fastbike** [comment]
Just to follow up on this issue, the CustomIntfObject property on the TWebContext class allowed me to achieve my goals.  I declared a custom interface that provided some methods to manipulate objects in a dictionary, and then added a class helper to TWebContext to provide access.
`  IWebContextObjectsDictionary = interface
    ['{B70454F5-DD2E-4727-9B3B-D910CEE113AC}']
    procedure Add(const Key: string; const Value: TObject); overload;
    procedure Add(const Key: string; const Value: IInterface); overload;
    function TryGetValue(const Key: string; out Value: TObject): Boolean; overload;
    function TryGetValue(const Key: string; out Value: IInterface): Boolean; overload;
    procedure Remove(const Key: string);
  end;
`
This enables either old school TObject, or interfaced objects, to be created and attached to the context. Typically there will be something created during the initial request handling, which is then render out as part of the final code. In between there is some custom business logic which is passed a pointer to the object stashed in the Context.
