### ISSUE TITLE
Feature Suggestion: integrate delphi ORM with dmvcframework

### ISSUE THREAD

**Issue by joaoduarte19** [danieleteti/delphimvcframework#279]
Hi Daniele,
Have you considered integrating your [Delphi ORM](https://github.com/danieleteti/delphi-orm) project with Delphi MVC?

In my opinion it would be very good for both projects. It would add an ORM to DMVCFramework and the community could add new features to DORM.

**Comment by danieleteti** [comment]
Yes, I considered this some time ago. However, it is not feasible IMHO. DORM and DMVCFramework are two huge projects and it takes a lot of time just to handle one of them. 
I preferred to add a thin layer for data access in DMVCFramework (TMVCActiveRecord) which is quite manageable and simpler to use than DORM. 
However DORM is still waiting for contributors and mantainers. If you want, you are welcome.

**Comment by joaoduarte19** [comment]
Soon I will start a new project and I intend to use an ORM. I am analyzing some ORM to choose the best one for my project. If I decide to use DORM, I will definitely contribute to the project.
