### ISSUE TITLE
JWT description in Swagger UI doesn't work

### ISSUE THREAD

**Issue by danieleteti** [danieleteti/delphimvcframework#281]
The JWT description in SwaggerUI doesn't allow to add parameters. 
Check `samples\swaggerdoc\SwaggerDocApi.dproj`

Can @joaoduarte19 give help about this?

**Comment by joaoduarte19** [comment]
I will check this error ASAP

**Comment by danieleteti** [comment]
Can you post a video to show how is intended to make the authentiation with JWT and a request to `POST /person`?

**Comment by joaoduarte19** [comment]
Yes, I can create a detailed video or tutorial to show how to do JWT authentication using swagger.
