### ISSUE TITLE
Alternative server components

### ISSUE THREAD

**Issue by biware-repo** [danieleteti/delphimvcframework#284]
Is it possible to use any other server components? For example for realtime applications is now better to use websockets.

Is it anough to implement interfaces in MVCFramework.Server.pas to use some commercial websocket server components eg. from esegece?

**Comment by danieleteti** [comment]
Yes, it is not so complex. A supported "default" open source version, should be even better...

**Comment by BimmerR** [comment]
If this is the same as replacing INDY - I'm all in :-)
Really looking for a ultra simple windows service that offers TLS/SSL support without the need for external dll's (OpenSSL).

**Comment by RDP1974** [comment]
Take a look to https://github.com/winddriver/Delphi-Cross-Socket/blob/master/Net/Net.MbedTls.pas
Builds of https://github.com/ARMmbed/mbedtls an excellent TLS library from ARM
So you don’t need OpenSSL libraries

Roberto Della Pasqua
www.dellapasqua.com<http://www.dellapasqua.com>

Da: Bjarne Rasmussen <notifications@github.com>
Inviato: giovedì 16 gennaio 2020 09:22
A: danieleteti/delphimvcframework <delphimvcframework@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Oggetto: Re: [danieleteti/delphimvcframework] Alternative server components (#284)


If this is the same as replacing INDY - I'm all in :-)
Really looking for a ultra simple windows service that offers TLS/SSL support without the need for external dll's (OpenSSL).

**Comment by danieleteti** [comment]
This will be available in dmvcframework-4.0.0-oxygen
