### ISSUE TITLE
make DB access more parallelized

### ISSUE THREAD

**Issue by RDP1974** [danieleteti/delphimvcframework#288]
please can you update the samples/sources to make full parallelization of firedac,
can you build a db objects pooling;
1- can use Firedac.Connection pooling to save the connection open/close I/O
http://docwiki.embarcadero.com/CodeExamples/Rio/en/FireDAC.Pooling_Sample
2- dispatch a thread/itask for the sql, each with preallocated db objects
3- eventually use a connection/transaction/query mapped into TLS slot and monitor OnThreadAttach/Detach onBeforeDispatch httpapp to create/free/check active 

You will get rid of the common bottleneck to use a single query for the whole server (now: many requests -> single db query serialized; after: many requests->many db queries in concurrency)

ps. please sorry if I'm wrong, just have done a tittle time to dmvc

**Comment by danieleteti** [comment]
Hi, TMVCActiveRecord uses the connection you provide. The pooling is not related to the MVC framework but only to the FireDAC connection. If you are on a server, you *must* provide a pooled connection, but MVCActiveRecord doesn't require it. If you are on mobile or desktop applications, you can also dont use a pooling... so TMVCActive record will leave the option to you. It just *use* the connection you provide.

Did I get your point?

**Comment by RDP1974** [comment]
ok I see, thanks for the kind info
