### ISSUE TITLE
Add section definition in the Swagger file

### ISSUE THREAD

**Issue by danieleteti** [danieleteti/delphimvcframework#289]
The swagger file use only in line definition for models.

Should be much better if it had uses the `#ref ` syntax centralizing all the models in the proper section. Moreover, the swagger-ui can show the models in the proper section.

**Comment by joaoduarte19** [comment]
Yes, this is an improvement I already thought to make. As soon as I have some free time I want to make this change in the way I add JSONSchema to swagger.

**Comment by danieleteti** [comment]
I think that we could just add to the model all the complex types (classes) we fould while inspecting each method.

**Comment by danieleteti** [comment]
@joaoduarte19 do you have any news about this?

**Comment by joaoduarte19** [comment]
I have already started working on this feature. I believe that within 3 weeks it will be finished.
