### ISSUE TITLE
Enum parameters

### ISSUE THREAD

**Issue by ads69** [danieleteti/delphimvcframework#292]
Hi,
it would be great to have enum in parameters.
The goal is to have a combobox or a listBox where the user choose a value.
Something like
-name: "gender"
          in: "query"
          type: "string"
          **enum: [ "male", "female", "other"]**
          description: "Enter user gender here."
          required: true

Best regards

Armindo

**Comment by joaoduarte19** [comment]
This is a good improvement for swagger.

**Comment by joaoduarte19** [comment]
This issue has been resolved.
