### ISSUE TITLE
[ERegularExpressionError] Error in regular expression at offset 13: unmatched parentheses

### ISSUE THREAD

**Issue by alifoz** [danieleteti/delphimvcframework#300]
Hi!

I have this route:

    [MVCPath('/cerebro)')]
    [MVCHTTPMethod([httpGET])]
    procedure GetCerebro;

procedure TMyController.GetCerebro;
var
  LCerebro : TCerebro;
begin
  LCerebro := TCerebro.Create;
  LCerebro.id := 99;
  LCerebro.codigo := '11';
  LCerebro.nome := 'teste';
  LCerebro.vencimento := now;
  LCerebro.msg1 := 'mensagem1';
  LCerebro.msg2 := 'Mensagem2';
  LCerebro.msg3 := 'Mensagem3';
  LCerebro.msg1data := now +1;
  LCerebro.msg2data := now + 2;
  LCerebro.msg3data := now +3;
  LCerebro.login := 'usuario';
  LCerebro.status := 9;

  Render(LCerebro);
end;

and i received this error... what i did wrong?

**Comment by danieleteti** [comment]
There is a parenthesis in the route. Remove it.
