### ISSUE TITLE
[EMVCException] Not Found in Postman or other but not in RestDebuger

### ISSUE THREAD

**Issue by shariful2011** [danieleteti/delphimvcframework#301]
I am using DelphiMVCFramework 3.2.0 (boron) RC2. On executing in RestDebuger I am able to get a successful response but not in Postman or Android or iOS using Flutter. You can see [RestDebugger](https://mega.nz/#!is1k2CzK!HR2y9jWWeF53dd11inEY24nKdtD7jQOFtC5YbPj2Jtg) the link I used and the parameters I added. And in Postman and others, I got following error message:
{
    "classname": "EMVCException",
    "items": [],
    "statuscode": 404,
    "reasonstring": "",
    "message": "[EMVCException] Not Found",
    "data": null
}
All uses same url http://localhost:8080/cases/newcase which is a POST method.
Postman response is 
![image](https://user-images.githubusercontent.com/634779/69434757-7477f580-0d68-11ea-9a04-a799296e314a.png)
Android Response is 
![image](https://user-images.githubusercontent.com/634779/69434835-9d988600-0d68-11ea-8c8b-0e98fc523238.png)

**Comment by spinettaro** [comment]
@shariful2011 have a look at content-type header, if you doesn't respect it you receive a 404 error.
So, be sure that the header content-type of the client request and the MVCConsumeAttribute match the same value.

**Comment by shariful2011** [comment]
I add [Headers('Accept', 'application/json')] which solved the issue, is it ok or not.

**Comment by fastbike** [comment]
See my response in the other  issue that you have created
