### ISSUE TITLE
How to use POST method for inserting data in REST Server

### ISSUE THREAD

**Issue by shariful2011** [danieleteti/delphimvcframework#302]
I am trying to make a Restful server using this framework. I can manage every call except the POST method for inserting data. Every time I am getting a 404 status code. Using RESTDebuger did a successful call but not in others like Postman, Android, iOS. Please see the image of my controller
![image](https://user-images.githubusercontent.com/634779/69491424-39d4a100-0ebf-11ea-8465-6068069f25c2.png)
RestDebuger Request: 
![image](https://user-images.githubusercontent.com/634779/69491433-5b358d00-0ebf-11ea-8b26-c58dcdbfc2b2.png)
![image](https://user-images.githubusercontent.com/634779/69491437-6688b880-0ebf-11ea-8d72-22ee94d07f74.png)
Postman Request:
![image](https://user-images.githubusercontent.com/634779/69491460-c97a4f80-0ebf-11ea-8c5d-11c3bb47f6e8.png)
A guide will be helpful.

**Comment by fastbike** [comment]
You need an HTTP 'Accepts" header.

The "MVCProduces" attribute maps to HTTP  "Accepts"
The "MVCConsumes" attribute maps to HTTP "Content-Type"

**Comment by shariful2011** [comment]
How do I add the HTTP 'Accepts' header? Can you please help?

**Comment by fastbike** [comment]
Use Postman, and add it as a header

**Comment by shariful2011** [comment]
This is what I did:
add attribute Headers as and problem solved. I have to add MVCFramework.RESTAdapter unit
[Headers('Accept', 'application/json')]

**Comment by fastbike** [comment]
You already have the attribute [MVCProduces('application/json')] in your server code, so there is no need to make any changes to your server code.

You need to add it to the client side call: via Postman, native app, Embo RestDebugger etc

**Comment by danieleteti** [comment]
@shariful2011 did you solve your problem?

**Comment by shariful2011** [comment]
Yes, using accept header on client-side. Thanks for the guide.
