### ISSUE TITLE
Attribute for hidding some URI ressource in the Swagger page

### ISSUE THREAD

**Issue by ads69** [danieleteti/delphimvcframework#303]
Hi,
It could be interesting to using a new attribute for hidding some URI ressources on the swagger (for internal use for instance).

I mean for instance :
 http://api.example.com/pricing/  is visible in Swagger
 http://api.example.com/cost/  is **NOT** visible in Swagger
Best regards

Armindo

**Comment by ads69** [comment]
I have created a new attribute for this

In **MVCFramework.Swagger.Commons.pas** :
•	I have a new attribute : `MVCSwagHiddenInSwaggerAttribute = class(TCustomAttribute);`

In **MVCFramework.Middleware.Swagger.pas**

   In procedure **TMVCSwaggerMiddleware.DocumentApi(ASwagDoc: TSwagDoc); (Line 141)**
```
	        for LAttr in LMethod.GetAttributes do
                    begin
                    ********** Add these two next lines  ************
                    if LAttr is MVCSwagHiddenInSwaggerAttribute then
                     Break;
```
In your controller then you can use `[MVCSwagHiddenInSwagger]` as first Attribute or at least before `[MVCPath(….`

If @danieleteti or @joaoduarte19 can add it in next commit

Thanks

Armindo

**Comment by joaoduarte19** [comment]
@ads69  see pull request #304 

I added this feature. You can add the MVCSwagIgnorePathAttribute attribute to your Controller or its method not to show in the Swagger documentation.

**Comment by ads69** [comment]
Thanks for this feature  @joaoduarte19
