### ISSUE TITLE
Issue with Serialize/Deserialize class ( TObjectList< T > )

### ISSUE THREAD

**Issue by AlbertSchimidt** [danieleteti/delphimvcframework#307]
I'm having trouble trying to serialize/deserialize class ( TObjectList< T > ).

The example:

`[ MVCNameCaseAttribute( ncLowerCase ) ]
TObj1 = class
  prop1 : string;
end;`

`[ MVCNameCaseAttribute( ncLowerCase ) ]
[ MVCListOf( TObj1 ) ]
TObj2 = class ( TObjectList< TObj1 > )
  function asJSONString : string;
end;`

`function TObj2.asJSONString : string;
var
  serialize : TMVCJsonDataObjectsSerializer;
  jsonObj : TJsonObject;
begin
  Result := '';
  try
    serialize := TMVCJsonDataObjectsSerializer.Create;
    jsonObj := TJsonObject;
    serialize.ObjectToJsonObject( Self, jsonObj, stDefault, [] ); // raises exception EMVCSerializationException : 'Cannot serialize list of TypeKind tkArray or tkDynArray'
    Result := jsonObj.ToJSON;
  finally
    serialize.DisposeOf;
    jsonObj.DisposeOf;
  end;
end;`

This DOES work:

`[ MVCNameCaseAttribute( ncLowerCase ) ]
TObj1 = class
  prop1 : string;
end;`

`[ MVCNameCaseAttribute( ncLowerCase ) ]
TObj2 = class
  private
    FList : TObjectList< TObj1 >;
  public
    [ MVCListOf( TObj1 ) ]
    property list : TObjectList< TObj1 > read FList write FList;
    function add( pObj : TObj1 );
    function asJSONString : string;
end;`

`function TObj2.add( pObj : TObj1 );
begin
  FList.add( pObj );
end;`

`function TObj2.asJSONString : string;
var
  serialize : TMVCJsonDataObjectsSerializer;
  jsonObj : TJsonObject;
begin
  Result := '';
  try
    serialize := TMVCJsonDataObjectsSerializer.Create;
    jsonObj := TJsonObject;
    serialize.ObjectToJsonObject( Self, jsonObj, stDefault, [] );
    Result := jsonObj.ToJSON;
  finally
    serialize.DisposeOf;
    jsonObj.DisposeOf;
  end;
end;`

**Comment by joaoduarte19** [comment]
Remove the ```MVCListOf``` attribute and test if it works. In the latest versions of DMVCFramework it can automatically identify object lists, I believe this will work for you.

**Comment by AlbertSchimidt** [comment]
> Remove the `MVCListOf` attribute and test if it works. In the latest versions of DMVCFramework it can automatically identify object lists, I believe this will work for you.

Didn't work sadly. But thanks for the reply.
I couldn't install the newer version, but it seems to work though.
But the error did change to 'Cannot serialize property or field "list" of TypeKind tkArray or tkDynArray'

**Comment by joaoduarte19** [comment]
I think for now the best way to solve your problem is to change your list to a TObjectList<T>, or you can also create a custom serializer for your TListObject<T>.

**Comment by danieleteti** [comment]
@AlbertSchimidt  what's `TListObject`? However, did you sove the problem?

**Comment by AlbertSchimidt** [comment]
> @AlbertSchimidt what's `TListObject`? However, did you sove the problem?

Sorry @danieleteti , I typed incorrectly. Already edited the post.

I created a custom serializer like @joaoduarte19 said but it created a json like this:

`{ [ { "prop1" : "test1" }, { "prop1" : "test2" } ] }`

It didn't create an identificator for the array, so for deserialize it would create another error ( because DMVC wouldn't know what is that array, and I would need to know what is inside it to work with it ).

I solved with an object containing a property of type TObjectList< T >:

`[ MVCNameCaseAttribute( ncLowerCase ) ] TObj1 = class prop1 : string; end;`

`[ MVCNameCaseAttribute( ncLowerCase ) ] TObj2 = class private FObj1List : TObjectList< TObj1 > public [ MVCListOf( TObj1 ) ] property obj1List : TObjectList< TObj1 > read FObj1List write FObj1List; function add( pObj : TObj1 ); function asJSONString : string; end;`

`function TObj2.add( pObj : TObj1 ); begin obj1List.add( pObj ); end;`

`function TObj2.asJSONString : string; var serialize : TMVCJsonDataObjectsSerializer; jsonObj : TJsonObject; begin Result := ''; try serialize := TMVCJsonDataObjectsSerializer.Create; jsonObj := TJsonObject; serialize.ObjectToJsonObject( Self, jsonObj, stDefault, [] ); Result := jsonObj.ToJSON; finally serialize.DisposeOf; jsonObj.DisposeOf; end; end;`

DMVC created a json like this:

`{ "obj1List" : [ { "prop1" : "test1" }, { "prop1" : "test2" } ] }`

To deserialize it, I used:

`var`
`  obj2 : TObj2;`

  `obj2 := Context.BodyAs< TObj2 >;`

**Comment by dan5602** [comment]
I've just come across the same issue.
I am getting this as a reponse:
`{
    "classname": "EMVCSerializationException",
    "items": [],
    "statuscode": 500,
    "reasonstring": "error",
    "message": "Cannot serialize property or field \"List\" of TypeKind tkArray or tkDynArray.",
    "data": null
}`

This occurs when Render is called accepting a TObjectList.
The model I am using is very basic and consists of six fields - all of which are strings.

The issue does not occur if I return a dataset (of the same data) and pass that to Render.

**Comment by danieleteti** [comment]
Yes, it is by design. 
If you want to deserialize a `TObjectList<TFoo>` you have to use

```delphi
  LMyFooList := Context.Request.BodyAsListOf<TFoo>();
```

or 

```delphi
  LMyFooList := TObjectList<TFoo>.Create;
  Context.Request.BodyForListOf<TFoo>(LMyFooList);
```

if you want to serialize a collection you have to use:

```delphi
  Render<TFoo>(LMyFooList);
```

**Comment by dan5602** [comment]
Thanks Daniele!
