### ISSUE TITLE
How to remove DMVCFramework System Controller

### ISSUE THREAD

**Issue by viniciussanchez** [danieleteti/delphimvcframework#308]
How to remove DMVCFramework System Controller?

![image](https://user-images.githubusercontent.com/16382981/69831475-55fe7800-1208-11ea-8a1a-c6f039fbd6f5.png)

**Comment by viniciussanchez** [comment]
I managed to put this "if" but I don't know if it's the best practice.

![image](https://user-images.githubusercontent.com/16382981/69831562-a5dd3f00-1208-11ea-9121-72550da17c59.png)

**Comment by joaoduarte19** [comment]
In your WebModule, after creating your TMVCEngine clean the controllers:
```delphi
FEngine := TMVCEngine.Create(Self);
FEngine.Controllers.Clear;
```
This will remove the SysControllers from your API.

**Comment by danieleteti** [comment]
faq

**Comment by viniciussanchez** [comment]
Ok, thanks
