### ISSUE TITLE
DMVC server as linux daemon

### ISSUE THREAD

**Issue by joaoduarte19** [danieleteti/delphimvcframework#310]
Is there a best practice for building a server like Daemon Linux?

I did some tests using the code:
```delphi
  try
    ... 
    if fork() <> 0 then
    begin
      exit;
    end;
    while true do
      sleep(100);
  except
    on E: Exception do
      Writeln(E.ClassName, ': ', E.Message);
  end;

```
This worked, but generated some unexpected errors.

I did a quick search on the dmvc examples and found no such examples. I think it would be interesting an example of building the server as a linux daemon

**Comment by budisatya** [comment]
i use systemd to run dmvc console as daemon,
so u can using systemctl to start/stop

ex: create file dmvc.service
then u can run
systemctl start dmvc
systemctl stop dmvc
...
