### ISSUE TITLE
Cannot use gzip compression in REST Client

### ISSUE THREAD

**Issue by spinettaro** [danieleteti/delphimvcframework#313]
If you try to use 'GZIP' as content encoding the application raise an Exception.
This is the code to test the scenario:
```procedure TForm1.Button1Click(Sender: TObject);
var
  lCLient:   TRESTClient;
  lString:   string;
  lResponse: IRESTResponse;
begin
  lCLient := TRESTClient.Create('http://localhost', 8887);
  try
    lString := '{"key":"value"}';

    lCLient.ContentEncoding('gzip');
    lCLient.Compression(True);

    lResponse := lCLient.doPOST('/api/convertfile', [], lString);

  finally
    lCLient.Free;
  end;
end;
```

The problem is related to this line of code: line 1451 of MVCframework.RESTclient
```
lEncoding := TEncoding.GetEncoding(lContentCharset); 
``` 

Should be also worth to understand the function lCLient.Compression(True); what role plays.

**Comment by spinettaro** [comment]
In addition the automatic decompression of the response is done only in SendHTTPCommand and not in SendHTTPCommandWithBody

**Comment by danieleteti** [comment]
This will be addressed when TRESTClient will be rewritten to use the new THTTPClient instead of INDY.
