### ISSUE TITLE
Post with nested object

### ISSUE THREAD

**Issue by kaluznyo** [danieleteti/delphimvcframework#318]
Hi,

I try to make a POST with 'custom' object in my JSON like:
`
{
  "UnikId": 255,
    "Operator": {
    	"NoOperator": 100	
    }
}
`

In my model I have something like this : 

`
property Operator : TOperator read FOperator write FOperator;
`

When I get the post like this :
`context.Request.BodyAs<TcdeOp>`

I get an error : AcessViolation : Global Action Exception Handler"

I think it's because the framework dont' know how serialize Operator. If it's right, how can we achieve this type of POST ?

**Comment by joaoduarte19** [comment]
Could you provide the structure of your classes? 
If they are classes that inherit from TObjects they should deserialize correctly. However, if your TOperator class inherits from a complex object, you must create a custom serializer/deserializer.

**Comment by danieleteti** [comment]
Is fOperator correctly initialized? The deserializer doesn't create target properties.

**Comment by danieleteti** [comment]
News about this issue?

**Comment by osaris** [comment]
For this case we found a workaround but we have another case where object properties are not deserialized. We are working with TObject only.

Here are the class involved in our new case :
```
  TSvijrnl = class(TObject)
  private
    FUniksvijrnl : Integer;
    FUnikCdeOp : Integer;
    FLots : TObjectList<TCdeLot>;
  public
    constructor Create(DataSet : TDataSet);
    property UnikSviJrnl : integer read FUnikSviJrnl write FUnikSviJrnl;
    property UnikCdeOp : integer read FUnikCdeOp write FUnikCdeOp;
    property Lots : TObjectList<TCdeLot> read FLots write FLots;
  end;

  TCdeLot = class(TObject)
  private
    FNoLot : Integer;
    FSuivis : TObjectList<TSuivi>;
  public
    constructor Create(DataSet : TDataSet);
    property NoLot : integer read FNoLot write FNoLot;
    property Suivis : TObjectList<TSuivi> read FSuivis write FSuivis;
  end;
````
and I try to POST a TSviJrnl with :
```
{
    "UnikCdeOP":        202452,
    "Lots" : [
        {
            "NoLot":    88569
        },
        {
            "NoLot":    88570
        }
    ]
}
````

but Svijrnl.Lots when I expect it to contains two TCdeLot with NoLot set for each one.

**Comment by osaris** [comment]
I fixed my problem by creating a basic constructor (without DataSet parameter) and initiliazing FLots properties in it.

This issue can be closed ;-)

**Comment by danieleteti** [comment]
Good :-)
If you want you  can produce an `how to` so that other developers can find easly such information.

**Comment by danieleteti** [comment]
> I fixed my problem by creating a basic constructor (without DataSet parameter) and initiliazing FLots properties in it.
> 
> This issue can be closed ;-)

You can also use `Context.Request.BodyFor<TSvijrnl>(lInstance)` instead of BodyAs.

**Comment by osaris** [comment]
> If you want you can produce an `how to` so that other developers can find easly such information.

Where are the `how to` located ? (personally I looked at the tests to fix my issue ;-)).
