### ISSUE TITLE
Windows Service not Work JWT

### ISSUE THREAD

**Issue by juliomar** [danieleteti/delphimvcframework#319]
Hello. I created a server with JWT authentication and used the console to debug, after I decided to put run as a Windows service. Good from there he even calls the endpoint of the token but ahead of it will not, he returns Unsupported authorization scheme. In this case the correct error is class EIdHTTPProtocolException with message 'HTTP / 1.
1,401 Unauthorized '.

Has anyone been through this or is having the same problem?

**Comment by joaoduarte19** [comment]
This error has happened to me when I had not implemented the TIdHTTPWebBrokerBridge OnParseAuthentication event.
For this case I did so to solve:
```` delphi
uses
  MVCFramework.Commons;
...

  FServer := TIdHTTPWebBrokerBridge.Create(Self);
  FServer.OnParseAuthentication := TMVCParseAuthentication.OnParseAuthentication;
...
````

**Comment by juliomar** [comment]
It worked at first. I took the example as a base, but it does not have this implementation. Thank you very much the ticket can be closed. I believe that if possible adding the code in the example will help many others.

**Comment by danieleteti** [comment]
What sample are you talking about? We should change it to make it clearer the use of `TMVCParseAuthentication.OnParseAuthentication`.

**Comment by juliomar** [comment]
> What sample are you talking about? We should change it to make it clearer the use of `TMVCParseAuthentication.OnParseAuthentication`.

\samples\windowsservice file ServiceU.pas line 66 the excerpt is not present FServer.OnParseAuthentication := TMVCParseAuthentication.OnParseAuthentication;
