### ISSUE TITLE
Make logWritter Public in Analytics Middleware

### ISSUE THREAD

**Issue by ads69** [danieleteti/delphimvcframework#321]
Hi,
In unit MVCFramework.Middleware.Analytics.pas can you make the property LogWriter Public ?
Something like that :
```
type
  TMVCAnalyticsMiddleware = class(TInterfacedObject, IMVCMiddleware)
  private
    FLogWriter: ILogWriter;
  protected
    procedure OnBeforeRouting(Context: TWebContext; var Handled: Boolean);
    procedure OnAfterControllerAction(Context: TWebContext; const AActionNAme: string; const Handled: Boolean);
    procedure OnBeforeControllerAction(Context: TWebContext; const AControllerQualifiedClassName: string; const AActionNAme: string;
      var Handled: Boolean);
  public
    constructor Create(const ALogWriter: ILogWriter); virtual;
    property LogWriter:ILogWriter read FLogWriter write FLogWriter;

  end;
```

thanks

Armindo

**Comment by danieleteti** [comment]
Sure, but what's the reason?

**Comment by ads69** [comment]
Hi Daniele,
if you want to create a class that inherit form TMVCAnalyticsMiddleware
Something like 
`Type
  TMVCEWAnalyticsMiddleware = Class(TMVCAnalyticsMiddleware)
  Protected
    Procedure OnBeforeControllerAction(Context: TWebContext; Const AControllerQualifiedClassName: String; Const AActionNAme: String;Var Handled: Boolean);
  End;`
and you need to acces the LogWriter object.
Best regards

Armindo

**Comment by fastbike** [comment]
> if you want to create a class that inherit form TMVCAnalyticsMiddleware
> Something like
> `Type TMVCEWAnalyticsMiddleware = Class(TMVCAnalyticsMiddleware) Protected Procedure OnBeforeControllerAction(Context: TWebContext; Const AControllerQualifiedClassName: String; Const AActionNAme: String;Var Handled: Boolean); End;`
> and you need to acces the LogWriter object.

Override the constructor, which takes the instance of the ILogWriter object ?

**Comment by ads69** [comment]
fastbike,

> Override the constructor, which takes the instance of the ILogWriter object ?

you're right but if you look at the source code it's like cloning the original class.

**Comment by fastbike** [comment]
Yes, I agree a bit untidy as you'll need to store a second access to the LogWriter, but it works :)
