### ISSUE TITLE
Authentication EndPoints are not at the Top of Swagger

### ISSUE THREAD

**Issue by ads69** [danieleteti/delphimvcframework#322]
Hi,
Now EndPoints are sorted and always appear in the same order, this is great.
But it has a smal drawback, the authentication endpoint (JWT for instance) is lost among the others, it would be nice tho have all the authentication Endpoints on the top of the list.
Best regards

Armindo

**Comment by joaoduarte19** [comment]
This would work well for authentication middleware. However, the user can create a custom authentication that cannot be mapped to put at the top of the list.

**Comment by ads69** [comment]
If at least the authentication middleware are taken in account, that would be a nice improvement !
