### ISSUE TITLE
Memory leak in DMVCServer

### ISSUE THREAD

**Issue by joaoduarte19** [danieleteti/delphimvcframework#323]
When testing my DMVC server, I noticed that in some cases a memory leak is occurring. I tried to find this memory leak, but I couldn't.
I believe it is caused when the client application makes a request and is closed before receiving the response.
I made an example that generates the same memory leak as my application.

[TestMemoryLeak.zip](https://github.com/danieleteti/delphimvcframework/files/4105933/TestMemoryLeak.zip)

In this example, when the server starts, it opens a web page that requests the server.
When I close the page in my browser, then I stop my DMVC server and close the memory leak, as in the image below:

![memoryleak](https://user-images.githubusercontent.com/13373632/73030519-964d3180-3e18-11ea-8ab6-c26f24181958.png)

I believe that because of this memory leak, my server gradually increases the memory consumption until a moment that locks up and only works again after restarting.

**Comment by danieleteti** [comment]
We'll look into this ASAP

**Comment by joaoduarte19** [comment]
Very thanks!
Now it's working wonderfully!!!
