### ISSUE TITLE
Routes distinction

### ISSUE THREAD

**Issue by viniciussanchez** [danieleteti/delphimvcframework#325]
I have a problem, the framework is understanding that the routes below are the same:

../api/users
**../api/users/1**
**../api/users/permissions**

When I try to access the permissions, it converts "permissions" on the understanding that it is a parameter of the other route.

I'm using Delphi 10.3.3

**Comment by danieleteti** [comment]
The router scans the action in the order of declaration. Just declare the "more specific" routes before the more "general" ones.
In your case I'd do the following

../api/users/permissions
../api/users/1
../api/users

**Comment by viniciussanchez** [comment]
We ended up discovering this ....

Couldn't the framework do this internal sorting? That would be good ... since it is a necessity for him ...

**Comment by danieleteti** [comment]
We really want to avoid such "magic" behavior. I really prefer "explicit" instead of "implicit". Simply must be clear the criterias on which the router works. What's your POV about this?

**Comment by viniciussanchez** [comment]
I think that if the framework turned around it would be better.
Developers should not be concerned about this. It took me a long time to discover that this was possible, but that I had to put it in order. Until then, I thought it was not possible using DMVC.
In other fameworks of other languages like Java, GoLang, this is already something internal, standard of the framework. He who differentiates routes.
But I understand your point of view...
