### ISSUE TITLE
TMVCActiveRecordController DB connection reconnecting to DB engine after each request

### ISSUE THREAD

**Issue by biware-repo** [danieleteti/delphimvcframework#326]
FDConnection in TMVCActiveRecordController is disconnected after each action processed.
If another request arrived it is connecting again to DB. Connecting requires some time and due to this fact, there is approximatelly 500ms from request to response. Requests are sent from same session (so it should be 1 Webmodule)

Is there any workaround to keep DB connection connected, or any fix? 
What is lifecycle of WebModule in DMVC Framework?
Where should be created datamodule with DB connection and why TMVCActiveRecordController requires DB Connection other than this in datamodule?

**Comment by danieleteti** [comment]
It is not a concern of tmvcactiverecord. It is the fdconnection that must be configured with pooling. TMVCActiveRecord just use the provided connection (that must be in pooling).
