### ISSUE TITLE
error building dmvcframeworkРТ102

### ISSUE THREAD

**Issue by alextim400** [danieleteti/delphimvcframework#333]
I am trying to build dmvcframeworkRT102, but I get an error while compiling the unit Serializer.Common.pas: Unit MVCFramework.Nullables not found. There is such a file in source. What's the matter here?

**Comment by danieleteti** [comment]
Just include the unit in the package `dmvcframeworkrt`. It will be included in the next RC.

**Comment by alextim400** [comment]
Same issue with MVCFramework.log. Thanks for the advice.

**Comment by danieleteti** [comment]
Current repo should be ok. Please test it and let me know.

**Comment by danieleteti** [comment]
Is the problem fixed?

**Comment by alextim400** [comment]
I fixed it according to your advice. Everything worked out. Thanks. I did not do repository updates.
