### ISSUE TITLE
TDataSetUtils.DataSetToObject Compliant with TNullableType

### ISSUE THREAD

**Issue by ads69** [danieleteti/delphimvcframework#336]
Hi,
today I use something like : TDataSetUtils.DataSetToObject(lDataSet, lCustomer);
I would like to change some properties of my Object to make them Nullable.
But doing this calling this procedure raise an error saying : Nullable must have a value.
How could I do to make it compatible with TNullable Type ?
Best reagrds

Armindo

**Comment by danieleteti** [comment]
Can you provide a simple test case with just one procedure which show the problem?

**Comment by ads69** [comment]
Ok Daniele, will do a test case tonight.

**Comment by ads69** [comment]
Daniele,
I have tryed to reproduce it in a very small project with no success unfortunatelly.
I think that some units that I use in a bad way may lead to this, because I have another problem with the swagger (I cannot open it) when MVCFramework.Serializer.JsonDataObjects is in my uses.
I close the issue for the moment and will try to investigate more later.
Thanks again.

**Comment by danieleteti** [comment]
You are welcome, let me know about your findings.

**Comment by ads69** [comment]
Daniele,
I have found the problem the DatasetToObjet doesn't raise the error (not easy to catch since I was using a service). In fact the Nullable property doesn't take the value, it keep staying in a nill state.
look at the sample
[Project1.zip](https://github.com/danieleteti/delphimvcframework/files/4294247/Project1.zip)

Hope this help.

**Comment by danieleteti** [comment]
Actually there was an issue, but the sample provided uses the `Spring` nullables, and not the `dmvcframework` nullables. In the repo now you can use the fixed version which solve the problem. Also here you can fnd the corrected sample.

[Project1.zip](https://github.com/danieleteti/delphimvcframework/files/4303679/Project1.zip)

**Comment by ads69** [comment]
Great ! Thanks Daniele.
