### ISSUE TITLE
Install of DMVC fails - 

### ISSUE THREAD

**Issue by alangittest** [danieleteti/delphimvcframework#34]
I follow the easy install 5 minutes guide.

When I press install I get error message "required package expertscreators not found".

Why don't people test things these days ???

![image](https://cloud.githubusercontent.com/assets/15258900/13721329/e71516ae-e855-11e5-80dc-9b4cc3baf70d.png)

**Comment by alangittest** [comment]
On the Facebook support page I see someone else has the same issue.  But no fix.

**Comment by littleearth** [comment]
What version of Delphi Seattle do you have? Trial? Do you have the folder
C:\Program Files (x86)\Embarcadero\Studio\17.0\source\Experts?

**Comment by alangittest** [comment]
Hi.

Thanks for your email.

I have delphi XE7 pro.

I do not have that folder.

I have studio\15.0\source.




Sent from Outlook Mobile<https://aka.ms/blhgte>



On Sat, Mar 12, 2016 at 7:17 AM -0800, "littleearth" <notifications@github.com<mailto:notifications@github.com>> wrote:


What version of Delphi Seattle do you have? Trial? Do you have the folder
C:\Program Files (x86)\Embarcadero\Studio\17.0\source\Experts?

-

**Comment by littleearth** [comment]
1.) The package you are installing is for Seattle. XE7, XE8, Seattle (10)
2.) You do not need the expert package installed to use MVCF so you can still run the demos
3.) So you do no have an experts folder under source (I see the same in my XE8 installation?)

**Comment by alangittest** [comment]
I do not have the experts subfolder.

If i take out the 'requires expertscreator' line from the project, it comes up with another error about cannot find experts something else.

Sent from Outlook Mobile<https://aka.ms/blhgte>

**Comment by danieleteti** [comment]
The expert package is in beta test and is for Delphi 10 Seattle. These requirements are not meet by your Delphi setup.
I suggest you to create dmvcframework by hand as shown by the various samples.

**Comment by lhengen** [comment]
I am using DX Seattle with Subscription update 1 (Embarcadero® Delphi 10 Seattle Version 23.0.21418.4207) and using "Getting Started: the 5 minutes guide" I have encountered the same issue.  My install meets the requirements as per your comment above.  The "ExpertsCreators.dcp" cannot be found.  This same DCP is referenced for the Berlin DPROJ.  When will the source, or a DCP be included in GIT?  How can we beta test something not in the repo?

**Comment by danieleteti** [comment]
@lhengen Do you have the folder C:\Program Files (x86)\Embarcadero\Studio\17.0\source\Experts?

**Comment by lhengen** [comment]
No I do not.

**Comment by danieleteti** [comment]
That's the problem. Do you have a trial version?

**Comment by lhengen** [comment]
No I do not.  This is a new Windows 10 machine on which I had to install DX
Seattle with Update 1 from the ISO, and then I applied the hotfixes that
EMBT back ported and released after Berlin 10.2.  I have the Delphi
Professional Edition if that makes any difference.

**Comment by lhengen** [comment]
Why not distribute the DCP?

**Comment by danieleteti** [comment]
@lhengen because is copyright by EMBT and is part of RAD Studio. I cannot distribute it, you should already have it.
The problem is with the professional version. I don't have a professional version where do the tests.
The experts is based on DUnitX expert (https://github.com/VSoftTechnologies/DUnitX/tree/master/Expert). Can you try to install the related expert from DUnitX? Can you find where are the difference? I'll be glad to make the package installable also with pro version.

**Comment by danieleteti** [comment]
@lhengen dont loose your time.. DUnitX project had the very same problem
https://github.com/VSoftTechnologies/DUnitX/issues/160

We are waiting for a fix in the installation process.

**Comment by lhengen** [comment]
Marco released the DCP file in https://quality.embarcadero.com/browse/RSP-18303 but didn't make it widely known,  Just ran across it today.
