### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by 1Dragon** [danieleteti/delphimvcframework#343]
hello, 
I'm fascinated with the bootstrap, 
it turns out that I still don't understand anything about it,
I just saw a small example in MARS, 
could someone include a small example that lists a dataset with DelphiMvcFramework? 
I would be very grateful ;-)

thanks in advanced.

**Comment by danieleteti** [comment]
Hi, you all sort of example just in the project: https://github.com/danieleteti/delphimvcframework/tree/master/samples

Take a look to the sample `renders.dproj`

Welcome aboard :-)
