### ISSUE TITLE
articles_crud_web_angular not working

### ISSUE THREAD

**Issue by raelb** [danieleteti/delphimvcframework#346]
Running the web application (localhost:4200) shows this error in the console:
Error in :0:0 caused by: this.http.get(...).map is not a function

![image](https://user-images.githubusercontent.com/13108198/77247743-8ac18f80-6c3c-11ea-80b2-012fb15f4c27.png)

**Comment by danieleteti** [comment]
This sample is outdated, will be removed in the next RC.
