### ISSUE TITLE
activerecord: suggested patch for field name with spaces

### ISSUE THREAD

**Issue by drcrck** [danieleteti/delphimvcframework#348]
Hi, 
I have to publish a table for crud in my Firebird db, and we decide to try active record.
unforunately this table have some filednames with spaces inside. (is imported , it's not our choice! )

first bug to check : active record generator gave it a wrong name : we must add quote( " ) to MVCTableField ; 

second one : select statement crash, because in LoadByDataset  this method call
"lField := aDataSet.FindField(lItem.Value);"  doesn't find the field. 

I patch it simply in this way:  
lField := aDataSet.FindField(lItem.Value.DeQuotedString('"') );

i hope this can be useful.
Ciao

**Comment by drcrck** [comment]
hi, following this topic, i add other 2 changes made to permit post : 

in  TMVCSQLGeneratorFirebird.CreateInsertSQL
I changed the params creation in  this way : 

lSB.Append(':' + lKeyValue.value.**DeQuotedString('"').Replace(' ','')** + ',');

and in TMVCActiveRecord.ExecNonQuery :
lPar := lQry.FindParam(lPair.Value.**DeQuotedString('"').Replace(' ','')** );

maybe some similar mods are to be considered for CreateUpdateSQL.

**Comment by danieleteti** [comment]
I'll look into this ASAP.

**Comment by danieleteti** [comment]
This feature has been implemented for PostgreSQL (by [this](https://github.com/danieleteti/delphimvcframework/commit/e56fb272a93e4b78046b63357745c7d18ed42e82) commit ). I don't know when this will be available for Firebird too. It is not complicated at all, if you want to contribute.
