### ISSUE TITLE
StompTypes.dcu not found

### ISSUE THREAD

**Issue by alangittest** [danieleteti/delphimvcframework#35]
![image](https://cloud.githubusercontent.com/assets/15258900/13728223/69e6ae1a-e943-11e5-9cd6-0c6fa63ae233.png)

The subfolder delphistompclient is empty.

I tried both the github zip file and also doing a clone of the github repository.

I see a closed issue with the same error message.  I don't understand the response to the issue.

**Comment by danieleteti** [comment]
Check the FAQ chapter in the DelphiMVCFramework Developer Guide
https://danieleteti.gitbooks.io/delphimvcframework/content/chapterfaq.html
