### ISSUE TITLE
error line 1969 

### ISSUE THREAD

**Issue by jordilp69** [danieleteti/delphimvcframework#350]
Result := lList.ExtractAt(0);

[dcc32 Error] MVCFramework.ActiveRecord.pas(1969): E2003 Undeclared identifier: 'ExtractAt'

Delphi 10.2 Tokyo

**Comment by joaoduarte19** [comment]
This "ExtractAt" method was introduced in delphi 10.3 Rio. It must be changed to fit previous versions of delphi.

**Comment by danieleteti** [comment]
Does this line compile?

```delphi
    Result := lList.Extract(lList.First);
```
