### ISSUE TITLE
TMVCActiveRecord with MSSQL

### ISSUE THREAD

**Issue by st1gok** [danieleteti/delphimvcframework#358]
Hi!

Use release 3_2_0-boron-RC5

I try framework with mssql and get error SQLGenerator not found for "mssql".

**Comment by danieleteti** [comment]
Did you added the unit as suggested by the exception message?

**Comment by st1gok** [comment]
Thanks!!!
This is the first look at your framework. It looks very pretty and functional. Gives a similar principle of work as in other languages ​​with rest services. More documentation and would be super

**Comment by danieleteti** [comment]
We are working for that. Thank you your kind words.

**Comment by st1gok** [comment]
I have one problem with render result TMVCActiveRecord.All. "Cannot serialize property or field "List" of TypeKind tkArray or tkDynArray." 
I again did not add something?
