### ISSUE TITLE
serialization ignore empty or null fields

### ISSUE THREAD

**Issue by st1gok** [danieleteti/delphimvcframework#361]
Hi!
Maybe there is a serialization engine setting for ignore empty or null fields entities?

**Comment by joaoduarte19** [comment]
There is nothing to ignore empty or null fields in entities. When a field is null it is serialized in JSON with the value null. I believe this is the correct behavior for any serializer.
Just out of curiosity, why would you like to ignore empty or null fields in your use case?

**Comment by st1gok** [comment]
this behavior is found in many serializers in other languages. It also reduces the processing and unnecessary amount of data when exchanging for example with mobile devices

**Comment by danieleteti** [comment]
Up to version 2.x also DMVCFramework used to work as you suggest. Then, after a lot of users asked, we switched to the current "more predictable" implementation.
You can inherit from the current serializer and implement all the changes you need. The you can plug this serializer and replace the current one.
