### ISSUE TITLE
Dataset Helper Case

### ISSUE THREAD

**Issue by budisatya** [danieleteti/delphimvcframework#366]
hi daniele
i try to change dataset record to json object

fdquery.asJSONObject(fpLowerCase) <-- not working, always large case in firebird

i see in MVCFramework.Dataset.Utils :

function TDataSetHelper.AsJSONObject(AFieldNamePolicy: TFieldNamePolicy): string;
var
lSerializer: IMVCSerializer;
begin
lSerializer := TMVCJsonDataObjectsSerializer.Create;
Result := lSerializer.SerializeDataSetRecord(Self, [], ncAsIs);
// Mapper.DataSetToJSONObject(Self, JObj, false);
end;

AFieldNamePolicy <-- not going anywhere or i'm wrong?
and
Result := lSerializer.SerializeDataSetRecord(Self, [], ncAsIs); <-- always AsIs Case ???
or maybe i miss something?

**Comment by danieleteti** [comment]
Fixed in the repo. Please, let me know.

**Comment by budisatya** [comment]
Than'k u Daniele
uppercase - working
lowercase - working
camelcase - i dont know what suppost to came out, in my computer its came uppercase
