### ISSUE TITLE
TMVCActiveRecordController enhacement

### ISSUE THREAD

**Issue by biware-repo** [danieleteti/delphimvcframework#371]
It would great, if TMVCActiveRecordController have had swagger support. 
Eg. like in attached picture. 
![swagger_example](https://user-images.githubusercontent.com/22624070/80571956-c4d13e80-89fd-11ea-89cf-e918fa4e651c.png)

**Comment by danieleteti** [comment]
Wow! How many requests in one issue :-) Please, split minor requests in different issues. However, the ability to don't load system controller has been [just commited](https://github.com/danieleteti/delphimvcframework/commit/89d723fbde23854e255b3da72daff016d9c65f3c)
