### ISSUE TITLE
Expand function TMVCJsonDataObjectsSerializer.JsonArrayToArray(const AJsonArray: TJDOJsonArray): TValue;

### ISSUE THREAD

**Issue by dockerandy** [danieleteti/delphimvcframework#378]
Hello Daniele,

thank you for the great framework! We are very happy with this!
Can you expand the function TMVCJsonDataObjectsSerializer.JsonArrayToArray(const AJsonArray: TJDOJsonArray): TValue; to other datatypes like float, bool, .... 
I've done this in my enviroment for jdtFloat and it makes Serialization live easier. :)
I'm not shure if there are constraints that prevent such a modification?

Greetings
Andreas

function TMVCJsonDataObjectsSerializer.JsonArrayToArray(
  const AJsonArray: TJDOJsonArray):TValue;
var i:integer;
    lStrArr:TArray<String>;
    lIntArr:TArray<Integer>;
    **lDoubleArr:TArray<Double>;**
begin
  for I := 0 to Pred(AJsonArray.Count) do
    case AJsonArray.types[0] of
      jdtString : lStrArr := lStrArr + [AJsonArray.Items[i].Value];
      jdtInt    : lIntArr := lIntArr + [AJsonArray.Items[i].Value.ToInteger];
      **jdtFloat  : lDoubleArr := lDoubleArr + [AJsonArray.Items[i].FloatValue];**
    end;

  if Length(lStrArr)>0 then
    result := TValue.From<TArray<String>>(lStrArr)
  else if Length(lStrArr)>0 then
    result := TValue.From<TArray<Integer>>(lIntArr)
  **else
    result := TValue.From<TArray<Double>>(lDoubleArr)**
end;

**Comment by danieleteti** [comment]
Added support for Double and Int64 arrays

https://github.com/danieleteti/delphimvcframework/commit/a1c6d82198f73eab7f5b08e52b216d750d282c38
