### ISSUE TITLE
Memory Leak in Swagger doc

### ISSUE THREAD

**Issue by maiconsi** [danieleteti/delphimvcframework#379]
Identify some memory leaks in the Swagger classes.
Follow the corrections.
File: Swag.Doc.pas
Line: 261
`Result.AddPair(fDefinitions.Items[vIndex].Name, fDefinitions.Items[vIndex].JsonSchema.Clone as TJSONObject);`
*****************************
File: Swag.Doc.Defnition.pas
Line: 73
```
if Assigned(fJsonSchema) then
    FreeAndNil(fJsonSchema);
```
File: Swag.Doc.Path.Operation.RequestParameter.pas
Line: 208
`vJsonObject.AddPair(c_SwagRequestParameterSchema, fSchema.JsonSchema.Clone as TJSONObject);`
File: Swag.Doc.Path.Operation.Response.pas
Line: 147
`vJsonObject.AddPair(c_SwagResponseSchema, fSchema.JsonSchema.Clone as TJSONObject);`
Line: 189
`fSchema.JsonSchema := pJson.Values[c_SwagResponseSchema].Clone as TJSONObject;`

[Source.zip](https://github.com/danieleteti/delphimvcframework/files/4596410/Source.zip)

**Comment by joaoduarte19** [comment]
Can you provide an example that generates memory leaks? Because using the current version of SwagDoc I couldn't find any memory leaks.

**Comment by maiconsi** [comment]
Hello, sorry for the delay.
You can actually use the DMVCFramework example "swaggerdoc".
The only difference is that I am using FastMM4.
I verified that if I don't use it, these errors don't occur, now I don't know if it's a delphi failure to not report this leak or FastMM4's failure!
![Screenshot_69](https://user-images.githubusercontent.com/46498249/82499367-f2bf1580-9ac7-11ea-9243-54fd0556b4a0.png)
![Screenshot_68](https://user-images.githubusercontent.com/46498249/82499379-f6eb3300-9ac7-11ea-9490-8e11a05c47e9.png)
![Screenshot_67](https://user-images.githubusercontent.com/46498249/82499384-f94d8d00-9ac7-11ea-883f-5fb29b12b4da.png)

**Comment by joaoduarte19** [comment]
Thanks for the contribution!
