### ISSUE TITLE
pas file encoding & render problem

### ISSUE THREAD

**Issue by holdelphi** [danieleteti/delphimvcframework#380]
Delphi 10.3.3
DMVCFramework : 3.2.0 RC7

1. some pas unit file maybe using UTF-8 or unicode is better, 
for example in source file : "MVCFramework.Commons.pas"，
I MUST change this file to UTF-8 endcoding.

Line 119:     `URL_MAPPED_PARAMS_ALLOWED_CHARS = ' 噼轾蜢''"@\[\]\{\}\(\)\=;&#\.:!\_,%\w\d\x2D\x3A';`

correct after change file encoding to utf-8 : `URL_MAPPED_PARAMS_ALLOWED_CHARS = ' àèéùòì''"@\[\]\{\}\(\)\=;&#\.:!\_,%\w\d\x2D\x3A';`

2. Render problem, using below json string to render, the response conent will be blank.

var jsonStr:string;
begin
jsonStr =
`{"status":200,"msg":"ok","data":{"uid":1,"real_name":"","birthday":0,"card_id":"","partner_id":0,"group_id":0,"nickname":"hello","avatar":"","phone":"","now_money":0,"brokerage_price":0,"integral":101,"sign_num":0,"level":0,"spread_uid":0,"spread_time":0,"user_type":"vip","is_promoter":0,"pay_count":14,"spread_count":0,"addres":"","adminid":false,"login_type":"","couponCount":0,"like":1,"orderStatusNum":{"order_count":14,"sum_price":10.6,"unpaid_count":0,"unshipped_count":0,"received_count":0,"evaluated_count":2,"complete_count":0,"refund_count":0},"notice":1,"brokerage":1,"recharge":0,"orderStatusSum":10.6,"extractTotalPrice":0,"extractPrice":0,"statu":2,"vip":true,"vip_id":0,"vip_icon":"","vip_name":"gold","yesterDay":0,"recharge_switch":0,"switchUserInfo":[{"id":1,"uid":1,"real_name":"","birthday":0,"card_id":"","partner_id":0,"group_id":0,"nickname":"kitty","avatar":"","phone":"","now_money":0,"brokerage_price":0,"integral":101,"sign_num":0,"level":0,"spread_uid":0,"spread_time":0,"user_type":"vip","is_promoter":0,"pay_count":14,"spread_count":0,"addres":"","adminid":0,"login_type":""}]}}`

Render(jsonStr);  // the response content will be return blank (not anything)....
//ctx.Response.Content := jsonStr;   // this code is OK
end;

**Comment by danieleteti** [comment]
Hi, thenk you for your issue. Can you reproduce the problem with a self-contained project? We cannot reproduce the issue.
