### ISSUE TITLE
Incompatible types TArray in TDataSetHelper

### ISSUE THREAD

**Issue by Margera** [danieleteti/delphimvcframework#382]
Hi!

Delphi 10.1 Berlin - Update 2
DMVCFramework : 3.2.0 RC7

Is there an easy way to get around this problem?

![image](https://user-images.githubusercontent.com/14941476/81588384-cea85980-938e-11ea-8349-61b0b8e59471.png)

**Comment by danieleteti** [comment]
Did you tried to use nil as default param? We don't have Berlin to test. Let me know

**Comment by Margera** [comment]
I hadn't tried it, I don't know how I haven't tested something so simple before, now it's compiling correctly

**Comment by danieleteti** [comment]
Ok, we will change that as nil. Thank you

**Comment by joaoduarte19** [comment]
I applied this fix to commit 86c28eb6614022dd8e03a0c4d71953786ddb27de
