### ISSUE TITLE
Exception when swagger will sort paths

### ISSUE THREAD

**Issue by Margera** [danieleteti/delphimvcframework#383]
Hi!

Delphi 10.1 Berlin - Update 2.: Fail
DMVCFramework : 3.2.0 RC7

Tested on Delphi 10.3 Trial.: Ok

When calling the /swagger/index.html page(Sample swaggerdoc) there is an exception in the comparer methods, I couldn't find the focus, but I could see that at some point the Left is not sent, probably an index problem.

The error occurs in the unit `MVCFramework.Middleware.Swagger`, method `SortApiPaths`

![image](https://user-images.githubusercontent.com/14941476/81729790-f1a43d80-9462-11ea-988e-203d0810f54a.png)

![image](https://user-images.githubusercontent.com/14941476/81729808-f8cb4b80-9462-11ea-9dc8-33313e96e39f.png)

**Comment by joaoduarte19** [comment]
I will check this ASAP
