### ISSUE TITLE
aContext.Request.ParamNames

### ISSUE THREAD

**Issue by iliauta** [danieleteti/delphimvcframework#388]
Using DMVL BORON RC7. 

Call to service looks like https://localhost:8081/service/query?firstname=AAA&lastname=BBB

In the procedure of the controller 

lNames := aContext.Request.ParamNames;
  for I := 0 to length(lNames) - 1 do
  begin
    lres := lres + ',' + lNames[i];
  end;

I get 4 items array. 
firstname,lastname,firstname,lastname

I think it's incorrect.

**Comment by danieleteti** [comment]
Yes, I think so. We'll investigate.
