### ISSUE TITLE
ReadOnly Field in ActiveRecord

### ISSUE THREAD

**Issue by ads69** [danieleteti/delphimvcframework#392]
Hi Daniele,
Is there a way to have a ActiveRecord field in ReadOnly ?
I have looked at TMVCActiveRecordFieldOption but the foTransient option doesn't retrieve the field value.
I want the field to be read but not written.
Best regards
Armindo

**Comment by danieleteti** [comment]
Currently use `foAutogenerated`. A proper `foReadOnly` and `foWriteOnly` attributes are in the roadmap.

**Comment by ads69** [comment]
Thanks for adding this Daniele !

**Comment by danieleteti** [comment]
Check activerecord_showcase sample to see how to use `foReadOnly` and `foWriteOnly`

**Comment by ads69** [comment]
Great ! Thanks Daniele !
