### ISSUE TITLE
installation issue on XE8 entreprise

### ISSUE THREAD

**Issue by samimetoui** [danieleteti/delphimvcframework#393]
Good morning 

I am trying to install delphimvcframework on XE8. Because i cannot install the IDEExpert then i do it by hand like described in the FAQ §3  I cannot install the IDEExpert, can I use DelphiMVCFramework without it?
[here](https://danieleteti.gitbooks.io/delphimvcframework/content/chapterfaq.html)

first i have created a webbroker server application
then i have modifie unit WebModuleUnit1 as described and created unit MyControllerU as described 

i have added dependecies in the Library Path  
C:\DMVC\sources\
C:\DMVC\lib\dmustache\
C:\DMVC\lib\loggerpro\

when i try to compile my project i still have this error:
[dcc32 Erreur fatale] MVCFramework.pas(85): F2613 Unité 'Swag.Doc' non trouvée.
translation : [dcc32 Fatal error] MVCFramework.pas (85): F2613 Unit 'Swag.Doc' not found.

**Comment by danieleteti** [comment]
That guide is very old.
Add `C:\DMVC\lib\swagdoc\Source\` is your lib paths
