### ISSUE TITLE
Installation error (Tryed D10.3.3 and D10.4)

### ISSUE THREAD

**Issue by CiceroBillo** [danieleteti/delphimvcframework#394]
Delphi Rio 10.3.3

[dcc32 Error] MVCFramework.SQLGenerators.Firebird.pas(72): E2037 Declaration of 'CreateSQLWhereByRQL' differs from previous declaration

**Comment by danieleteti** [comment]
Please, use the official release not the repository clone (if you don't plan to controbute to the project).
That change has been made just 2 hors ago and is in the test phase and works.

**Comment by CiceroBillo** [comment]
Ok. Thank's.

**Comment by danieleteti** [comment]
However, now also the repo is aligned. If you want just pull from the repo and retest. In the future just use the released version :-)

**Comment by CiceroBillo** [comment]
Grazie mille.

**Comment by danieleteti** [comment]
Prego :-)
