### ISSUE TITLE
Error Install

### ISSUE THREAD

**Issue by allancmello** [danieleteti/delphimvcframework#395]
Erro install MVCFramework:

[dcc32 Hint] MVCFramework.Commons.pas(1027): H2164 Variable 'S' is declared but never used in 'TMVCStringDictionary.ToString'
[dcc32 Warning] dmvcframeworkRT.dpk(143): W1033 Unit 'Web.WebBroker' implicitly imported into package 'dmvcframeworkRT'
[dcc32 Warning] dmvcframeworkRT.dpk(143): W1033 Unit 'IdHTTPWebBrokerBridge' implicitly imported into package 'dmvcframeworkRT'
[dcc32 Error] E2223 $DENYPACKAGEUNIT 'Web.WebBroker' cannot be put into a package

RAD Studio 10.3.3

**Comment by danieleteti** [comment]
Thank you for your issue, however this is the repo version. If you just want to use the framework, please use the released version and not the development repo.

**Comment by danieleteti** [comment]
However, now it should work also the repo version
