### ISSUE TITLE
 New Content-Encoding validation

### ISSUE THREAD

**Issue by ThiagoACousseau** [danieleteti/delphimvcframework#397]
After upgrading from version 3.0 to 3.2 the consumption of a third-party WS is not being possible, due to the "Content-Encoding not supported [UTF-8]" validation, this validation occurs in MVCFramework.RESTClient on line 1393. Attached is the return WS.

[lista.txt](https://github.com/danieleteti/delphimvcframework/files/4820809/lista.txt)

**Comment by danieleteti** [comment]
Can you provide a public endpoint (or a self contained web service) which reproduce the problem?

**Comment by balenaultra** [comment]
Hi @danieleteti , same problem here.

Endpoint 187.86.54.241:8181
Login ultra
Password estac2ul

full request http://ultrasistemas.no-ip.biz:8181/boletos/lista?cnpj=82.214.834/0001-64,82.214.834/0001-64,35.256.799/0001-66

In postman we got resuts.

For now, only added this.
![image](https://user-images.githubusercontent.com/7242261/174595185-66d3d29a-29f7-43c9-bad4-cb7dbefc9442.png)
on `MVCFramework.RESTClient.Indy`
