### ISSUE TITLE
Extending TMVCStaticFilesMiddleware for dynamic generated content

### ISSUE THREAD

**Issue by landrix** [danieleteti/delphimvcframework#398]
I want to deliver dynamically ("semi-static" :) ) generated ics files (CalDAV) on request. 

Is TMVCStaticFilesMiddleware a good starting point for adjustments? Or is there a more suitable middleware for this thing?

**Comment by danieleteti** [comment]
Hi, Why don't use a controller with the proper MVCProduces attribute?

**Comment by landrix** [comment]
OK

```
  [MVCPath('/appointments')]
  TControllerAppointments = class(TMVCController)
    [MVCProduces('text/calendar','')]
    [MVCHttpMethod([httpGET])]
    [MVCPath('/ical/($username)')]
    procedure GetICalAppointments(CTX: TWebContext);
  end;
```

and

```
procedure TControllerAppointments.GetICalAppointments(CTX: TWebContext);
var
  hstrl : TStringList;
begin
  hstrl := TStringList.Create;
  hstrl.LoadFromFile('d:\downloads\myevents.ics',TEncoding.ANSI);
  Ctx.Response.SetCustomHeader('ETag','3cd-5a8e76ac1edc7');
  Render(Trim(hstrl.Text));
  hstrl.Free;
end;
```

produce not the same response like a direct call on www.mydomain.com/myevents.ics. It's not accepted as WebCal-Response.

I have to take a closer look at that. You can close this issue if you want.

**Comment by danieleteti** [comment]
OK, keep me informed.
