### ISSUE TITLE
missed code

### ISSUE THREAD

**Issue by KrIvanov** [danieleteti/delphimvcframework#40]
I didn't find dmvcframework.inc from MVCFramework.Commons . Where must it be?

Also it can not be compiled for now. There is also Error in 

function B64Encode(const Value: String): String;
overload
// var
// lB64: TBase64Encoding;
begin
  Result := TIdEncoderMIME.EncodeString(Value);

Suppose after overload must be ';'

**Comment by danieleteti** [comment]
Fixed. Pull the repo
