### ISSUE TITLE
More simple short description of delphimvcframework

### ISSUE THREAD

**Issue by zaher** [danieleteti/delphimvcframework#400]
First few  lines of README should explain what really is delphimvcframework to all readers, delphi, pascal, c++ or even non developers/programmers.

**Comment by danieleteti** [comment]
Nice observation. The project's "About" says: "DMVCFramework (for short) is a popular and powerful framework for web solution in Delphi. Supports RESTful and JSON-RPC APIs development."

It should be enough?

**Comment by zaher** [comment]
No,
Is it work behind web servers as module? Apache, ISS or it is own webserver?
Is support html templates, 
Is it easy to generate web pages or just RESTfull?
etc

**Comment by danieleteti** [comment]
All these features are mentioned in the features list. Do yo think they are not enough visible?
