### ISSUE TITLE
Add Possibility to change Table name in ActiveRecord

### ISSUE THREAD

**Issue by ads69** [danieleteti/delphimvcframework#401]
Hi,
For some cases it could be interresting to be able to change the table name of an TMVCActiveRecord at runtime.
Here's the 2 cases that I have found 

- More that one table use the same structure so you can use the same TMVCActiveRecord to update/read it.
- The Table used can have different names on different databases.

That is something that I have already implemented in my own use .
in MVCFramework.ActiveRecord in  TMVCActiveRecord = class 
in Public section
`Procedure SetTableName(Value: String);`

Then
`Procedure TMVCActiveRecord.SetTableName(Value: String);
Begin
  fTableName := Value;
End;`

Best regards
Armindo

**Comment by danieleteti** [comment]
Thank you. Added such support and related unit tests

**Comment by renaneustaquio** [comment]
foi adicionado a propriedade tablename, porem ela está sendo serializada no json, por favor adicionar MVCDoNotSerialize
