### ISSUE TITLE
Problem in Swagger in latest versions

### ISSUE THREAD

**Issue by ads69** [danieleteti/delphimvcframework#402]
Hi,
I see a problem in the swagger page that appears since the last versions.
If I try the SwaggerDoc sample it uses the localhost as URL (http://localhost:8080/swagger/index.html) on my PC, no problem appear on the page.
Now I check my IP and replace the localhost url by : http://192.168.100.126:8080/swagger/index.html
on the bottom on the page I see an error, the swagger itself is fully fonctionnal but this error appears.
Same problem occurs of course if you launch the server on one PC and you try to acces the Swagger using the server IP from another PC.
Best regards

Armindo
![localhost](https://user-images.githubusercontent.com/15327138/86340845-cfa28c80-bc55-11ea-981a-f4f8b0a3db9a.png)
![IP](https://user-images.githubusercontent.com/15327138/86340852-d3ceaa00-bc55-11ea-89b1-8a150ce5f108.png)

**Comment by joaoduarte19** [comment]
I'll check this out ASAP.

**Comment by joaoduarte19** [comment]
In the latest versions of the swagger UI there is an online JSON Schema validator. When you enter your local IP it tries to access it but cannot because it is not a public IP. To remove this message, I disabled this validation.

Fixed in commit b1bae8b736dce4597146be09850ca801fc6977f2
