### ISSUE TITLE
Example SSLSample with xe 10.4 is only working with port 443.

### ISSUE THREAD

**Issue by tbegsr** [danieleteti/delphimvcframework#403]
The example SSLSample failed if you use a port diffrent then 443 with Exception bei $00007FFFF3A03E49. Exception-Klasse EIdHTTPErrorParsingCommand 'Error in parsing command.'. Prozess SSLSample.exe (36400)
if you use Delphi XE10.4

 LServer.OnQuerySSLPort := SSLHelper.QuerySSLPort; is needed if you use on other port then 443

// JCL_DEBUG_EXPERT_GENERATEJDBG OFF
// JCL_DEBUG_EXPERT_INSERTJDBG OFF
// JCL_DEBUG_EXPERT_DELETEMAPFILE OFF
program SSLSample;
{$APPTYPE CONSOLE}

uses
  System.SysUtils,
  IdHTTPWebBrokerBridge,
  IdSSLOpenSSL,
  System.IOUtils,
  Web.WebReq,
  Web.HTTPApp,
  Web.WebBroker,
  WebModuleUnit1 in 'WebModuleUnit1.pas' {WebModule1: TWebModule} ,
  MyControllerU in 'MyControllerU.pas',
  MyObjectsU in 'MyObjectsU.pas';

{$R *.res}

type
  TGetSSLPassword = class
    procedure OnGetSSLPassword(var APassword: {$IF CompilerVersion < 27}AnsiString{$ELSE}string{$ENDIF});
  end;

type
  TSSLHelper = class
  // This helper class is neccessary to set ssl true
  // as it defaults to false on non standard ssl ports
  procedure QuerySSLPort(APort: Word; var VUseSSL: boolean);
end;

procedure TGetSSLPassword.OnGetSSLPassword(var APassword: {$IF CompilerVersion < 27}AnsiString{$ELSE}string{$ENDIF});
begin
  APassword := '';
end;

procedure TSSLHelper.QuerySSLPort(APort: Word; var VUseSSL: boolean);
begin
  VUseSSL := true;
end;

procedure RunServer(APort: Integer);
var
  LServer: TIdHTTPWebBrokerBridge;
  LGetSSLPassword: TGetSSLPassword;
  LIOHandleSSL: TIdServerIOHandlerSSLOpenSSL;
  LSSLHelper: TSSLHelper;
begin
  Writeln(Format('Starting DMVCFramework HTTPS Server or port %d', [APort]));
  LGetSSLPassword := nil;
  LSSLHelper := nil;
  LServer := TIdHTTPWebBrokerBridge.Create(nil);
  try
    LGetSSLPassword := TGetSSLPassword.Create;
    LIOHandleSSL := TIdServerIOHandlerSSLOpenSSL.Create(LServer);
    LIOHandleSSL.SSLOptions.CertFile := 'cacert.pem';
    LIOHandleSSL.SSLOptions.RootCertFile := '';
    LIOHandleSSL.SSLOptions.KeyFile := 'privkey.pem';
    LIOHandleSSL.OnGetPassword := LGetSSLPassword.OnGetSSLPassword;
    LServer.IOHandler := LIOHandleSSL;
    LServer.DefaultPort := APort;
    LServer.OnQuerySSLPort := LSSLHelper.QuerySSLPort;

    LServer.Active := True;
    Writeln('Press RETURN to stop the server');
    ReadLn;
  finally
    LServer.Free;
    LGetSSLPassword.Free;
  end;
end;

const
  OPENSSL_LIBS: array of string = ['libeay32.dll', 'ssleay32.dll'];

procedure CheckOPENSSLLibs;
var
  lOpenSSLLib: String;
begin
  // Just a check for
  for lOpenSSLLib in OPENSSL_LIBS do
  begin
    Write('Checking ', lOpenSSLLib, '...');
    if not TFile.Exists(lOpenSSLLib) then
      raise Exception.CreateFmt('Required OPENSSL library not found in the exe folder: %s' + sLineBreak +
        'Download INDY compatible OpenSSL Libraries from http://indy.fulgan.com/SSL/', [lOpenSSLLib]);
    Writeln('OK');
  end;
end;

begin
  CheckOPENSSLLibs;
  try
    if WebRequestHandler <> nil then
      WebRequestHandler.WebModuleClass := WebModuleClass;
    RunServer(4443 {443} { standard https port } );
  except
    on E: Exception do
      Writeln(E.ClassName, ': ', E.Message);
  end

end.

**Comment by landrix** [comment]
any news on this?

**Comment by landrix** [comment]
ok, here is the right answer
https://stackoverflow.com/questions/62068537/delphi-indy-ssl-error-after-migrating-to-10-4-sydney

i've added the following to MVCFramework.Server.Impl.pas

```
  TMVCListener = class(TInterfacedObject, IMVCListener)
  private
    ....
    procedure QuerySSLPort(APort: Word; var VUseSSL: boolean);

...
    FBridge.IOHandler := FBridgeSSLHandler;
    FBridge.OnQuerySSLPort := QuerySSLPort;
  end;
end;

procedure TMVCListener.QuerySSLPort(APort: Word; var VUseSSL: boolean);
begin
  VUseSSL := true;
end;

```
for custom TIdHTTPWebBrokerBridge you need to set TIdHTTPWebBrokerBridge.OnQuerySSLPort the same way.

**Comment by landrix** [comment]
**facepalm** the first post give the answer allready

**Comment by landrix** [comment]
i would say, you can close this issue
