### ISSUE TITLE
MVCFramework Warnings - W1025 Unsupported language feature: 'class constructor'

### ISSUE THREAD

**Issue by marcelojaloto** [danieleteti/delphimvcframework#407]
Warnings List:

![image](https://user-images.githubusercontent.com/20048296/89131442-362ffa00-d4e3-11ea-9b7f-8e86ea724b2b.png)

Solution in a unit for example:

![image](https://user-images.githubusercontent.com/20048296/89131490-9757cd80-d4e3-11ea-8f1e-53e210ad3012.png)

**Comment by danieleteti** [comment]
Sorry, that is not a solution. `class constructor` are very thifferent thigs of plain constructors.
It seems a spourious error, we need to investigate.
