### ISSUE TITLE
Add docExpansion parameter for Swagger

### ISSUE THREAD

**Issue by ads69** [danieleteti/delphimvcframework#408]
Hi,
My swagger is becoming bigger and Bigger and it's becoming quite hard to navigate to all Models.
Any plan to add the docExpansion property for Swagger ?
Like [here](https://github.com/swagger-api/swagger-ui/issues/3088)

Best regards

Armindo

**Comment by joaoduarte19** [comment]
This is a setting that must be entered into the Swagger UI distribution files.
You must open the [index.html](https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html) of the swagger UI files and add `docExpansion: 'none'`:
```javascript
    window.onload = function() {
      // Begin Swagger UI call region
      const ui = SwaggerUIBundle({
        url: "/api/swagger.json",
        dom_id: '#swagger-ui',
        docExpansion: 'none',
        validatorUrl : null,
        deepLinking: true,
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset
        ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ],
        layout: "StandaloneLayout"
      })
      // End Swagger UI call region

      window.ui = ui
    }
```

**Comment by ads69** [comment]
Ola Joao,
Great ! it works fine.
