### ISSUE TITLE
IsValidToken doesn't work with TJWTCheckableClaim.IssuedAt

### ISSUE THREAD

**Issue by Ravaut123** [danieleteti/delphimvcframework#41]
Add code to

procedure TMVCJwtAuthenticationMiddleware.OnBeforeRouting
...
            lJWT.Claims.Issuer := 'Delphi MVC Framework';
            lJWT.Claims.ExpirationTime := Now + OneHour; // todo: customize
            lJWT.Claims.NotBefore := Now - OneMinute * 5; // todo: customize
            **lJWT.Claims.IssuedAt := Now; //  Add this line todo: customize**
...

**Comment by danieleteti** [comment]
Closed by #a102909
