### ISSUE TITLE
Add a FieldbyName Method to TMVCActiveRecord

### ISSUE THREAD

**Issue by ads69** [danieleteti/delphimvcframework#411]
Hi,
It would be nice to have a FieldByName Method to a TMVCActiveRecord,
more possibilities to access the field and less dependent to the object properties.
Best regards

Armindo

**Comment by danieleteti** [comment]
Can you give more details on this? An example?

**Comment by ads69** [comment]
Something like

```
With TCustomer = class(TMVCActiveRecord)

lCustomer := TCustomer.Create;
  try
    lCustomer.FieldByName('CompanyName').Value := 'Google Inc.';
    lCustomer.FieldByName('City').Value := 'Montain View, CA';
    lCustomer.FieldByName('Note').Value := 'Hello there!';
    lCustomer.FieldByName(MyFieldNameTakenFromAnotherPartOfMyCode).Value := 'Dummy text';
    lCustomer.Insert;
    lID := lCustomer.FieldByName('ID').ValueOrDefault;
  finally
    lCustomer.Free;
  end;
```

The main advantage is that the fieldname used could be dynamic.

**Comment by danieleteti** [comment]
Interesting, however what should be returned by `FieldByName`? The string you pass in the method should be the attribute name, not the actual fieldname. `FieldByName` should returns a `TValue`.

**Comment by ads69** [comment]
Daniele, one point for you it should be the attribute name of course.
FieldByName should return a value.
I will post a modified example with a TValue.

**Comment by ads69** [comment]
With TCustomer = class(TMVCActiveRecord)

lCustomer := TCustomer.Create;
  try
    lCustomer.FieldByName('CompanyName').Value := TValue.From<NullableString > ('Google Inc.');
    lCustomer.FieldByName('City').Value := TValue.From<NullableString > ('Montain View, CA');
    lCustomer.FieldByName('Note').Value := TValue.From<NullableString > ('Hello there!');
    lCustomer.FieldByName(MyFieldNameTakenFromAnotherPartOfMyCode).Value := TValue.From<NullableString > ('Dummy text');
    lCustomer.Insert;
    lID := lCustomer.FieldByName('ID').Value.AsType<NullableString > ().Value ;
  finally
    lCustomer.Free;
  end;

**Comment by ads69** [comment]
```
With TCustomer = class(TMVCActiveRecord)

lCustomer := TCustomer.Create;
  try
    lCustomer.FieldByName('CompanyName').Value := TValue.From<NullableString > ('Google Inc.');
    lCustomer.FieldByName('City').Value := TValue.From<NullableString > ('Montain View, CA');
    lCustomer.FieldByName('Note').Value := TValue.From<NullableString > ('Hello there!');
    lCustomer.FieldByName(MyFieldNameTakenFromAnotherPartOfMyCode).Value := TValue.From<NullableString > ('Dummy text');
    lCustomer.Insert;
    lID := lCustomer.FieldByName('ID').Value.AsType<NullableString > ().Value ;
  finally
    lCustomer.Free;
  end;
```

**Comment by ads69** [comment]
But maybe it will better to call this method name "AttributeByName" instead of "FieldByName"

**Comment by danieleteti** [comment]
In the repo is now available some function preview of this request. Was something I would like to add too.

```delphi
procedure TMainForm.btnAttributesClick(Sender: TObject);
var
  lCustomer: TCustomer;
  lID: Integer;
begin
  Log('** Dynamic Properties Access');
  lCustomer := TCustomer.Create;
  try
    lCustomer.Attributes['CompanyName'] := 'Google Inc.';
    lCustomer.Attributes['City'] := 'Montain View, CA';
    lCustomer.Attributes['Note'] := 'Hello there!';
    lCustomer.Attributes['Code'] := 'XX123';
    lCustomer.Attributes['Rating'] := 3;
    lCustomer.Insert;
    lID := lCustomer.ID;
    Log('Just inserted Customer ' + lID.ToString);
  finally
    lCustomer.Free;
  end;

  lCustomer := TMVCActiveRecord.GetByPK<TCustomer>(lID);
  try
    Assert('Google Inc.' = lCustomer.Attributes['CompanyName'].AsType<NullableString>().Value);
    Assert('Montain View, CA' = lCustomer.Attributes['City'].AsString);
    Assert('XX123' = lCustomer.Attributes['Code'].AsType<NullableString>().Value);
    Assert('Hello there!' = lCustomer.Attributes['Note'].AsString);
    lCustomer.Update;
    Log('Just updated Customer ' + lID.ToString);
  finally
    lCustomer.Free;
  end;

  lCustomer := TCustomer.Create;
  try
    lCustomer.LoadByPK(lID);
    lCustomer.Code.Value := '9012';
    lCustomer.Update;
  finally
    lCustomer.Free;
  end;
end;
```

Check the activerecord_showcase sample.

**Comment by ads69** [comment]
Daniele, you're just amazing !
