### ISSUE TITLE
Add a Public PrimaryKey

### ISSUE THREAD

**Issue by ads69** [danieleteti/delphimvcframework#412]
Hi,
is it possible for you to add these properties to the public declarations of TMVCActiveRecord in the next release ?

```
[MVCDoNotSerialize]
Property PrimaryKeyFieldName: String Read fPrimaryKeyFieldName;
[MVCDoNotSerialize]
Property PrimaryKeyFieldType: TFieldType Read fPrimaryKeyFieldType;
[MVCDoNotSerialize]
Property PrimaryKey: TRTTIField Read fPrimaryKey;
```
it could be usefull for "Autofilling" it in some events for instance

```
Procedure TMyObject.OnBeforeInsert;
Var
  lValue: TValue;
  IsNullableType: Boolean;
  DID: String;
Begin
  Inherited;
  If PrimaryKeyFieldName.IsEmpty Then
    Exit;
  lValue := PrimaryKey.GetValue(Self);
  If (Not lValue.AsType<NullableString > ().HasValue) Or (lValue.AsType<NullableString > ().Value = '') Then
    Begin
      DID := GetUUID;
      lValue := TValue.From<NullableString > (DID);
      PrimaryKey.SetValue(Self, lValue);
    End;
End;

```
Thanks

**Comment by danieleteti** [comment]
Please check this https://github.com/danieleteti/delphimvcframework/blob/master/samples/activerecord_showcase/EntitiesU.pas#L521

Also, some properties you are using are already protected, there is no need to make them public.  If I correctly understood this should be enough. Let me know.

**Comment by ads69** [comment]
Daniele,
you're right this sample fits my needs.
Well done !

**Comment by danieleteti** [comment]
Great! :-)
