### ISSUE TITLE
#NewRestClient Not all TRESTClientAdapter tests are OK

### ISSUE THREAD

**Issue by danieleteti** [danieleteti/delphimvcframework#413]
@joaoduarte19 not all unit test for TRESTClientAdapter are OK. Seems that asych tests are failing.

**Comment by joaoduarte19** [comment]
I'll check that out. I think it's a compatibility issue. I believe you are using the delphi Sydney. I just realized that when using TEvent with Threads in delphi Sydney it doesn't work properly as it did in dephi Rio. I need to investigate if this is a bug in delphi Sydney or if there were any changes that affected it.

**Comment by renaneustaquio** [comment]
Estou com problema na função TMVCRESTClient.AddBody(aBodyStream: TStream; const aContentType: string;
  const aOwnsStream: Boolean): IMVCRESTClient e function TMVCRESTClient.AddQueryStringParam(const aName, aValue: string): IMVCRESTClient; pois não existe TRESTObjectOwnership no delphi 10.2
