### ISSUE TITLE
RootNode for BodyAsListOf

### ISSUE THREAD

**Issue by osaris** [danieleteti/delphimvcframework#415]
Hello,

I'm using new ```RootNode``` feature of ```BodyAs``` because my requests always contains two parts. It works well. I wonder if it will be possible to implement the same feature for ```BodyAsListOf``` or if it's something impossible by design ? If you think it's possible I can try to do a PR for this if needed.

Regards !

**Comment by osaris** [comment]
PR #416

**Comment by danieleteti** [comment]
Thank you. I'll check it ASAP.

**Comment by danieleteti** [comment]
Merged, thank you :-)
