### ISSUE TITLE
DMVC application using 20% Cpu all time

### ISSUE THREAD

**Issue by marcosbarreto** [danieleteti/delphimvcframework#417]
Hi guys,

I made a simple service application using DMVC. Is some moments the server machine is very slow then i look the process and i see que dmvc application is cosuming 20% to 25% of CPU. but i dont send neither command. 
Anyone more have this problem?

**Comment by danieleteti** [comment]
Hi, can you reproduce the problem with a self contained project? Never seen such behavior.

**Comment by marcosbarreto** [comment]
I dont know how reproduce or debug this problem daniele! can you give me a tip?

**Comment by danieleteti** [comment]
Create a copy of your application, then reproduce the problem.
Start to remove all the "functional" pieces and check if the problem goes away, if not what remains is the test we need to debug.

**Comment by danieleteti** [comment]
Any news?

**Comment by marcosbarreto** [comment]
I could not test yet.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em ter., 22 de set. de 2020 às 07:59, Daniele Teti <notifications@github.com>
escreveu:

**Comment by danieleteti** [comment]
Any news?
