### ISSUE TITLE
Problem with "list of lists" properties : not correct serialization

### ISSUE THREAD

**Issue by PascalDal** [danieleteti/delphimvcframework#418]
I just discover MVC Framework yesterday, and I met an error while trying to serialize my objects : 

"Exception Class Name : EMVCSerializationException
Exception Message    : Cannot serialize property or field "List" of TypeKind tkArray or tkDynArray."

I made some tests and this error occurs in following case :
1. I try to serialise class containing TArray<T> property with T inherits from "TObject" but this could be see as a implementation limit, not really a bug

2. I try to serialize class containg "TList<T2>" property with T2 inherits itself of TList<T>, and I think this is a bug/problem in current implementation (but not sure either since I maybe misuse the framework) :

AttributeToJsonDataValue handle objects and interface by detecting specials items (DataSet, JSON or list) in order to handle them specifically. For list objects (detected through "TDuckTypedList") your implementation call 'ObjectToJsonObject' for each list item instead of call if on complete list object. This mean each list item are serialized but not the list itself, unfortunatly, when you have a "list" property containg itself another list this will call 'ObjectToJsonObject' on this list and yry to serialize the entire list object instead of each item list. 
This fail in later call to method "AttributeToJsonDataValue" on internal property named "list" (from "TList<T>" class), because it is an array of any types and not only thoses supported in current implementation.

Perhaps a "recursive" implementation would allow to better manage these cases and to simplify this one ?

**Comment by danieleteti** [comment]
Hi, thank you for your detailed description. Can you create a small project which reproduce the cases?

**Comment by PascalDal** [comment]
Here is a small project : 
[TestMVC.zip](https://github.com/danieleteti/delphimvcframework/files/5193988/TestMVC.zip)

you can reproduce previous cases :

1/ Test array of objects
http://localhost:8080/api/getArrayOfObjects

2/ Test list of lists
http://localhost:8080/api/getListOfLists

**Comment by danieleteti** [comment]
The latest [commit in the repo](https://github.com/danieleteti/delphimvcframework/commit/bee7777f6ef7f34f331ca9743319e2274cfe3f74) fixes this issue. Can you deeply test it in your scenario?
