### ISSUE TITLE
Problem with StaticFilePath

### ISSUE THREAD

**Issue by ads69** [danieleteti/delphimvcframework#422]
Hi,
I have installed the last version and now I get this error 
` {"classname":"EMVCException","detailedmessage":"","apperrorcode":0,"items":[],"statuscode":500,"reasonstring":"","message":"[EMVCException] StaticFilePath cannot be \"/\"","data":null}`

no problem previously.

I use 

```
FEngine.AddMiddleware(TMVCStaticFilesMiddleware.Create(
    '/',         { StaticFilesPath }
    'www',     { DocumentRoot }
    'index.html' { IndexDocument - Before it was named fallbackresource }
    ));
```

Any idea ?

Best regards

**Comment by danieleteti** [comment]
Hi, it is a breaking change in 3.2.1-carbon (it is documented in the read me [here](https://github.com/danieleteti/delphimvcframework#321-carbon-repo-version-currently-in-beta)).
In the readme there is also the suggested solution (RedirectionController). 
Please, let me know if you can easily sole the problem using the proposed solution.

**Comment by ads69** [comment]
Thanks Daniele,
no need to register this RedirectionController ?

**Comment by danieleteti** [comment]
Yes, you have to register it as a normal controller. The sample linked in the readme does it.

**Comment by ads69** [comment]
It still doesn't work I will have to investigate more and let you know

**Comment by danieleteti** [comment]
The steps are:
- change static path from "/" to something else (e.g. "/static")
- register a "redirection controller" like the one in the sample which redirects "/" to "/static"

**Comment by ads69** [comment]
Up to now I used TControllersRegister.Instance.RegisterController in the Initialization of each controller instead of .AddController in the WebModule
I'm porting everything to .AddController to see if it works like that

**Comment by ads69** [comment]
I have managed it working with 
```
FEngine.AddMiddleware(TMVCStaticFilesMiddleware.Create(
    '/static',         { StaticFilesPath }
    'www',     { DocumentRoot }
    'index.html' { IndexDocument - Before it was named fallbackresource }
    ));
```

But the Swagger doesn't work anymore
Same problem with the Swaggerdoc sample

**Comment by danieleteti** [comment]
OK, I hope @joaoduarte19 can check the problem ASAP.

**Comment by joaoduarte19** [comment]
the swagger examples have been corrected. See the last commit.

**Comment by ads69** [comment]
Swagger sample works fine now also !
Thanks Daniele and Joao !
