### ISSUE TITLE
Error Building to 64-bit Linux Platform

### ISSUE THREAD

**Issue by maperx** [danieleteti/delphimvcframework#423]
[DCC Error] Json.Schema.Field.Objects.pas(94): E1019 For loop control variable must be simple local variable

Fixed that error, others appear.

**Comment by danieleteti** [comment]
I cannot reproduce the problem. Are you using the repo version?

**Comment by maperx** [comment]
I´m using the release version 3.2.0 boron, on Delphi Tokyo 10.2.3
File path: ...\dmvcframework_3_2_0_boron\lib\swagdoc\Source\Json.Schema.Field.Objects.pas

**Comment by danieleteti** [comment]
Can you try using the the repo version?

**Comment by maperx** [comment]
I just tried, same problem with release and repo version

**Comment by danieleteti** [comment]
Can you double check if there are 2+ copy of that unit in your paths?

In the current version line 94 is similar to the following:


![image](https://user-images.githubusercontent.com/1428644/93899992-31264480-fcf5-11ea-9596-9af868cbe66b.png)

**Comment by maperx** [comment]
Checked. There is only one, with the same lines of code.
![code](https://user-images.githubusercontent.com/1987152/93947314-c33c4600-fd11-11ea-98b2-d28505caae6a.jpg)
