### ISSUE TITLE
errror install on delphi seatle update 1

### ISSUE THREAD

**Issue by rioda78** [danieleteti/delphimvcframework#425]
environment delphi seatle 10 update 1, i get error when install dmvc 3.2 boron. error appear :

1. [dcc32 Error] MVCFramework.RESTClient.pas(1399): E2034 Too many actual parameters .
2. [dcc32 Error] MVCFramework.RESTClient.pas(1580): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
3. [dcc32 Error] MVCFramework.RESTClient.pas(1597): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
4. [dcc32 Error] MVCFramework.RESTClient.pas(1612): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments

error happen on code :

`    {$IF Defined(SeattleOrBetter)}
        lDecomp := TZDecompressionStream.Create(Result.Body, MVC_COMPRESSION_ZLIB_WINDOW_BITS[lCompressionType], False);
    {$ELSE}
        lDecomp := TZDecompressionStream.Create(Result.Body, MVC_COMPRESSION_ZLIB_WINDOW_BITS[lCompressionType]);
    {$ENDIF}`

parameter False need to remove to going further

**Comment by danieleteti** [comment]
Issue already fixed in the repo version. Will be available in 3.2.1-carbon.
