### ISSUE TITLE
Swagger.json file does not contain enumerations

### ISSUE THREAD

**Issue by blitt001** [danieleteti/delphimvcframework#427]
My swagger.json file does not contain the enumerations.
![afbeelding](https://user-images.githubusercontent.com/51137523/94268347-53120800-ff3d-11ea-816b-863556b01094.png)
Instead of the enumurations, it contains "Enum]"

**Comment by joaoduarte19** [comment]
This issue has been fixed.

**Comment by blitt001** [comment]
Thanks, working as expected now.
