### ISSUE TITLE
Feature request - support body for GET Request

### ISSUE THREAD

**Issue by arkadiusz-wolanski** [danieleteti/delphimvcframework#428]
Hi,

to support complex parameters for querying, it would be great if GET request would support possibility to send body data.

Best regards

Arek

**Comment by joaoduarte19** [comment]
It is not considered good practice to send data in the body of GET requests.
However, the DMVC server in StandAlone mode (using Indy) accepts GET requests with a body. For servers compiled as an Apache or ISAPI module it may not work, you would have to test these cases.

**Comment by arkadiusz-wolanski** [comment]
Joao,

the DMVC server works fine, but the RESTClient has not possibility to send the body in a GET Request, it's a Indy limitation. I have workaround for it in my projects, but it would by great if MVC would it also support. 
As far as I can see, the spec for HTTP protocol don't dismiss it : https://tools.ietf.org/html/rfc7231#page-24

Best regards

Arek

**Comment by joaoduarte19** [comment]
RESTClient Indy doesn't really support Get with body data.
We are working on a new RESTClient for DMVC and we will look into the possibility of adding body support to GET/DELETE requests.
A workaround to resolve this limitation is to make a POST request that allows you to send the body and use the `X-HTTP-Method-Override: GET` header for the server to interpret as a GET request.
