### ISSUE TITLE
Render with ObjectDict() for a Single Object with TMVCSerializationAction

### ISSUE THREAD

**Issue by sonjli** [danieleteti/delphimvcframework#430]
Hello.
I don't know if this is a real issue so I explain my case:

I have a EntityProcessor that have to add some HATEOAS links to a Entity
**Case 1**: In GetEntites I do: 
```
var
   lEntities: TObjectList<TMacchinaUser>;
...
Renderer.Render(ObjectDict().Add('data', lEntities, RicettaEsplosaLink)) 
// RicettaEsplosaLink is a TMVCSerializationAction
```

**Case 2**: In GetEntity I do: 
```
var
   lEntities: TMacchinaUser;
...
Renderer.Render(ObjectDict().Add('data', lEntities, RicettaEsplosaLink)) as for GetEntities
// RicettaEsplosaLink is a TMVCSerializationAction

```
**In second case the rendered JSON is WITHOUT the links.**

After some debugging I think I found the "problem". I attach the  "_MVCFramework.Serializer.JsonDataObjects.pas_" with my edit **at line 573**.

I hope this can help.

Eddy
[MVCFramework.Serializer.JsonDataObjects.zip](https://github.com/danieleteti/delphimvcframework/files/5312271/MVCFramework.Serializer.JsonDataObjects.zip)

**Comment by danieleteti** [comment]
Thank you for your analysis.  I'll get into it ASAP.

**Comment by sonjli** [comment]
FYI
I don't use the form **Renderer.Render(200, lEntities, RicettaEsplosaLink)** (_Without ObjectDict()_) because i need the "data" object that surrounds the entity.

Thanks
Eddy

**Comment by danieleteti** [comment]
Patch integrated (with s small change). Thank you.
