### ISSUE TITLE
Overload Render for adding Json root

### ISSUE THREAD

**Issue by DelphiMan68** [danieleteti/delphimvcframework#431]
hello,
In many senarios we need a root key for json and I think It is a good idea for oveload render. In bellow example I will describe It.

Here is an action with result:

procedure TCustomerController.GetCustomers;
var
  lCustomers: TObjectList<TCustomers>;
begin
  lCustomers := TMVCActiveRecord.SelectRQL<TCustomers>('', 0);
  Render<TCustomers>(lCustomers);
end;

* Result:

{
        [{
            "code": "4432",
            "description": "PIZZA CARBONARA XL",
            "price": 8,
            "id": 1
        },
        {
            "code": "2334",
            "description": "PIZZA PEPPERONI AND MUSHROOMS",
            "price": 12,
            "id": 2
        }]
}

====================================
But in some cases we need to add a root key like "data"

*Idea: 
procedure TCustomerController.GetCustomers;
var
  lCustomers: TObjectList<TCustomers>;
begin
  lCustomers := TMVCActiveRecord.SelectRQL<TCustomers>('', 0);
  Render<TCustomers>(lCustomers, 'data');     <==== My Idea
end;

*Result:
{
    "data": [
        {
            "code": "4432",
            "description": "PIZZA CARBONARA XL",
            "price": 8,
            "id": 1
        },
        {
            "code": "2334",
            "description": "PIZZA PEPPERONI AND MUSHROOMS",
            "price": 12,
            "id": 2
        }]
}

Thanks :)

**Comment by DelphiMan68** [comment]
I fount the solution.

this line: 
Render<TCustomers>(lCustomers);

must be change to this:

Render(ObjectDict(False).Add('data', lCustomers));

**Comment by danieleteti** [comment]
Yes. It is such a good idea there is already there :-)
Thank you for your proposal.
