### ISSUE TITLE
Config[TMVCConfigKey.MaxEntitiesRecordCount] doesn't work

### ISSUE THREAD

**Issue by sonjli** [danieleteti/delphimvcframework#435]
Hello,
any value you put in Config[TMVCConfigKey.MaxEntitiesRecordCount], non changes in RQL max entities is done.
The problem is in `MVCFramework.ActiveRecord.InternalSelectRQL` where the parameter "`MaxRecordCount`" is not used.

The followin image shows my actual solution:
![Schermata da 2020-10-09 08-55-38](https://user-images.githubusercontent.com/623109/95553123-2f0af800-0a0e-11eb-887f-3c1603733502.png)

Thanks,
Eddy

**Comment by danieleteti** [comment]
Thank you, the fix is in the repo.
