### ISSUE TITLE
JSONDataValueToTValueParam bug (MVCFramework.JSONRPC.pas)

### ISSUE THREAD

**Issue by sf-spb** [danieleteti/delphimvcframework#443]
Correct:

tkInt64:
      begin
        if JSONDataValue.Typ = jdtInt then
        begin
          JSONRPCRequestParams.Add(JSONDataValue.IntValue, pdtInteger);
        end
        else
          if JSONDataValue.Typ = jdtULong then
        begin
          JSONRPCRequestParams.Add(JSONDataValue.ULongValue, pdtLongInteger);
        end
        else
          **_if JSONDataValue.Typ = jdtLong then
        begin
          JSONRPCRequestParams.Add(JSONDataValue.LongValue, pdtLongInteger);
        end_**
        else
        begin
          raise EMVCJSONRPCInvalidRequest.Create(BuildDeclaration(RTTIParameter));
        end;

      end;

**Comment by danieleteti** [comment]
Thank you
