### ISSUE TITLE
Possible problem with '/' in Controller with [MVCPath('/')]

### ISSUE THREAD

**Issue by TomsGoe** [danieleteti/delphimvcframework#444]
If you use the example "plainclient" and "plainserver" from the framework, you always get the error message "not found". It seems that the search for the controller implemented for the URL does not work correctly.
After swapping the blocks in MVCFramework.Router.pas the problem seems to be solved. I ask for verification.
![2020-10-29 13_02_26-jwtplainclient - RAD Studio 10 1 Berlin - MVCFramework Router](https://user-images.githubusercontent.com/73646105/97567654-137c8700-19e7-11eb-95aa-8f99668123fd.png)

**Comment by allanwolski** [comment]
I have the same issue here in master.

```
[MVCPath('/')]
TDocsController = class(TMVCController)
public
...
```
```
DelphiMVCFramework
HTTP 404: [EMVCException] Not Found
```
