### ISSUE TITLE
TJSONBool delphi XE8

### ISSUE THREAD

**Issue by ronaldobim** [danieleteti/delphimvcframework#452]
No Delphi XE8 não existe a classe TJSONBool, existe alguma versão mais antiga que é recomendável usar  com XE8 ?

**Comment by joaoduarte19** [comment]
use the JSON classes of the [JsonDataObjects](https://github.com/danieleteti/delphimvcframework/blob/master/sources/JsonDataObjects.pas) unit instead. It will work on all versions of delphi from Delphi 2010, if I'm not mistaken.

All DMVC JSON serialization uses this class and I strongly recommend that you also use it, as it is much faster and simpler to use than the native JSON parser from delphi.

**Comment by danieleteti** [comment]
@ronaldobim What's the problem? DMVCFramework doesn't compile on XE8 or other?

**Comment by ronaldobim** [comment]
Good morning, delphi xe8 does not compile, but I have compiled with delphi comunity. Thanks De: Daniele TetiEnviado:sábado, 26 de dezembro de 2020 11:51Para: danieleteti/delphimvcframeworkCc:ronaldobim; MentionAssunto: Re: [danieleteti/delphimvcframework] TJSONBool delphi XE8 (#452) @ronaldobim What's the problem? DMVCFramework doesn't compile on XE8 or other?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
