### ISSUE TITLE
(Nullable) Attribute is not get swagger info

### ISSUE THREAD

**Issue by seabig6** [danieleteti/delphimvcframework#453]
[MVCSwagJSONSchemaField('customer_name', 'Customer Name', True, False)]
property CustomerName: string read FCustomerName write FCustomerName;
There is ok to swagger,
but
[MVCSwagJSONSchemaField('customer_name', 'Customer Name', True, False)]
property CustomerName: nullableString read FCustomerName write FCustomerName;
There is not showing in swagger.

**Comment by danieleteti** [comment]
@joaoduarte19 did you have any info about this?

**Comment by joaoduarte19** [comment]
I'll look this ASAP
