### ISSUE TITLE
Any suggest for RQL to filter with datetime in MySQL Database

### ISSUE THREAD

**Issue by seabig6** [danieleteti/delphimvcframework#454]
```
eq(<property>,<value>)
lt(<property>,<value>)
le(<property>,<value>)
gt(<property>,<value>)
ge(<property>,<value>)
ne(<property>,<value>)
and(<query>,<query>,...)
or(<query>,<query>,...)
sort(<+|-><property)
limit(count,start,maxCount)
contains(<property>,<value | expression>)
in(<property>,<array-of-values>) 
out(<property>,<array-of-values>)
```

Which can filter with datatime data type?  thanks!

**Comment by danieleteti** [comment]
I think I don't get the point. All these RQL functions should works on mysql. What you really need? Do you have a real case?

**Comment by seabig6** [comment]
I have a table :
DROP TABLE IF EXISTS business_quotation; 
CREATE TABLE business_quotation (
quotation_code VARCHAR(50) NOT NULL ,
quotation_date DATETIME NOT NULL)

How to set RQL for filter quotation_date?

ge(quotation_date, "2020-12-01")  ?

Thanks!

**Comment by danieleteti** [comment]
Yes, write date and times in ISO format

`ge(quotation_date, "2020-12-01")` is correct but the field is datetime, not date.

**Comment by seabig6** [comment]
I test OK.  Thanks a lot!
