### ISSUE TITLE
Support for HEAD command

### ISSUE THREAD

**Issue by jadeade** [danieleteti/delphimvcframework#455]
Hi all!

I am in need to use the head command in a project, and I implemented it with intention of send a patch. My implementation was working on 3.1.0 some weeks ago and the current code looked very similar, but seems that the code has changed drastically since then! I will attach the patch in case it's still useful

Do you have plans on adding this functionality? If not, I can try to implement it on the new code if I have a little of idle time, but I am not sure when I will be able to

Cheers

[head.zip](https://github.com/danieleteti/delphimvcframework/files/5689039/head.zip)

**Comment by joaoduarte19** [comment]
We recently added a new RESTClient. Yes we can add the HEAD method to the new RESTClient.
