### ISSUE TITLE
Hidden Param Attribute in Swagger

### ISSUE THREAD

**Issue by ads69** [danieleteti/delphimvcframework#457]
Hi,
in MVCSwagParamAttribute it would be interesting to have a Hidden property.
The goal here would be to force a param or header filled with the DefaultValue without displaying in the Swagger.
This would be interestng for instance to set custom params dedicated to the Swagger only.
Best regards

Armindo

**Comment by joaoduarte19** [comment]
Do you want some parameters to be hidden in Swagger?
Could you give an example of use to better understand?

**Comment by ads69** [comment]
Hi Joao,
For instance 
Usualy I have [MVCSwagParam(plHeader, 'MediaType', 'application/octet-stream', ptString, False, 'application/octet-stream')]
But since this header should always have it's default value, I would like to have it not displayable (and so not editable) in the Swagger using extra field (Called Hidden).
[MVCSwagParam(plHeader, 'MediaType', 'application/octet-stream', ptString, False, 'application/octet-stream', **TRUE**)]
Best regards

**Comment by ads69** [comment]
The other way too bypass this is to know in the controller that the request was done from the Swagger

**Comment by joaoduarte19** [comment]
I think that if it is a response header as described in version 3 the OpenAPI.
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#responseObject
I am studying to implement support for version 3 of OpenAPI (Swagger) soon.

**Comment by ads69** [comment]
It's a request header, the goal would be to force an header value if the request is done from the Swagger (and only from swagger)

**Comment by joaoduarte19** [comment]
> It's a request header, the goal would be to force an header value if the request is done from the Swagger (and only from swagger)

This really cannot be done. The request made by the Swagger UI interface is like any request made by another API client

**Comment by joaoduarte19** [comment]
> > It's a request header, the goal would be to force an header value if the request is done from the Swagger (and only from swagger)
> 
> This really cannot be done. The request made by the Swagger UI interface is like any request made by another API client

I believe that there is no more doubt about it, so we can close this issue.
