### ISSUE TITLE
Virtual methods in TMVCRESTClient

### ISSUE THREAD

**Issue by diegofgeremias** [danieleteti/delphimvcframework#458]
Whenever there is an error, my API returns a standard structure with the details of it. With this information I am able to create an exception in the client application so that this error is handled / displayed in the proper way.

However, with the current implementation of TMVCRESTClient, I cannot manage the return of the request, generating an exception if necessary in a generic way.

Is it possible to create some virtual methods right after executing the requests in the TMVCRESTClient class?

Something like that:

`(...)

protected
   DoAfterExecuteRequest (const aMethod: TMVCHTTPMethodType; const aResponse: IMVCRESTResponse); virtual;

(...)

function TMVCRESTClient.InternalExecuteRequest (const aMethod: TMVCHTTPMethodType): IMVCRESTResponse;
begin
   (...)

   Result: = TMVCRESTResponse.Create (lResponse);

   DoAfterExecuteRequest (aMethod, Result);
end;`

**Comment by joaoduarte19** [comment]
This is interesting.
 We can add interceptor methods before executing and after executing the request

**Comment by danieleteti** [comment]
I would go for a solution which doesn't require a new class for each "customization". What about if you need to change the implementation for different API version?
What about just generate a sort of "client side middleware"?
Something like

`lMVCClient.OnResponseCompleted.Add(procedure(Response: IHTTPResponse) begin ... end);`

or just simpler

`lMVCClient.OnResponseCompleted:= procedure(Response: IHTTPResponse) begin ... end;`


With this approach you can register a chain of processor for your data.

Available hooks could be

- OnBeforeSendRequest
- OnSendRequestCompleted
- OnResponseBegin
- OnResponseCompleted

**Comment by joaoduarte19** [comment]
In commit 112bf481014e111d0e40848699250ff4200a8f1b methods were added to intercept request processing.
Add Hooks using anonymous methods:
```delphi
FRESTClient    
  // Executes before send the request
  .SetBeforeRequestProc(
    procedure(aRequest: IHTTPRequest)
    begin      
      // Do something
    end
  )
  // Executes after send the request
  .SetRequestCompletedProc(
    procedure (aResponse: IHTTPResponse; var aHandled: Boolean)
    begin      
      // Do something
      // Set Handled to True to not process TMVCRESTResponse      
    end
  )
  // Executes after the response is processed.
  // If aHandled was set to True in RequestCompletedProc, this method will not be executed
  .SetResponseCompletedProc(
      procedure(aResponse: IMVCRESTResponse)
      begin
        // Do something
      end
    );
```
