### ISSUE TITLE
delphimvcframework without javascript?

### ISSUE THREAD

**Issue by Michael3006** [danieleteti/delphimvcframework#46]
Here is my question:
Can delphimvcframework be used, if the user has
deactivated javascript?
Or which parts could be used with deactivated 
javascript?
Thanks for your answer,
Michael

**Comment by danieleteti** [comment]
dmvc is not dependant from javascript. Your client can be in javascript, delphi, pure html, python or whatever. You can generate server side view and use dmvcframework as the good-old-php pages
