### ISSUE TITLE
How about insert and update with entity definitions?

### ISSUE THREAD

**Issue by seabig6** [danieleteti/delphimvcframework#460]
Is it possible to use different entity definitions for insert and update, or can define one entity to distinguish them by attribute definitions? Can be defined "MVCEntityFieldActionsAttribute" liking to "MVCEntityActionsAttribute"?

**Comment by danieleteti** [comment]
Probably you need an EntityProcessor. Did you tried with that?

**Comment by seabig6** [comment]
Where has a sample?

**Comment by seabig6** [comment]
Merry Christmas and happy new year！

**Comment by danieleteti** [comment]
@seabig6 Thank you.

The sample is `activerecord_restful_crud`. Check for *EntityProcessor*.

**Comment by seabig6** [comment]
I Got it, thanks!
