### ISSUE TITLE
Serialization enums

### ISSUE THREAD

**Issue by macielgoettms** [danieleteti/delphimvcframework#463]
Hi, I am updating a project with MVC in version 2 to 3, and I had the same situation reported in #232 , and I checked solution #264  which is excellent and flexible, but in my case it generates a lot of work, as I have hundreds of enums in this project and my client expects ordinal values ​​in everyone.

So I would like to suggest a change in the serializer, to make the default type configurable, in the serialization of enums, which is currently "estEnumName". We could use the class TMVCConfig which is already a parameter of the serializer constructor, to make this configuration.

If this change is relevant, I am willing to develop

Thanks

**Comment by danieleteti** [comment]
Yes, it make sense when migrate `pre-3.x` projects. If you provide a PR wich accomodate the problem I'll be happy to merge it. Please, provide unit tests and samples.

**Comment by macielgoettms** [comment]
Great, I'll do it, thanks

**Comment by danieleteti** [comment]
> So I would like to suggest a change in the serializer, to make the default type configurable, in the serialization of enums, which is currently "estEnumName". We could use the class TMVCConfig which is already a parameter of the serializer constructor, to 

Sorry, but considering the solution proposed, it would clutter the codebase and will force the serializer to access to TMVCConfig very often. Why just don't inherit from the current serializer and change the behaviour in the descendant class?

**Comment by macielgoettms** [comment]
You are right, I initially thought about this solution, but I was concerned about the future maintenance of the code, even so it is really a simpler way and that does not impact the base code, thanks.

**Comment by danieleteti** [comment]
> You are right, I initially thought about this solution, but I was concerned about the future maintenance of the code, even so it is really a simpler way and that does not impact the base code, thanks.

Good! If you need help to understand hot to change the default serializer, just ask.

DT
