### ISSUE TITLE
Feature Requets: Clone request / Clone response

### ISSUE THREAD

**Issue by gatosoft** [danieleteti/delphimvcframework#467]
Could a functionality be implemented to make a "clone request" / "clone response"?

The idea is to be able to make an interceptor and redirect a request, changing (if necessary) the URL, the parameters, the headers, etc.

Associated with the above, would it be possible to expose the headers as a list in the request / response?

thanks,

**Comment by joaoduarte19** [comment]
> Could a functionality be implemented to make a "clone request" / "clone response"?
> 
> The idea is to be able to make an interceptor and redirect a request, changing (if necessary) the URL, the parameters, the headers, etc.
> 

We can create a method to clone the request. However, cloning the response I don't think is necessary.

> Associated with the above, would it be possible to expose the headers as a list in the request / response?
> 
Headers are already exposed in the response

**Comment by gatosoft** [comment]
Ok, the headers are exposed in the request, but not as a list. I need to know exactly what header is coming to get it. It would be much better if they were as a list ...

My idea about the interceptor is a middleware, where I intercept the request (OnBeforeRoute), validate and redirect to another Microservice,

To do this, I create a new Request Client, copy (clone) infopath, headers, parameters, body, etc. and I call the other, and make some changes to him. When this new request makes the response, I copy (clone) it and make my convenient changes to return it to the original request,

It's like an ApiGateWay or a reverse proxy ...

I hope I have made myself understand

**Comment by fastbike** [comment]
I like the sound of this and could see it being used in current projects.
