### ISSUE TITLE
STOMP Extension enabled

### ISSUE THREAD

**Issue by KrIvanov** [danieleteti/delphimvcframework#47]
How long will it get, to be STOMP Extension refactored and again activated?

**Comment by danieleteti** [comment]
Are you already using it or are only interested in it?

**Comment by KrIvanov** [comment]
We have planed to use it eventually next month or later. I'm still not sure
with DMVC or not, but actually there is no other Berlin compatible Delphi
client to use.

2016-08-24 15:22 GMT+02:00 Daniele Teti <notifications@github.com>:

**Comment by danieleteti** [comment]
A more powerful extension will be presented at ITDevCon in ROME 6,7, Oct.

**Comment by danieleteti** [comment]
In 3.0 the stomp extension has been removed from the core engine. It will be available as sample.

**Comment by kayvanbree** [comment]
Has the STOMP sample been removed? Are there any plans regarding STOMP?

**Comment by sonjli** [comment]
Hi Daniele,
I am using STOMP protocol with RabbitMQ. But I have a lot of troubles with Rabbit complexity.
I would like to use Redis with PUBLISH\SUBSCRIBE. Is there any issue about this?
Do you think it is a robust technology inside Redis?

**Comment by danieleteti** [comment]
@sonjli IT is a completely different approach. Without a broader scope I cannot say if PUB/SUB it is a good replacement or not.

**Comment by danieleteti** [comment]
@kayvanbree The DelphiSTOMPClient is no more included in the dmvcframework (we want to keep the core light and fast as much is possibile). However the project itself is alive and kicking. https://github.com/danieleteti/delphistompclient

We'll publish the sample dmvcframeowork+stomp ASAP.

**Comment by sonjli** [comment]
It's quite simple: I have to publish a message in a "room". Until every client pop the message, then this message has not to be removed from the queue.

(ASAP-Thanks for the ASAP-sample ;) )
