### ISSUE TITLE
TMVCRESTClient - sAuthorization

### ISSUE THREAD

**Issue by cleveira** [danieleteti/delphimvcframework#470]
Constante "sAuthorization" não existe na versão do Delphi 10.2 Tokyo "MVCFramework.RESTClient".
Pelo que puder verificar essa constante nas versões mais novas esta na unit do Delphi "System.NetConsts".

![image](https://user-images.githubusercontent.com/26878600/105502155-e537dc00-5ca3-11eb-99cf-7be877d08e47.png)

**Comment by joaoduarte19** [comment]
I'll look at this ASAP.
