### ISSUE TITLE
Use JSON-RPC with custom non-HTTP transport

### ISSUE THREAD

**Issue by vldgeorgiev** [danieleteti/delphimvcframework#475]
Hello

For an existing project I want to use the JSON-RPC feature of the framework. However, my project is not a web one and the data transport is Windows named pipes, not HTTP.

The samples show making a descendant class from `TMVCJSONRPCController` and placing in it all the required RPC methods, with all the invoking handled from the TMVCEngine and RTTI. Which is very nice and without much effort.    
Is there a suitable way to do something similar (e.g. inherit from `TMVCJSONRPCController`), but manually pass it the raw JSON-RPC string data without a `TMVCEngine` and using HTTP? 

Or it would be better to just use the `TJSONRPCRequest/TJSONRPCResponse` classesas a wrapper for the JSON-RPC protocol, and do the method routing myself?

Thanks.

**Comment by danieleteti** [comment]
If you just need jsonrpc probably the best thing to do is to just use the classes and to the routing by yourself.
