### ISSUE TITLE
Problem with Stream and CRUD (MS SQL)

### ISSUE THREAD

**Issue by ads69** [danieleteti/delphimvcframework#477]
Hi,
I have done a test work based on the article_crud sample.
Everything works fine , except that I cannot retrieve data from Blob fields.

My table structure is like this :
`CREATE TABLE XWP (
  N_XWP int IDENTITY,
  ID_XWP varchar(50) NOT NULL CONSTRAINT DF_XWP_ID_XWP DEFAULT (newid()),
  N_Fabric int NOT NULL,
  ID_Fabric varchar(50) NOT NULL,
  DATA varbinary(max) NULL,
  Thumbnail varbinary(max) NULL,
  Picture varbinary(max) NULL,
  CONSTRAINT PK_XWP_N_XWP PRIMARY KEY CLUSTERED (N_XWP)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO`

the object class is like this
`[MVCNameCase(ncLowerCase)]
    TXWP = Class(TBaseBO)
  Private
    fN_Xwp: Integer {autoincrement};
    fID_Xwp: String;
    fN_Fabric: Integer;
    fID_Fabric: String;
    fData: TStream;
    fThumbnail: TStream;
    fPicture: TStream;

    Procedure SetN_Fabric(Const Value: Integer);
    Procedure SetID_Fabric(Const Value: String);
    Procedure SetN_Xwp(Const Value: Integer);
    Procedure SetID_Xwp(Const Value: String);
    Procedure SetData(Const Value: TStream);
    Procedure SetThumbnail(Const Value: TStream);
    Procedure SetPicture(Const Value: TStream);
  Public
    Constructor Create;
    Destructor Destroy; Override;
    Procedure CheckInsert; Override;
    Procedure CheckUpdate; Override;
    Procedure CheckDelete; Override;

    [MVCColumn('N_XWP')]
      Property N_Xwp: Integer Read fN_Xwp Write SetN_Xwp;
    [MVCColumn('ID_XWP')]
      Property ID_Xwp: String Read fID_Xwp Write SetID_Xwp;
    [MVCColumn('N_Fabric')]
      Property N_Fabric: Integer Read fN_Fabric Write SetN_Fabric;
    [MVCColumn('ID_Fabric')]
      Property ID_Fabric: String Read fID_Fabric Write SetID_Fabric;
    [MVCColumn('DATA')]
      Property Data: TStream Read fData Write fData;/
    [MVCColumn('Thumbnail')]
      Property Thumbnail: TStream Read fThumbnail Write fThumbnail;
    [MVCColumn('Picture')]
      Property Picture: TStream Read fPicture Write fPicture;

  End;`

the controller is like that
`procedure TXWPController.GetXWPS;
begin
  Render(
    ObjectDict().Add('data', GetXWPService.GetAll)
    );
end;`

and the service
`function TXWPService.GetAll: TObjectList<TXWP>;
begin
  FDM.TBL_XWP.Open('SELECT * FROM XWP ORDER BY N_XWP', []);
  Result := FDM.TBL_XWP.AsObjectList<TXWP>;
  FDM.TBL_XWP.Close;
end;`

And here's what I get doing a GET
`{
  "data": [
    {
      "n_xwp": 1,
      "id_xwp": "49D32B8E-EB05-4643-965B-9C022180E461",
      "n_fabric": 5,
      "id_fabric": "25575F0C-6CDD-40F6-86A4-E3EDB1D9486E",
      "data": "",
      "thumbnail": "",
      "picture": ""
    },
    {
      "n_xwp": 2,
      "id_xwp": "{453EB85D-5D33-41D1-B25E-E8CA6009C117}",
      "n_fabric": 6,
      "id_fabric": "{FEFF32C3-C64F-4617-B907-2F17A9B1A30F}",
      "data": "",
      "thumbnail": "",
      "picture": ""
    },
    {
      "n_xwp": 3,
      "id_xwp": "{3C1F02CE-756E-42C4-BF5F-F80B4011D510}",
      "n_fabric": 7,
      "id_fabric": "{70167252-3A8C-45BD-8BF5-A1E169CDB5C5}",
      "data": "",
      "thumbnail": "",
      "picture": ""
    },
    {
      "n_xwp": 4,
      "id_xwp": "{3E1D1EC3-3945-4FF2-8DCD-33C11A5AFE39}",
      "n_fabric": 8,
      "id_fabric": "{FC973686-9A2A-4708-AB1E-5B46887526CB}",
      "data": "",
      "thumbnail": "",
      "picture": ""
    }
  ]
}`

As you can see the varchar(max) field returns empty values

Any idea ?

Best regards

**Comment by danieleteti** [comment]
`MVCColumn` is deprecated, should be `MVCTableField`. Did you solve?
