### ISSUE TITLE
Second parameter of the "DateToISO8601" function should be configurable 

### ISSUE THREAD

**Issue by gatosoft** [danieleteti/delphimvcframework#479]
Hi. I have an issue in the serialization of a Dataset where the date field has the value: 12/30/1899, that is, the date zero.

The error is as follows:
"The given \" 30 \ / 12 \ / 1899 \ "local time is invalid (situated within the missing period prior to DST)."

This error occurs in the Berlin and Tokyo versions of Delphi when trying to use the function: DateToISO8601. ==> This Bug was fixed in version 10.4 (Sydney)

In DMVC, the error is generated when the function is executed: DateTimeToISOTimeStamp (located in: MVCFramework.Serializer.Commons)

The DateUtils.DateToISO8601 function fails on the line that calculates the Bias:
`Bias: = Trunc (TimeZone.GetUTCOffset (ADate) .Negate.TotalMinutes);`

I can solve it by modifying the source of MVCFramework.Serializer.Commons modifying the second parameter of the DateToISO8601 function, passing it from false to true, so that it does not calculate the UTC time difference.

Original: 
`Result: = DateToISO8601 (ADateTime, False);`
Modified: 
`Result: = DateToISO8601 (ADateTime, True);`

In my particular case, it would be useful if this second parameter could be changed according to the needs of the program. (CalculateUTC)

In fact, in the system I am working with, the required date format is this: 1899-12-30T00:00:00.000Z and not 1899-12-30T00:00:00.000-05:00

Then, Specifically, I suggest allowing to send this parameter as an option of serialization 

Greeting,

**Comment by joaoduarte19** [comment]
Recently in `MVCFramework.Serializer.Commons` the global variable `gLocalTimeStampAsUTC` has been added. When starting your application, set this variable to `True` to have the behavior you expect. Upgrade your repository to the latest version of the master branch to have access to this modification
