### ISSUE TITLE
Compatibility error for Delphi 10.1 and DMVC 3.2.1(carbon)

### ISSUE THREAD

**Issue by DelphiMan68** [danieleteti/delphimvcframework#480]
Hello,
I had some compatibility errors for using DMVC 3.2.1 version in Delphi 10.1 berlin.
three errors are located in "MVCFramework.ActiveRecord" unit.

for solving thise errors and fixing It follow below lines:

1- Change this code:
`lNullableTDateTime := TDateTime(aValue.AsExtended);`
to this:
`lNullableTDateTime := aValue.AsType<TDateTime>;`

2- Change this code:
`lNullableTDateTime := TDateTime(aValue.AsExtended);`
to this:
`lNullableTDate := aValue.AsType<TDate>;`

3- Change this code:
`lNullableTTime := TTime(aValue.AsExtended);`
to this:
`lNullableTTime := aValue.AsType<TTime>;`

**Comment by allanwolski** [comment]
Related #465

**Comment by danieleteti** [comment]
Is this issue closed?

**Comment by allanwolski** [comment]
Yes, it's working now. Thanks @danieleteti
