### ISSUE TITLE
Error adding a QueryStringParam of type Double

### ISSUE THREAD

**Issue by diegofgeremias** [danieleteti/delphimvcframework#484]
I believe it is just a mistake of the type Ctrl + C Ctrl + V, but the code today is as follows:

`function TMVCRESTClient.AddQueryStringParam(const aName: string; aValue: Double): IMVCRESTClient;`
`begin`
`  Result := AddPathParam(aName, aValue.ToString);`
`end;`

When in fact I believe it must be something like:

`function TMVCRESTClient.AddQueryStringParam(const aName: string; aValue: Double): IMVCRESTClient;`
`begin`
`  Result := AddQueryStringParam(aName, aValue.ToString);`
`end;`

**Comment by joaoduarte19** [comment]
I'll check ASAP
