### ISSUE TITLE
Support uploading big file

### ISSUE THREAD

**Issue by Beanv587** [danieleteti/delphimvcframework#487]
Hello

I am using Delphi 10.2 in the samples of fileupload.When I upload a Big file (≈600M),it will return out of memory。

Test browser: Chrome

My computer's memory is 16G, and the available memory is 60%.

![bbb](https://user-images.githubusercontent.com/30143806/109805528-82e8d880-7c5e-11eb-940a-3015b1169f6c.png)

**Comment by danieleteti** [comment]
Did you have any news about this? Did you find something?

**Comment by Beanv587** [comment]
@danieleteti 
Sorry, I just saw the message you sent.
In fact, When delphimvcframework accept post stream, it put the stream in memory for splicing...
This is not a good method, because once a large file is uploaded, the memory will overflow. I think the best way is to determine the content type. If it is multipart / form data, then create a temporary file to save the stream, and parse it.

**Comment by Beanv587** [comment]
I originally wanted to modify delphimvcframework by myself, so I closed this issues...but I found that the actual process is very difficult, I don't know where to start..

**Comment by landrix** [comment]
Any changes in the current version in this regard?
