### ISSUE TITLE
firebird sql generators error

### ISSUE THREAD

**Issue by drcrck** [danieleteti/delphimvcframework#489]
Hi Daniele, 
there a bug in firebird sql construct if there are fields with spaces.
it's all ok for select, but update or insert crash.
in MVCFramework.SQLGenerators.Firebird should be modified CreateInsertSQL and  CreateUpdateSQL
adding call to "GetFieldNameForSQL" and "GetParamNameForSQL" during sql creation.

row 107:  lSB.Append(**GetFieldNameForSQL**(lKeyValue.Value.FieldName) + ',');
row 121:  lSB.Append(':' + **GetParamNameForSQL**(lKeyValue.Value.FieldName) + ',');

and

row 186 :       Result := Result + GetFieldNameForSQL(lKeyValue.Value.FieldName) + ' = :' + GetParamNameForSQL(lKeyValue.Value.FieldName) + ',';

ciao :)

**Comment by danieleteti** [comment]
Hi. Currently fields with staces are not supported in FirebirdSQL, so this is the expected behaviour. 
We'll consider your suggestions to implement the support.

Thank you

Ciao :-)

**Comment by danieleteti** [comment]
The fix is in the repo. Please, test it and let me know.
