### ISSUE TITLE
Required package 'FireDAC' not found

### ISSUE THREAD

**Issue by thealgorithms10** [danieleteti/delphimvcframework#494]
I was re-setuping right now using the community edition of delphi..but seems i've got an error here when i was installing the DelphiMVC packages..it was Delphi 10.3.3 on community edition.

I've got here an error upon installing the DelphiMVC carbon 3.2.1 btw. Error is "Required package FireDAC not found" when i compile those packages

**Comment by thealgorithms10** [comment]
![DelphiMVC-error](https://user-images.githubusercontent.com/82137662/113978095-16bd4e00-9876-11eb-9600-8ad7543f3838.png)

**Comment by danieleteti** [comment]
Quite strange. Did you used the latest version? Can you do a test using the repository version?

**Comment by thealgorithms10** [comment]
I forgot how to I fix it but currently it was been fixed using Delphi Sydney
