### ISSUE TITLE
Unsupported FieldType (44) for field...

### ISSUE THREAD

**Issue by thealgorithms10** [danieleteti/delphimvcframework#496]
Good day,

Seems i received an error upon rendering the object. "Unsupported FieldType (44) for field..". I was using TinyInt datatype on our MySQL database. Other primary datatypes was work fine. 

I tried to declare it to Integer and Word but still not working.

See attached file. On the top left, that's my table on database (MySQL). Then the lower image, that's the object i created

![image](https://user-images.githubusercontent.com/82137662/114969884-ded48d00-9eab-11eb-9519-d0b0bb934152.png)

**Comment by atiweb** [comment]
Try using integer type

**Comment by danieleteti** [comment]
Has been fixed in the master branch. Please, let me know.
