### ISSUE TITLE
Can Implement Design Time ActiveRecord Dataset?

### ISSUE THREAD

**Issue by kitesoft** [danieleteti/delphimvcframework#497]
https://github.com/henriquewerlang/ORM4Delphi/blob/master/Delphi.ORM.DataSet.pas

it will be very RAD and help full to use activeRecord in VCL Application

    procedure OpenArray<T: class>(List: TArray<T>);
    procedure OpenClass<T: class>;
    procedure OpenList<T: class>(List: TList<T>);
    procedure OpenObject<T: class>(&Object: T);
    procedure OpenObjectArray(ObjectClass: TClass; List: TArray<TObject>);
    procedure Resync(Mode: TResyncMode); override;
    
thanks

**Comment by danieleteti** [comment]
Did you tried [ColumbusEgg4Delphi](https://bitbucket.org/bittimepro/columbusegg4delphi/src/master/)?
Check also [this Embarcadero webinar](https://blogs.embarcadero.com/mvvm-mvc-rad-architectures-with-columbusegg4delphi/) about it
