### ISSUE TITLE
Access violation when routing URl

### ISSUE THREAD

**Issue by mustsrghini** [danieleteti/delphimvcframework#498]
Hello,

How I can route URI like this

http://localhost:8080/api/v1/Prdnfo?=&Code=1&GetInfo=True.
MVCFramework gave access violation for this URL
But not for
http://localhost:8080/api/v1/PrdInfo?Code=1&Getinfo=True.
thsi the command header
($cmd) is Prdinfo and parameters are 
Code=1 and Getinfo=True
Declaration in controller :
[MVCPath('/($cmd)')]
 [MVCHTTPMethod([httpGET])]
 [MVCConsumes(TMVCMediaType.APPLICATION_JSON)]
  procedure FCmd(AContext: TWebcontext);
     Thanks

**Comment by danieleteti** [comment]
We cannot reproduce the problem. Can you give more info or a small and self-contained example?
