### ISSUE TITLE
Firedac Error with MEmo Size > 4000

### ISSUE THREAD

**Issue by ads69** [danieleteti/delphimvcframework#501]
Hello,
I have a strange Firedac (SQL Server) Error when trying to insert a record and writing to a varchar(max) (memo) field.
EFDException error raised, with message : 

> [FireDAC][Phys][ODBC]-345. Data too large for variable [CLE2]. Max len = [4000], actual len = [4192] Hint: set the TFDParam.Size to a greater value.

This Cle2 field is declared like this in the private section of the TMVCActiveRecord Class :
```
[MVCTableField('Cle2')]
FCle2: NullableString;
```

and like this in the public section
```
[MVCSwagJsonSchemaField(stString, 'Cle2', 'Cle2', True, False)]
Property Cle2: NullableString Read FCle2 Write FCle2;
```

no problem when the size is < 4000.

Any idea ?

Best regards

**Comment by LucasFFavero** [comment]
Did you manage to solve this problem?
