### ISSUE TITLE
Render Error With Guid Field Type

### ISSUE THREAD

**Issue by MuhammedReisBayraktar** [danieleteti/delphimvcframework#504]
Hi, 
When i render dataset i got a guid value error.

Product.Append;
Product.FieldByName('id').AsString := '4de2b512-1560-11eb-8a95-78929c63b084';
Product.FieldByName('name').AsString := 'Test Name';
Product.Post;

Render(Product, True, dstSingleRecord);

**Comment by danieleteti** [comment]
Hi. What error? What version?

**Comment by MuhammedReisBayraktar** [comment]
Hi,
'4de2b512-1560-11eb-8a95-78929c63b084' is not a valid GUID value

latest version.

**Comment by joaoduarte19** [comment]
> Hi,
> '4de2b512-1560-11eb-8a95-78929c63b084' is not a valid GUID value
> 
> latest version.

This is an exception generated by delphi when you assign your GUID string to your Dataset field.. 
For delphi a valid GUID string must be in the format `{4de2b512-1560-11eb-8a95-78929c63b084}`
So you should write your code like this:

```delphi
Product.Append;
Product.FieldByName('id').AsString := '{4de2b512-1560-11eb-8a95-78929c63b084}';
Product.FieldByName('name').AsString := 'Test Name';
Product.Post;

Render(Product, True, dstSingleRecord);
```

NOTE: The DMVC serializer can convert a GUID string without braces to a TGUID field normally
