### ISSUE TITLE
Request ContentType header is empty, cannot deserialize body (IIS)

### ISSUE THREAD

**Issue by gilsonwindsoft** [danieleteti/delphimvcframework#506]
Hello, 

When I receive a request on IIS across different servers, the request gets a blank ContentType.
If I read "CTX.Request.RawWebRequest.ContentType" property, the contentType is there.
But if I read "CTX.Request.ContentType" property, the contentType is empty.

Is it a bug? How can I solve this?

**Comment by danieleteti** [comment]
Which version are you using?

**Comment by danieleteti** [comment]
Check what happens in `TMVCWebRequest.DefineContentType` in unit `MVCFramework.pas`
