### ISSUE TITLE
I cannot install DMVCFramework E2003 Undeclared identifier: 'THTTPSecureProtocols'

### ISSUE THREAD

**Issue by ednardoh** [danieleteti/delphimvcframework#508]
Ao tentar instalar o DelphiMVCFramework no delphi XE10.2 Tokyo dá esse erro: [dcc32 Error] MVCFramework.RESTClient.Intf.pas(71): E2003 Undeclared identifier: 'THTTPSecureProtocols', alguém poderia me ajudar?

**Comment by danieleteti** [comment]
Please, use english.

**Comment by ednardoh** [comment]
When trying to install DelphiMVCFramework on delphi XE10.2 Tokyo gives this error: [dcc32 Error] MVCFramework.RESTClient.Intf.pas(71): E2003 Undeclared identifier: 'THTTPSecureProtocols', could someone help me?

**Comment by joaoduarte19** [comment]
I'll check this out ASAP.

**Comment by joaoduarte19** [comment]
THTTPSecureProtocols was added from delphi Tokyo Update 2. So I think you are using the first version of delphi Tokyo that didn't have THTTPSecureProtocols. I recommend that you update your delphi to Tokyo update 2 or 3, or even a newer version of Delphi.

See more about it at https://blog.marcocantu.com/blog/2018-january-http-improvements-1022.html

**Comment by ednardoh** [comment]
I understand thank you
