### ISSUE TITLE
ETag middleware emits blank response on IIS - with possible fix

### ISSUE THREAD

**Issue by fastbike** [danieleteti/delphimvcframework#512]
I've just added the ETag middleware to a DMVC project.

Wwhen I run a request via Postman on a local instance hosted with the TIdHTTPWebBrokerBridge it works fine.

However, when I recompile as an ISAPI and host under IIS 7.x the request returns a 200 status code but with no body. All the expected headers are returned.

I can replicate this in our app by commenting/uncommenting the registration of code for the middleware.
`FMVC.AddMiddleware(TMVCETagMiddleware.Create);`

To track what is going on I added some logging the middleware to track the position of the output stream around the hashing of the stream (line 104)

`2021-08-10 21:01:39:732  [TID       3332][DEBUG   ] Stream size is 7193
2021-08-10 21:01:39:732  [TID       3332][DEBUG   ] Strean Pos is 0
2021-08-10 21:01:39:733  [TID       3332][DEBUG   ] Running Hash
2021-08-10 21:01:39:733  [TID       3332][DEBUG   ] Stream Pos is 7193`

This shows that the stream is being advanced by the hashing and not reset => so the output has nothing to emit.
I made a simple fix to to reset the position after the hashing, i.e. add on line 105
`  lContentStream.Seek(0, soFromBeginning);`

Is this going to cause  any other problems ?

**Comment by joaoduarte19** [comment]
> This shows that the stream is being advanced by the hashing and not reset => so the output has nothing to emit.
> I made a simple fix to to reset the position after the hashing, i.e. add on line 105
> ` lContentStream.Seek(0, soFromBeginning);`
> 
> Is this going to cause any other problems ?

This is the solution to this problem. Does not cause other problems.

**Comment by fastbike** [comment]
Can I leave this fix to you?  I'm still working on getting my head around git.
