### ISSUE TITLE
Escaped "$" in MVCPath is now broken

### ISSUE THREAD

**Issue by fastbike** [danieleteti/delphimvcframework#513]
I've  updated to the latest version (3.2.2)

Our API had a path which is "Patient/$match"
We implemented this by escaping the $ so the MVCPath looks like
`[MVCPath('Patient/\$match')]`

The routing is now broken and returns a "Not Found" error

I have tracked this down to the MVCFramework.Router file, line 183
The original code was 
`  LRequestPathInfo := TIdURI.PathEncode(LRequestPathInfo);`
the new code is
` LRequestPathInfo := TNetEncoding.URL.EncodePath(LRequestPathInfo, [Ord('$')]);`

So the URL pathinfo is changed from "'Patient/$match" to "Patient/%24match"

I'm still thinking of the best fix - but am logging this in case someone else has a similar issue

**Comment by fastbike** [comment]
Also see issue #389 - Nitrogen has broken that work around.
A possible work around is to alter the MVCPath attribute on the affected methods so it reads
`[MVCPath('Patient/%24match')]`
However this makes the code unreadable and will also affect any documentation generated by the System controlloer and Swagger middleware.

I think the router code will need to be changed.

**Comment by fastbike** [comment]
A suggested fix is to change the router code in MVCFrameworh.Router at line 249
from
`              LMethodPath := MVCPathAttribute(LAtt).Path;`
to
`              LMethodPath := TNetEncoding.URL.EncodePath(MVCPathAttribute(LAtt).Path, [Ord('$')]);`

This will result in an apples-for-apples comparison in the IsCompatiblePath method.
Note I have not yet tested this suggestion.

**Comment by fastbike** [comment]
Suggested fix turns the MVCPath into '/%5C%24match' so that does not work !

**Comment by fastbike** [comment]
No code change required to the framework code :)
The fix is to remove the escaping from the MVCPath in the controller
So the controller code becomes
`    [MVCPath('/$match')]
    procedure MatchPatient(LocationId: string);`

**Comment by fastbike** [comment]
See last comment, escaped paths do NOT need to be escaped

**Comment by fastbike** [comment]
That last comment was incorrect. As well as removing the escaping in the controller, the Router code does need to be patched as comment https://github.com/danieleteti/delphimvcframework/issues/513#issuecomment-896259685

**Comment by danieleteti** [comment]
I did a small change to fix this issue and to change [this one](https://github.com/danieleteti/delphimvcframework/issues/492) which was closed. Let me know. There are 3 new unit test to test this issue. It should be fixed now, but let me know.

You should just escape the `$` symbol in the MVCPath like the following example:
`[MVCPath('/patient/\$match')]`

or

`[MVCPath('/patient/\$match/($par1)/($par2)')]`

Note, is escaped only the `$` which not define a parameter

**Comment by fastbike** [comment]
Great, I was just testing my suggested fix and saw that it broke the param placeholders in the MVCPath :(

**Comment by fastbike** [comment]
Thanks for the fast response. I can confirm this works as expected now.
