### ISSUE TITLE
AContext parameter in TMVCController methods is redundant

### ISSUE THREAD

**Issue by fastbike** [danieleteti/delphimvcframework#514]
I've noticed two of the TMVCController class methods include AContext as a parameter.
`    procedure OnBeforeAction(AContext: TWebContext; const AActionName: string;
      var AHandled: Boolean); virtual;`
`    procedure OnAfterAction(AContext: TWebContext; const AActionName: string); virtual;`

Given that Context is available as a class property - is this now redundant ?
If it is, will removing this be too much of a breaking change ?

On a related note the GetContext method raises an error where I think the logic of the text is 180 degrees from the intended message.
If the Context has not been assigned it says "Context already set on Classname.'
I think it should say "Context is not set on Classname.'

**Comment by danieleteti** [comment]
Yes the `AContext` param will be removed in 4.0.0-oxygen. It will break all the action filter methods, but a bit of cleaning is OK for a major version upgrade.

**Comment by fastbike** [comment]
Thanks Daniele

What about the incorrect text , have I read this correctly ?

**Comment by danieleteti** [comment]
Can you crete another issue just for the "AContext" parameter related issue?

**Comment by fastbike** [comment]
The context parameter has been raised  as https://github.com/danieleteti/delphimvcframework/issues/562
This issue now closed
