### ISSUE TITLE
Incompatibility with EurekaLog (Web.Win.IsapiHTTP unit)

### ISSUE THREAD

**Issue by DelphiMan68** [danieleteti/delphimvcframework#515]
Hello,
There is an incompatibility with eurekaLog. My suggestion is to change unit name from "Web.Win.IsapiHTTP" to "MVCFramework.Web.Win.IsapiHTTP"
![image](https://user-images.githubusercontent.com/10184622/129359844-6141ec7b-852d-4e8e-a887-29246aac6f25.png)

**Comment by danieleteti** [comment]
That's a well-known problem 
https://support.eurekalog.com/index.php?/Knowledgebase/Article/View/78/0/7x-eurekalogcore-contains-implicit-units-webwinisapihttp-or-it-contains-unit-webwinisapihttp-which-is-also-contained-in-package-eurekalogcore
