### ISSUE TITLE
Redis sample fix to 3.2.2 - nitrogen

### ISSUE THREAD

**Issue by Microcom-Bjarne** [danieleteti/delphimvcframework#518]
https://github.com/danieleteti/delphimvcframework/blob/a45cb1383eaffc9e81a836247643390acbb7b9b0/samples/outputcachewithredis/WebModuleU.pas#L44

MVC is readonly :-) so change the line to 
`Config['redis_connection_string'] := '127.0.0.1:6379'; `

and for the example to work another line is needed.
`Config['redis_connection_key'] := '';`
otherwise an exception is raised due to missing key from the cachecontroller.

**Comment by danieleteti** [comment]
Thank you
