### ISSUE TITLE
CustomLoggerSample - AnsiString 

### ISSUE THREAD

**Issue by Ravaut123** [danieleteti/delphimvcframework#52]
I can't compile the CustomLoggerSample demo

Error on lCookie.Name.ToLower. Here I'm getting that lCookie.Name is Ansistring.
I'm working with Seattle 10. Must I change settings?

To compile If changeed

    lCookie.Name.ToLower  into LowerCase(lCookie.Name)
-----------------------

`class procedure TMVCEngine.ClearSessionCookiesAlreadySet(
  aCookies: TCookieCollection);
var
  I: Integer;
  lSessCookieName: string;
  lCookie: TCookie;
begin
  lSessCookieName := TMVCConstants.SESSION_TOKEN_NAME.ToLower;
  I := 0;
  while true do
  begin
    if I = aCookies.Count then
      Break;
    lCookie := aCookies[I];
    if lCookie.Name.ToLower = lSessCookieName then
    begin
      aCookies.Delete(I);
    end
    else
      Inc(I);
  end;
end;`

**Comment by danieleteti** [comment]
Thank you
FIXED in the last push.
