### ISSUE TITLE
Sydney dmvframeworkRT104.bpl install fails

### ISSUE THREAD

**Issue by YvesVerm** [danieleteti/delphimvcframework#520]
The latest download Delphi Sydney dmvframeworkRT104.bpl installation fails:

- E2202 Required package 'loggerproRT' not found. Where is loggerproRT located? Do I need to install some extra packages or add some searchpath?

- the contains part refer to Delphi 20.0 Rio instead of Delphi 21.0 Sydney. e.g.Web.ApacheConst in 'c:\program files (x86)\embarcadero\studio\20.0\source\Internet\Web.ApacheConst.pas'

**Comment by danieleteti** [comment]
Please, follow the installation guide

**Comment by surendrasiddhi** [comment]
HI,
I am facing the same issue with latest vesion of DMVC framework neon version. My delphi is 10.4 sydney.
How to fix this issue ?
