### ISSUE TITLE
Powershell Invoke-RestMethod error 404

### ISSUE THREAD

**Issue by lcregencia** [danieleteti/delphimvcframework#521]
Our API works so far using Postman, browser and even command prompt http request. We are building some form of automation via Powershell however, when calling the Invoke-RestMethod in Powershell it causes an error 404. Any idea why? 

We have an ISAPI setup with our API on a Windows Server 2019, using DMVC (carbon)

PS C:\> Invoke-Restmethod -Uri "http://.../api/clients"
Invoke-Restmethod : DelphiMVCFramework
HTTP 404: [EMVCException] Not Found

also tried but same error: 
PS C:\> Invoke-Restmethod -Uri "http://.../api/clients" -Method GET

I think this may not be related to the framework itself but maybe someone experienced the same I would like to know what was your solution.

**Comment by danieleteti** [comment]
Please show me the header sent and the controller's action declaration

**Comment by lcregencia** [comment]
Daniele, you just gave me an idea what I'm missing :) I explicitly specify the headers in my Powershell Invoke-Restmethod call and now it is working! I just specified the accept and content-type

Awesome! Many thanks!
