### ISSUE TITLE
SQL Problem with TMVCActiveRecord.SelectDataSet

### ISSUE THREAD

**Issue by ads69** [danieleteti/delphimvcframework#522]
Hi,
I have a problem with this query (MS SQL) 
`script:= 'SELECT  SUM(A_Terme) AS Restant FROM ewapp.TB_SIGN_CREDIT_CLIENT WHERE ID = ?'
lDS := TMVCActiveRecord.SelectDataSet(script, [ID]);`
With this query I get 10 as Sum (wich is wrong).
Now doing this
`script := 'SELECT  SUM(A_Terme) AS Restant FROM ewapp.TB_SIGN_CREDIT_CLIENT WHERE ID = ''' + ID + ''''
` it gives me a sum of 9 wich is true.
I don't know if it is due the the Sum or the Parameter. (I think that the Sum is the problem since in the table the ID is always the same).
Best regards

Armindo

**Comment by danieleteti** [comment]
Quite strange. Could it depends by some implicit conversion done by the sql parser in MSSQL?
Try to specify the parameter type in the 3rd parameter of the `SelectDataset` method.

**Comment by ads69** [comment]
Hi Daniele,
Strange behaviour, this morning I have tryed to add the third parameter, and it worked fine.
I have then tryed with only the 2nd parameter (like the test that failed yesterday) and now it works again.
Very weird, I don't know if it could be a problem with my compiler but this morning it works . Strange.
So I close the issue.
Thanks
Armindo
