### ISSUE TITLE
Compiling dmvcframework_group.groupproj error and IDE auto kill

### ISSUE THREAD

**Issue by sonjli** [danieleteti/delphimvcframework#523]
When I open the project group "dmvcframework_group.groupproj" and compile I get this error
![Schermata da 2021-09-24 16-11-28](https://user-images.githubusercontent.com/623109/134688848-95db7a18-4b5b-4160-a091-ea0fc1c6fc7c.png)
:
![Schermata da 2021-09-24 16-11-39](https://user-images.githubusercontent.com/623109/134688874-4d975c8c-60a9-4cf4-8d1c-bc01a95832b3.png)

After this the IDE is in "panic" and when I try to close the group I get this
![Schermata da 2021-09-24 16-13-04](https://user-images.githubusercontent.com/623109/134689067-00a5b974-b326-420a-b8d7-1d85992f4212.png)

Infos:
Delphi 10.4.2 ent
Windows 10 20H2

Other infos:
I have LoggerPro installed prevoiusly form your repo.
If I try to remove loggerpro from group, the problem still exists.

Thanks
Eddy

**Comment by danieleteti** [comment]
We cannot reproduce the problem.

**Comment by sonjli** [comment]
How can I help to reproduce?

**Comment by danieleteti** [comment]
Any news on this?

**Comment by sonjli** [comment]
I didn't try anymore. For now you can close this. I will try soon with D11.1
Thanks
