### ISSUE TITLE
TJsonBytesStream.Realloc new data type NativeInt Delphi 11

### ISSUE THREAD

**Issue by charleslibano** [danieleteti/delphimvcframework#524]
In Delphi 11 Alexandria, the Realloc method of the component TMemoryStream on var NewCapacity now is NativeInt type.

Of course, in the override the TJsonBytesStream.Realloc method this variable will be of the NativeInt type and not LongInt as well.

Charles Libano.

**Comment by danieleteti** [comment]
Hi, the repo version already has this change and it works with Delphi11Alexandria.
ASAP will be released the 3.2.2-nitrogen
