### ISSUE TITLE
Unsupported FieldType (44) for field ..TINYINT datatype

### ISSUE THREAD

**Issue by thealgorithms10** [danieleteti/delphimvcframework#525]
Still can't support other datatypes in database (e.g. TINYINT) and it was tedious to adopt/change on database side since it was used as foreign key to other tables - many tables, and indexes. We can't create a systemwide changelog for it

**Comment by thealgorithms10** [comment]
![Uploading dmvc_concern.png…]()

**Comment by danieleteti** [comment]
Can you resend the screenshot? Also, please, indicate which version are you using.

**Comment by thealgorithms10** [comment]
Unsupported FieldType (44) for field. I'm was used in both 3.2.1 and 3.2.2. Concern was related on this fb post - https://www.facebook.com/groups/delphimvcframework/posts/3866846836731760

**Comment by danieleteti** [comment]
Can you provide more info? When the exception raises? Can you reproduce a small and reproducible example which shows the problem?

**Comment by thealgorithms10** [comment]
My apologies of not responding. Yet, still the concern is still existing. How do i reopen this post @danieleteti ?
