### ISSUE TITLE
Support Serialize/Deserialize sets

### ISSUE THREAD

**Issue by rshuck** [danieleteti/delphimvcframework#533]
Is it possible to add support to serialize/deserialise sets using TypInfo.SetToString and TypInfo.StringToSet?

**Comment by rshuck** [comment]
I have created a set serializer as below however I would like to decorate set properties to use this serializer rather than having to register the serializer for each set.  Does anyone know of such an attribute, such as MVCSerializer(TypeOf(TSetSerializer)]

```
procedure TSetSerializer.DeserializeAttribute(
  var AElementValue: TValue; const APropertyName: string;
  const ASerializerObject: TObject;
  const AAttributes: System.TArray<System.TCustomAttribute>);
begin
  var I:=StringToSet(AElementValue.TypeInfo,(ASerializerObject as TJsonObject).S[APropertyName]);
  TValue.Make(I,AElementValue.TypeInfo,AElementValue);
end;

procedure TSetSerializer.SerializeAttribute(
  const AElementValue: TValue; const APropertyName: string;
  const ASerializerObject: TObject;
  const AAttributes: System.TArray<System.TCustomAttribute>);
begin
  var B:=AllocMem(AElementValue.DataSize);
  AElementValue.ExtractRawData(B);
  var S:=SetToString(AElementValue.TypeInfo,B);
  FreeMem(B);
  (ASerializerObject as TJDOJSONObject).S[APropertyName]:=S;
end;

```

**Comment by rshuck** [comment]
I have updated my example to use an array to make it more friendly.

`procedure TSetSerializer.DeserializeAttribute(
  var AElementValue: TValue; const APropertyName: string;
  const ASerializerObject: TObject;
  const AAttributes: System.TArray<System.TCustomAttribute>);
begin
  var List:=TList<String>.Create;
  try
    for var V in (ASerializerObject as TJDOJSONArray) do
      List.Add(V.Value);

    var I:=StringToSet(AElementValue.TypeInfo,String.Join(',',List.ToArray) );
    TValue.Make(I,AElementValue.TypeInfo,AElementValue);
  finally
    List.Free;
  end;
end;

procedure TSetSerializer.SerializeAttribute(
  const AElementValue: TValue; const APropertyName: string;
  const ASerializerObject: TObject;
  const AAttributes: System.TArray<System.TCustomAttribute>);
begin
  var B:=AllocMem(AElementValue.DataSize);
  AElementValue.ExtractRawData(B);
  var S:=SetToString(AElementValue.TypeInfo,B);
  FreeMem(B);

  var A:=(ASerializerObject as TJDOJSONObject).A[APropertyName];
  for var Item in S.Split([',']) do
    A.Add(Item);
end;

`

**Comment by danieleteti** [comment]
Thank you. Could you provide also a sample project which use this custom type serializer?

**Comment by rshuck** [comment]
This example will deserialize a given object, deserialize it, reserialize it and return another object as well in a list.

```
curl --location --request POST 'http://localhost:8080/api' \
--header 'Content-Type: application/json' \
--data-raw '{
    "OptionSet":["option1","option2"]
}'
```

[SetTest.zip](https://github.com/danieleteti/delphimvcframework/files/7557379/SetTest.zip)

**Comment by danieleteti** [comment]
Thanks for your snippets. Changes have been merged into the dmvcframework core so that sets serialization doesn't require custom type serializars anymore.
