### ISSUE TITLE
Error handling in JSONRPC

### ISSUE THREAD

**Issue by fastbike** [danieleteti/delphimvcframework#538]
The Index method in the TMVCJSONRPCController has a try/except code block that handles all Exception types. 
This means that an application writer is prevented from writing a high level exception handling block that allows custom exception handling as in the normal RESTful mvc application, because all custom error classes are descendants of Exception so get caught.
For instance It prevents an application from being able to log nested exceptions, and also log the call stack using 3rd party code such as Eurekalog.

Issue #191  added a custom exception handler to address this issue for RESTful applications.
I propose a similar pattern for JSONRPC, which would be called from the exception block on the TMVCJSONRPCController.Index method.  
Useful objects to pass through are:
- the Exception object
- the JSON error response, so the application writer can add to the message or change the error code.
- the original WebContext, to provide access to request properties
- and optionally a boolean variable "ExceptionHandled" set to true, which stops the error from propogating, or could be set to false to reraise the exception.
Thoughts ?

**Comment by danieleteti** [comment]
Good point. Let me think a bit about it.

**Comment by fastbike** [comment]
Thanks, I'll prototype a change in the next few days.

**Comment by HealthOneNZ** [comment]
Will need to include some type of json unit in the core MVCFramework unit if we want to surface the error object - thoughts ?

**Comment by danieleteti** [comment]
Sorry to be late at reply. 
@HealthOneNZ Including some json related classes in `MVCFramework.pas` is not a problem. MVCFramework supports natively JSON-RPC so it makes sense to depends from some sort of JSON stuff; indeed currently `JsonDataObjects.pas` is included in `MVCFramework.pas`.
@fastbike do you have some news about this? I'm preparing the official 3.2.2-nitrogen release. If you have something ready we can add to the release with unit tests and will be included in 3.2.2-nitrogen; otherwise we should wait for the next release.

**Comment by fastbike** [comment]
I got as far as adding the following code, it does not yet deal with the JSON error object

```
(* new TProc type *)
  TMVCJSONRPCExceptionHandlerProc = reference to procedure(E: Exception;
     //ErrorObj: TMVCJSONObject;
    WebContext: TWebContext; var ExceptionHandled: Boolean);

  TMVCEngine = class(TComponent)
```

**Comment by fastbike** [comment]
If I change the signature of the Exception handler, I'll need to add a JSON unit to the uses clause in the MVCFramework.pas file.

This will then bind the whole library whatever library is used e.g. System.Json or JsonDataObjects

Do you have a preference or can this be better handled via conditional compilation ?

```
  TMVCJSONRPCExceptionHandlerProc = reference to procedure(E: Exception;
     ErrorObj: TJSONObject;  // what JSON library should this reference 
    WebContext: TWebContext; var ExceptionHandled: Boolean);
```

**Comment by danieleteti** [comment]
dmvcframework uses jsondataobject not system.json so it's ok to use jsondataobject

**Comment by danieleteti** [comment]
Why not pass only the relevant properties as string and integer?

**Comment by fastbike** [comment]
> Why not pass only the relevant properties as string and integer?
The object that is created within the JSONRPC controller encapsulates:
     RequestID, ErrorCode, ErrorMessage

If I pass these as individual params, then the framework will need to deal with any changes to them. Also by passing the JSON object, it allows the application developer to add fields to the object which can be used by the front end js developer.

Another alternative would be to pass the JsonObject as a var string, and then parse it back to the lJSONResp variable.

E.g. if the exception passes 
`	{"RequestID":1,"Error":{"Code":100,"ErrMessage":"something went wrong"}}`

then the application writer could change it to
`	{"RequestID":1,"Error":{"Code":100,"ErrMessage":"something went wrong"},"AdditionalInfo":"Some additional info for the front end"}'

This would then be sent back to the client. Apart from some loss of efficiency with the additional conversion from JsonObject to string and back, this would give flexibility, and decouple the main MVCFramework from any particular JSOn library.

What do you think ?

**Comment by fastbike** [comment]
I'll take a look at the linked in specification (thanks for the link)

**Comment by fastbike** [comment]
So I'm proposing to change signature of the anonymous procedure to
```
  TMVCJSONRPCExceptionHandlerProc = reference to procedure(E: Exception;
    (*SelectedController: TMVCController;*)
    WebContext: TWebContext;
    var ErrorObj: string;
    var ExceptionHandled: Boolean);
```
Still not sure if the Controller needs to be passed through though.

**Comment by fastbike** [comment]
Here's a patch file for the JSONRPC unit, the MVCFramework unit just has the changes as above (ext changed to txt to allow upload to github)


[MVCFramework.JSONRPC.pas.patch.txt](https://github.com/danieleteti/delphimvcframework/files/8354322/MVCFramework.JSONRPC.pas.patch.txt)

**Comment by fastbike** [comment]
I've tested this with some of our code, here's an example of the code in the webmodule
```
  FMVC.PublishObject(
    function: TObject
    begin
      result := TEventFunctions.Create;
    end, '/events',
    procedure(E: Exception; WebContext: TWebContext; var ErrorObj: string; var ExceptionHandled: Boolean)
    var
      Json: TJsonObject;
    begin
      json := TJsonObject.Parse(ErrorObj) as TJsonObject;
      json.O['error'].S['data'] := 'some additional stuff';
      ErrorObj := Json.ToJSON;

      LogExceptionMessages(E, WebContext);
      LogStackTrace(E, WebContext);
    end);
```
And by raising an exception in the TEventFunctions method I get the following back at the browser
```
{"jsonrpc":"2.0","id":1,"error":{"code":0,"message":"Error Message","data":"some additional stuff"}}
```

**Comment by danieleteti** [comment]
Passing a Json object (also as string) could break the protocol because user could not respect the errorobject specs. We need to pass a record by var or something else. Then the framework will recreate the error object using the provided data.

**Comment by fastbike** [comment]
I'd then have to declare the record in the main MVCFramework.pas file, which kind of pollutes that files with JsonRPC related structures.  So I'm not keen on that direction.

The specification  allows the optional "data" field to be either Primitive (i.e. string or number) or Structured such as a object or array. 
So this leads us to either use:
- a  string that can be parsed to json, 
- or a variant such as TJsonDataValueHelper but binds us to to a specific json library
- TValue which could hold string, integer or structured etc.

Using TValue would lead towards 
```
  TMVCJSONRPCExceptionHandlerProc = reference to procedure(E: Exception;
    WebContext: TWebContext;
    ErrorCode: Integer;
    ErrorMsg: string;
    var ErrorData: TValue;
    var ExceptionHandled: Boolean);
```

**Comment by danieleteti** [comment]
Yes, this could be an approach that I like. Another could be to limit the generic nature of data and define it as TMVCStringDictionary

**Comment by fastbike** [comment]
I'm not sure what a string dictionary would bring, when the spec says that "data" can be either Primitive or Structured.
For example the Etherium wiki shows the following returned data
```
{
    code: 3,
    message: 'Execution error',
    data: [{
        code: 102,
        message: 'Innsufficient gas'
    },
    {
        code: 103,
        message: 'Gas limit exceeded'
    }]
}
```
I'm not sure how you could do that with the dictionary.

**Comment by danieleteti** [comment]
Yes, that's true. A dictionary would simple to implement but not flexible as specs recommends.

**Comment by fastbike** [comment]
We could leave it as TValue and use xmldoc to link to the JSON-RPC spec ?

**Comment by danieleteti** [comment]
OK, let's go with the TValue and we'll see how it works.

**Comment by fastbike** [comment]
Ok I've got some code changes to implement this. 
I'm using a record that gets passed as a var parameter to the application code in the error handler.  This allows the error code to be changed (it is hard coded to 0 at the moment) and the application developer access to the message. 
The Data element is a TValue so this can be populated with a variety of types: I've tested it with a simple string and by assigning a TJSONObject.

So the relevant part of MVCFramework.pas looks like
```
  TMVCJSONRPCExceptionErrorObject = record
    Code: Integer;
    Msg: string;
    Data: TValue;
  end;

  TMVCJSONRPCExceptionHandlerProc = reference to procedure(E: Exception;
    (*SelectedController: TMVCController;*)
    WebContext: TWebContext;
    var ErrorObj: TMVCJSONRPCExceptionErrorObject;
    var ExceptionHandled: Boolean);
```
I've left the ref to the controller in there, commented out as it is YAGNI at this stage.

I'll make a diff file for the JsonRPC file changes and attach it to a separate post.

**Comment by fastbike** [comment]
Here's the patch for the MVCFramework.JSONRPC.pas. file

[MVCFramework.JSONRPC.pas.patch.txt](https://github.com/danieleteti/delphimvcframework/files/8358227/MVCFramework.JSONRPC.pas.patch.txt)

**Comment by fastbike** [comment]
I've done the following tests:

1. Assign a string to the Data field
```
...
    procedure(E: Exception; WebContext: TWebContext; var ErrObj:  TMVCJSONRPCExceptionErrorObject;
      var ExceptionHandled: Boolean)
    begin
      ErrObj.Data := 'more details';
...
```
which outputs
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"Error Message","data":"more details"}}
```
2. A custom class
```
  TMyclass = class
  private
    FSomeValue: string;
  public
    property SomeValue: string read FSomeValue write FSomeValue;
  end;
...
    procedure(E: Exception; WebContext: TWebContext; var ErrObj:  TMVCJSONRPCExceptionErrorObject;
      var ExceptionHandled: Boolean)
    var
      a: TMyclass;
    begin
      a := TMyclass.Create;
      a.SomeValue := 'abc';
      ErrObj.Data := a;
...
```
which outputs
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"Error Message","data":{"SomeValue":"abc"}}}
```

**Comment by danieleteti** [comment]
Thank David for you contribute. I merged your code and did some slight changes. Please, test from your POV and let me know. 
Check this example 
`C:\DEV\dmvcframework\samples\jsonrpc_with_published_objects\` (client and server).
The 3rd client tab contais the new calls

**Comment by fastbike** [comment]
Thanks for the refinement.  Although I'm getting an error when the Data object is freed, I'll look into it.
My publisher code looks like this
```
  FMVC.PublishObject(
    function: TObject
    begin
      result := TEventFunctions.Create;
    end, '/events',
    procedure(E: Exception; WebContext: TWebContext; var ErrInfo: TMVCJSONRPCExceptionErrorInfo; var ExceptionHandled: Boolean)
    var
      Extra: TJsonObject;
    begin
      (* some local functions
      LogExceptionMessages(E, WebContext);
      LogStackTrace(E, WebContext);
      *)
      // add a json object to the "data" field of the response
      Extra := TJsonObject.Create;
      Extra.S['extra'] := 'some extra data';
      ErrInfo.Data := Extra;
      ExceptionHandled := true;
    end);
```

**Comment by fastbike** [comment]
Here's a patch. As ownership (and then freeing) only happens when the ExceptionHandled is true, I've added that to the test. 

Also I think when the Data property of the TJSONRPCResponseError class is assigned (it calls SetData), then it should free any existing TObject, so the patch reflects that as well.

[MVCFramework.JSONRPC.pas.patch.txt](https://github.com/danieleteti/delphimvcframework/files/8392416/MVCFramework.JSONRPC.pas.patch.txt)

**Comment by danieleteti** [comment]
Merged your changes. Let me know.

**Comment by fastbike** [comment]
Thanks, looks like we have a solution :)

**Comment by danieleteti** [comment]
Thanks a lot for your support, David
