### ISSUE TITLE
TRESTClient : EConvertError with message ''$s/'

### ISSUE THREAD

**Issue by Ravaut123** [danieleteti/delphimvcframework#54]
If I use the TRESTClient and send to the server

   lResp := lClt.doGET('/users/search/username/%s', [self.edtUserName.Text]);

I get an error like: 
  raised exception class EConvertError with message ''$s/' is not a valid integer value'.

![stack](https://cloud.githubusercontent.com/assets/1968086/18818171/a6bfe8f0-8372-11e6-8bfc-9bb817dfd0a1.PNG)

But this work:

   lResp := lClt.doGET(Format('/users/search/username/%s', [self.edtUserName.Text]), []);

Any Idea what's the problem?

**Comment by danieleteti** [comment]
This code...
```delphi
lResp := lClt.doGET('/users/search/username/%s', [self.edtUserName.Text]);
```
Should looks like the following
```delphi
lResp := lClt.doGET('/users/search/username', [self.edtUserName.Text]);
```

This is not the same behaviour of the ```Format``` function, it just append the pieces passed in the square brackets.
