### ISSUE TITLE
Funny issue when using DMVC with Delphi 10.4.2 Comunity

### ISSUE THREAD

**Issue by nhantr** [danieleteti/delphimvcframework#540]
Hi all,

I'm using Delphi 10.4.2 Community and latest 3.2.1 DMVC Framework.

1. If I create project like this (i.e accept all default value, including name):
![](http://imagizer.imageshack.com/a/img922/8853/Wu8XOY.png)
 Then the project create successfully, the Project Explorer panel show two file: Unit1 (controller) and Unit2 (web module)
![](http://imagizer.imageshack.com/a/img922/37/w9A4nA.png)

2. If I set the name for WebModuleClass. i.e MyBlog
![](http://imagizer.imageshack.com/a/img923/4484/PSzOW4.png)
Then I got this error and this error repeat 3 times
![](http://imagizer.imageshack.com/a/img922/2014/3RX1iS.png)
![](http://imagizer.imageshack.com/a/img922/2656/LCQNiL.png)
![](http://imagizer.imageshack.com/a/img923/651/lu82qR.png)

After I clicked OK for 3 error messages, the second Unit (i.e the WebModule) is created.
![](http://imagizer.imageshack.com/a/img924/854/Jxo9xO.png)

However, it don't displayed on the Project Explorer panel. 
I can save this unit to a file, however, when I right-click to the Project Explorer - Add - Unit2.pas, I got the error message as above and this unit can't be added to project.

Do anyone got that issue like me?

**Comment by danieleteti** [comment]
Strange behavior.  I think you should put this on th FB group.
