### ISSUE TITLE
100% CPU usage in Docker container

### ISSUE THREAD

**Issue by barlone** [danieleteti/delphimvcframework#541]
I try to run MVCFramework-based app in Docker container. It runs but "eat" all CPUs res. Without Docker works fine. I`ve attach _docker stats_ and _htop_ output for minimal BasicDemo test.

![Screenshot 2022-01-05 180756](https://user-images.githubusercontent.com/5476275/148249899-a4105135-7a9c-4c54-a1d4-5671a5e7116f.png)

![Screenshot 2022-01-05 180400](https://user-images.githubusercontent.com/5476275/148249275-7cf5f86f-dad1-405b-8236-7db8de0a70a8.png)

**Comment by barlone** [comment]
I`ve found the problem - it is "REPL" loop:

   WriteLn('Write "quit" or "exit" to shutdown the server');
   repeat
     Write('# ');
      ...
   until false;

In docker it work incorrect. And also does not allow to correctly complete the program on command _docker stop_.
This workaround tested and fix problem:

uses
  ...
{$IFDEF LINUX}
  Posix.Signal,
{$ENDIF}
  ...;

{$IFDEF LINUX}
var
  SIGTERMfire: Boolean = false;

procedure HandleSignals(SigNum: Integer); cdecl;
begin
  if SigNum = SIGTERM then
      SIGTERMfire := true;
end;
{$ENDIF}

procedure RunServer(APort: Integer);
label
  _l0;
begin
...

{$IFDEF LINUX}
    if lStartupCommand = '--in-docker' then begin
      LogEvent(etEvent, 'Server runned in Docker mode');
      Signal(SIGTERM, HandleSignals);
      while not SIGTERMfire do
        Sleep(250);
      goto _l0;
    end;
{$ENDIF}

    WriteLn('Write "quit" or "exit" to shutdown the server');
    repeat
      Write('# ');
   ...
    until false;

_l0:
  finally
    LServer.Free;
  end;
end;
   
Application starts in container with --in-docker argument.

**Comment by fastbike** [comment]
Nice work. It would be good to get these hints and tips for running virtualised instances such as containers and azure functions written up somewhere.

**Comment by danieleteti** [comment]
Can you follow these istructions?

https://www.facebook.com/groups/delphimvcframework/permalink/4966140576802375/
