### ISSUE TITLE
Request.QueryParams with empty key

### ISSUE THREAD

**Issue by llodi-csw** [danieleteti/delphimvcframework#542]
If you are making a request with a query string like this:

`...?codice`

the `Request.QueryParams` dictionary will be created with only one pair<key,value> both empty.

I think the problem is in `TMVCWebRequest.GetQueryParams` .
Below you can see the value of `FWebRequest` related to the example:
![image](https://user-images.githubusercontent.com/68338731/156541499-3a50d1a9-d830-4570-9264-052fb97a1242.png)

is this a correct behavior?
IMHO In this example the object `Request.QueryParams` should be empty because there are no valid parameters (with '=') in the querystring.

**Comment by danieleteti** [comment]
Related RFC is not clear about the query string internal format.
Some info here: https://stackoverflow.com/questions/4557387/is-a-url-query-parameter-valid-if-it-has-no-value
However, DMVCFramework should thread 
`?codice`

as if it were

`?codice=`

So there should be a param `codice` with an empty value. 
I think this is a bug. I'll give a look ASAP
