### ISSUE TITLE
EZDecompressionError - 'data error'

### ISSUE THREAD

**Issue by balenaultra** [danieleteti/delphimvcframework#545]
I have a bank API that is consumed by many clients but some are with a problem.

The API is rest but the body of the result is a XML and in Postman both requests have a valid result.

![image](https://user-images.githubusercontent.com/7242261/160193846-4c32c079-8a89-46f7-b215-602e95b226cc.png)

We are using delphi 11 alexandria with the last version of delphi mvc.

There is any tips or this is an error ?

**Comment by danieleteti** [comment]
That's a Delphi 11 bug (https://quality.embarcadero.com/browse/RSP-35516?filter=-2)
Now with Alexandria 11.1 should be resolved. In the next days we'll release the 3.2.2-nitrogen which will supports a lot of other features and will fix this behavior when used in Alexandria 11.1

**Comment by balenaultra** [comment]
> That's a Delphi 11 bug (https://quality.embarcadero.com/browse/RSP-35516?filter=-2) Now with Alexandria 11.1 should be resolved. In the next days we'll release the 3.2.2-nitrogen which will supports a lot of other features and will fix this behavior when used in Alexandria 11.1

Thanks.
We already updated to 11.1 and we'll be waiting for 3.2.2-nitrogen to solve our client problem.
There is a final release estimate?
Thank you

**Comment by balenaultra** [comment]
Just for the record.
The `master` works fine for this request.

Now I have another request that the return is an empty string. 
In this case the serializer shows an error 'Invalid body'

There is another way to do it or this is a bug? Or I have to open another issue?

When the return of the function is a string I got the empty string with no errors, but I need the Status Code for my algorithm.

This is a third part API that I cannot change.
