### ISSUE TITLE
[EInvalidCast] Invalid class typecast

### ISSUE THREAD

**Issue by jinshaopu** [danieleteti/delphimvcframework#549]
exports TMVCControlerClazz from dll   

in webmodulecreate
if DMVC = nil then
  begin
    DMVC := TMVCEngine.Create(self,
      procedure(Conf: TMVCConfig)
      begin
        Conf[TMVCConfigKey.AllowUnhandledAction] := 'true';
      end);
    for i := 0 to DSSC.MVCCount - 1 do
    begin
      DMVC.AddController(DSSC.MVCCLasses[i]);
    end;
  end;
![image](https://user-images.githubusercontent.com/14891482/162183853-39bfbe66-1447-49a7-b8e1-ace19d413430.png)

**Comment by jinshaopu** [comment]
![image](https://user-images.githubusercontent.com/14891482/162184539-fce3048f-a04a-47c6-87a5-83dfd5699dfd.png)
raise exception at here

**Comment by jinshaopu** [comment]
i have try to set {$typeinfo on}{$methodinfo on}

**Comment by danieleteti** [comment]
Check `samples\server_in_dll\` it shows the correct way to embed a dmvcframework server in a dll.

**Comment by jinshaopu** [comment]
OK  i got it .  i add a new interface  move the router to a dll. that's what i need.
