### ISSUE TITLE
Issue:  parsing booleans in RQL using Firebird 3.0

### ISSUE THREAD

**Issue by azapater** [danieleteti/delphimvcframework#550]
The file MVCFramework.RQL.AST2FirebirdSQL.pas parses booleans in RQL as 0 or 1, which makes FireDAC to raise an exception. 

In the method TRQLFirebirdCompiler.RQLFilterToSQL, changing the lValue of 0 and 1 to false and true respectively solves the issue and it's possible to use booleans in RQL connecting to Firebird 3.0.

I can prepare a PR with this if it's needed. 

    if SameText(aRQLFIlter.OpRight, 'true') then
      lValue := 'true'
    else
      lValue := 'false';

**Comment by danieleteti** [comment]
Thank you for your contribution. However, this change will break old firebird versions and interbase (Interbase compiler inherit from the firebird one). IN the next commit there will be a fix for this problem. Please, le me know if it works for you.

**Comment by azapater** [comment]
Excellent. I didn't think about old FB versions that didn't have native boolean support. I will test it and report if I have any problems. Thanks.

**Comment by danieleteti** [comment]
Any news? Can we close the issue?
