### ISSUE TITLE
Error compiling on Mac OsX "unit Web.ApacheHTTP not found" (Alexandria)

### ISSUE THREAD

**Issue by surfzone-org** [danieleteti/delphimvcframework#551]
You get the error "unit Web.ApacheHTTP not found"

Changed on  dmvcframework.inc

From:
{$IFNDEF MOBILE}
{$DEFINE WEBAPACHEHTTP}
{$ENDIF}

To:
{$IFNDEF MOBILE}
**{$IFNDEF MACOS}**
{$DEFINE WEBAPACHEHTTP}
**{$ENDIF}**
{$ENDIF}

and then, it works

**Comment by danieleteti** [comment]
Did you check if it's a problem in the library path? I don't have a Mac. Can you check if the apache module can be created for Mac?

**Comment by danieleteti** [comment]
Any news?

**Comment by surfzone-org** [comment]
Sorry Daniele, I did not view the repplys...

I found the issue in the client... 

I develop a server compiled in Windows, and the develop a windows, android and macos client... the error raises in the macos client... I can try to compile a sample if compiles on macOs

**Comment by fastbike** [comment]
Looks like there is an associated bug preventing MacOS compilation
```
function TWebContext.GetHostingFrameworkType: TMVCHostingFrameworkType;
begin
{$IFDEF WEBAPACHEHTTP}
  if FRequest.ClassType = TApacheRequest then
  begin
    Exit(hftApache);
  end
  else
  begin
{$IFNDEF LINUX}
    if FRequest.ClassType = TISAPIRequest then
    begin
      Exit(hftISAPI);
    end
    else
{$ENDIF}
{$ENDIF}
    begin
      Exit(hftIndy);
    end;
// add this condition compilation directive
{$IFDEF WEBAPACHEHTTP}
  end;
{$ENDIF}
end;
```
