### ISSUE TITLE
TRoleBasedAuthHandler.OnAuthorization method can't to do Override

### ISSUE THREAD

**Issue by marcelojaloto** [danieleteti/delphimvcframework#556]
Hi,

In the method OnAuthorization of class TRoleBasedAuthHandler can't to do override operation in descendant class.

unit: MVCFramework.Middleware.Authentication.RoleBasedAuthHandler
line: 83

solution:
```
procedure OnAuthorization(const AContext: TWebContext; UserRoles: TList<string>;
      const ControllerQualifiedClassName: string; const ActionName: string; var IsAuthorized: Boolean); overload; virtual;
```

Can i send a new pull request with this solution?

Thanks,
Marcelo Jaloto

**Comment by danieleteti** [comment]
Yes, feel free to contribute.
