### ISSUE TITLE
Delphi bug: Emojis saved as ?? using ActiveRecord

### ISSUE THREAD

**Issue by azapater** [danieleteti/delphimvcframework#561]
This is not a DMVC issue per se, but I wanted to share it with the community, just in case someone struggles with this in the future and hopefully I can save them a few hours of pulling their hair out.

My stack:

Delphi Sydney 10.4 Update 2
DMVC Framework 3.2.1
Firebird 3.0.10 (but I assume the problem will happen with any db)

**Problem:**

Using ActiveRecord I can't save emojis in the database. If I process the query myself in a controller it works fine but using ActiveRecord it saves "??" instead of the chosen emoji.

I assumed then that the problem it would be with DMVC Framework itself so after a lot of debugging and trying to track down the bug I eventually found that the bug is with FireDAC itself. 

ActiveRecord updates the data parsing all the fields as params and I found a bug in FireDAC when you try to assign an emoji using a parameter (actually I think it can generate problems with other unicode symbols). 

File with the bug: FireDAC.Stan.Param

Line 3295 - method: 

`procedure TFDParam.SetAsStrings(AIndex: Integer; const AValue: String);`

In that method you will see a compiler conditional {$IFDEF NEXTGEN} that according to Embarcadero docs it has been deprecated since 10.3, so basically, the needed type ftWideString for handling emojis will never be compiled anymore and all params are treated as ftString.

**Solution:**

change 

`FDataType := {$IFDEF NEXTGEN} ftWideString {$ELSE} ftString {$ENDIF};`

for 

`FDataType := ftWideString;`

Since FireDAC library comes pre-compiled, this change won't be compiled in your projects, so you need to add the source\data\firedac\ delphi folder in your library path.

With this fix now everything seems to work fine and I can save emojis (and any kind of string so far) using ActiveRecord.

I hate the idea of manipulating Embarcadero code, so if anyone can think in a better fix it will be more than welcomed. 

Also, if someone has Alexandria, I would appreciate if they could check if this bug has been fixed.

**Comment by danieleteti** [comment]
Quite strange. In the unittest and in the sample of TMVCActiveRecord we sav emoticons without problem.
Did you checked the sample "activerecord_showcase"?

**Comment by azapater** [comment]
I just checked that in the master branch ActiveRecord_showcase sample you use emojis indeed. It's not the case in the 3.2.1 ActiveRecord_showcase sample that I'm using at the moment (the current release version).

I've been tweaking the ActiveRecord_showcase doing some tests including emojis in the 3.2.1 sample and the bug is there. The emojis are saved as ??. 

If I update the DMVC library to the current developing version and compile the new ActiveRecord_showcase sample, the emojis are saved correctly as you mentioned. 

I haven't spent much time trying to see what has changed in the ActiveRecord unit since 3.2.1 but this is good news anyway, because it means that in the newer version of DMVC that bug is somehow fixed. I won't spend more time in this topic knowing that once I update to the final release it will be fixed.

Thanks for your time Daniel
