### ISSUE TITLE
MVCNameAs attribute and RQL

### ISSUE THREAD

**Issue by azapater** [danieleteti/delphimvcframework#564]
I've noticed that when using the Attribute MVCNameAs, that name doesn't map to other areas like RQL parser. 

I'm willing to try to do this implementation myself and PR it but I wanted to ask a few things first:

- I've seen in MVCFramework.RQL.Parser.pas a TODO comment regarding this, so before trying to analyse the code and develop a new solution myself: could you explain me a few concepts of ideas you already had in mind? This way I can follow the best good practices to contribute to this feature, because my knowledge of the library is way more limited than yours. 

- Is there any other places (apart from rql) that this mapping should be implemented?

- This feature seems quite of a breaking change for future updates. If there are users using rql and nameas attributes, their rql requests will be broken, so not sure if you are happy with this. 

Kind regards

**Comment by danieleteti** [comment]
@azapater let me know

**Comment by azapater** [comment]
@danieleteti Yesterday I did some testing and seems to work perfectly. Great work
