### ISSUE TITLE
using DMVC in LAZARUS!!

### ISSUE THREAD

**Issue by ibelarouci** [danieleteti/delphimvcframework#566]
please how can I use DMVC in Lazarus (FPC)?

**Comment by danieleteti** [comment]
No. DMVCFramework uses advanced language features (generics, extended rtti, rtti attributes, anonymous methods and so on) so freepascal is not able to compile dmvcframework applications. Also, dmvcframework is webbroker based (not a strong dependency, however) so, currently it couls not run on freepascal for the lack of webbroker "compatible" library.
