### ISSUE TITLE
Deserializing Hierarchical JSON issue for Client

### ISSUE THREAD

**Issue by thealgorithms10** [danieleteti/delphimvcframework#568]
Btw, i saw this changes in 3.2.0. May i ask on what do you mean by this?

![image](https://user-images.githubusercontent.com/82137662/178402862-410ab25d-e74f-4dec-b800-8a3ac30fc52c.png)

Cause with regards on this concern, the Hierarchical JSON can't deserialize in ObjectList properties as i encountered here. Even i put the attribute, still didn't include JSONArray properties. May i ask some help here where did it wrong? This was applied for Client after requesting REST.doGet.

Thanks for helping btw.

![image](https://user-images.githubusercontent.com/82137662/178403250-38fd39fb-aa13-4cea-ba9c-6beb9f738257.png)

**Comment by joaoduarte19** [comment]
This looks quite strange.
Can you provide us with a self-contained example that reproduces this behavior?

**Comment by thealgorithms10** [comment]
will attach the sample project. Btw, this is for the client. Trying to work-on with TMVCJsonDataObjectSerializer

**Comment by thealgorithms10** [comment]
Been prepare already the JSON data. This data was from shopify btw.

[deserialize.zip](https://github.com/danieleteti/delphimvcframework/files/9097916/deserialize.zip)

**Comment by thealgorithms10** [comment]
Ah i see. Already verified and tested. My apologies. Thanks btw! will close this report

**Comment by thealgorithms10** [comment]
However, the error was re-occur when i was attempting to deserialize as object only

**Comment by thealgorithms10** [comment]
I attach an updated project, wherein there were portion for deserializing object. However, error occurs when deserializing the sample JSON i attempted

[deserialize_new.zip](https://github.com/danieleteti/delphimvcframework/files/9108671/deserialize_new.zip)

**Comment by joaoduarte19** [comment]
> I attach an updated project, wherein there were portion for deserializing object. However, error occurs when deserializing the sample JSON i attempted
 
Again the error occurs because the product object was not created. To deserialize an object, you must first create it.

Below is your project with fixes that caused these errors and others that caused memory leaks.
[deserialize_new_revised.zip](https://github.com/danieleteti/delphimvcframework/files/9115589/deserialize_new_revised.zip)
