### ISSUE TITLE
RESTResponse.HeaderValue doesn't support in other available APIS

### ISSUE THREAD

**Issue by thealgorithms10** [danieleteti/delphimvcframework#569]
Seems there were problem, i think, in this method as i experienced in Shopify. Shopify has a header called _Link_ that been used in their pagination. However, it was not supported due to strong algorithm i think. Kindly verify this screenshot. 

Thank you and God bless
![image](https://user-images.githubusercontent.com/82137662/181676237-4768c6a4-3a5b-41a8-9eb0-f83597bf87e7.png)

**Comment by joaoduarte19** [comment]
It looks like you're using the deprecated Indy-based RESTClient. Upgrading to the new NetHTTP-based RESTClient will no longer have this problem.

**Comment by thealgorithms10** [comment]
what do you mean to update NetHTTP-based RESTClient? this was from MVCFramework.RESTClient
