### ISSUE TITLE
InvokeRecordInitializer not build In Delphi RIO.

### ISSUE THREAD

**Issue by marcosnielsen** [danieleteti/delphimvcframework#570]
Hello!

After the commit 
26-07-2022 
SHA-1: b89b2727a9dc6205195dcaea46cea26c0cdb0013 
Cleaning some hints
 
![image](https://user-images.githubusercontent.com/24677471/183445656-457bff64-ba92-4372-ae3f-0eda1109dad2.png)

In unit MVCFramework.Serializer.JsonDataObjects;
The MVC Framework.Serializer.JsonDataObjects.mas unit does not compile.
 
![image](https://user-images.githubusercontent.com/24677471/183445762-95d83d97-d090-4ccb-ba1b-592c072df934.png)

Unfortunately the InvokeRecordInitializer() method is not documented in the version before Delphi 10.4 Sydney.

https://docwiki.embarcadero.com/Libraries/RIO/en/System.InvokeRecordInitializer - 👎
https://docwiki.embarcadero.com/Libraries/Sydney/en/System.InvokeRecordInitializer - 👍
https://docwiki.embarcadero.com/Libraries/Alexandria/en/System.InvokeRecordInitializer -👍 

Thanks for your attention
Marcos Nielsen.

**Comment by marcosnielsen** [comment]
Hi @danieleteti
thanks for the change,
but there is a second call of "InvokeRecordInitializer(Buffer, RTTIType.Handle);" Full name:
procedure TMVCJsonDataObjectsSerializer.JSONObjectToRecordStatic(const JSONObject: TJsonObject;


![image](https://user-images.githubusercontent.com/24677471/183546047-00eb6568-5c77-4fdb-b328-b8cacac3aff8.png)

can you make the same correction there?

**Comment by danieleteti** [comment]
@marcosnielsen done, please let me know.

**Comment by marcosnielsen** [comment]
Hi @danieleteti 
DelphiMVC compiled with success
Thanks!

![image](https://user-images.githubusercontent.com/24677471/183661083-b5e6363f-8aa1-4a7b-9b4a-68153720f09c.png)
