### ISSUE TITLE
Swagger information does not get name of fields from MVCNameAs

### ISSUE THREAD

**Issue by jesusgarciazarco** [danieleteti/delphimvcframework#575]
Hello,

Trying to use swagger in a test project I have seen that if I set to properties of classes custom names with MVCNameAs, when documenting with swagger I get the original property name and not the one assigned with MVCNameAs

**Comment by danieleteti** [comment]
@joaoduarte19 could you give a look at this?

**Comment by jesusgarciazarco** [comment]
Sorry, it seems that the problem is mine.
I have Unit1.pas with TClass1 and Unit2.pas with TClass2 = class(TClass1)

If I set attributes MVCNameAs in Unit1 to TClass1, but MVCFramework.Serializer.Commons is not included in uses of Unit1, then the change of the property name is not serialized.

**Comment by joaoduarte19** [comment]
When using a custom attribute it is always necessary to declare Unit that such an attribute is part. The compiler generates a warning message by compiling a Unit that contains an attribute that did not have its Unit declares. Always be aware of compiler messages.

**Comment by danieleteti** [comment]
Thanks @joaoduarte19
