### ISSUE TITLE
A question about https scheme of swagger doc in mvc framework.

### ISSUE THREAD

**Issue by gloomoc** [danieleteti/delphimvcframework#577]
Hello, 
There is any way, or delivery in a future release to in the swagger documentation of the framework showing only the https scheme and not both, http and https.
Until now, we have the unit UMVCSwaggerMiddleware.pas modified, specifically TMVCSwaggerMiddleware class, because the procedure DocumentApiSettings which fills host, basepath, and schemes of swagdoc,
is private and is not heritable or virtual and we want to modify the line of code
// ASwagDoc.Schemes := [tpsHttp, tpsHttps]; to  ASwagDoc.Schemes := [tpsHttps]; to render swagger documentation only with the https scheme.

Thank you very much.

**Comment by danieleteti** [comment]
Please, le me know if this works on your side.
Check the updated sample at the following line.

https://github.com/danieleteti/delphimvcframework/blob/master/samples/swagger_api_versioning_primer/WebModuleU.pas#L93
