### ISSUE TITLE
Info/Warning. ActiveRecordConnectionsRegistry / FireDAC / Multiple connections (databases) issue when setting KeepAlive true.

### ISSUE THREAD

**Issue by Microcom-Bjarne** [danieleteti/delphimvcframework#579]
When using the new project wizard - the generated program (dpr file) will contain the line
`    LServer.KeepAlive := True;`

This line sadly has the effect of "not ending the thread" that was used inside ie. a controller.
Hitting the same endpoint / controller again - will result in using the existing thread.

This is not good - if your setup is using ActiveRecordConnectionsRegistry to control access to databases.
Since ending in existing thread will try to "name" the connection with an existing name.

This behaviour - is very oddly only detectable if both server and client is Delphi. Using Postman or Curl will not produce the same behaviour.

I will not classify it as an error - since the easy solution is to remove the line of code.

But I cannot find any information about - why the keepalive is set to true.
I can only guess it has something to do with "not having to create a new thread" for every request.

I hope others don't have to waste hours hunting this - like I did.

**Comment by danieleteti** [comment]
Hi, 
It's quite strange. The middleware lifecycle is related to the request lifecycle, not the thread lifecycle.
I tried to reproduce the problem but I cannot.
Can you give me a self-contained example which reproduce the problem?

**Comment by danieleteti** [comment]
Any news?

**Comment by Microcom-Bjarne** [comment]
@danieleteti - sorry for not getting back sooner. I will see if i can create a sample app for you to see. I hope I can get around to do it this week.

**Comment by Microcom-Bjarne** [comment]
I've researched the issue - and must admit that the error occurs because I call -
`ActiveRecordConnectionsRegistry.AddDefaultConnection` without calling the remove.

And subsequent call will try to add default again. And throw debugger exception - "duplicates not allowed".

But commenting the keepalive statement actually makes sure, that the thread is terminated, and hence the connection is removed. 

This is all caused by our setup having access to multiple databases via one rest service. And different databases for the connections - all injected in the token. 

I've setup a BaseController - that handles setup and teardown of the connections. 
And I think that is  one / the correct way to handle this.

Only thing that I'm pondering about is the fact that commenting the keepalive actually had the desired effect - and that the problem ONLY was for another win32 delphi application.

**This is not an error** - just close the issue as resolved.
