### ISSUE TITLE
A question about time response in endpoints

### ISSUE THREAD

**Issue by Margera** [danieleteti/delphimvcframework#580]
Is there a native way for DMVC measure to time a request? The intention is to log the information

**Comment by danieleteti** [comment]
We are working on a built-profiler for DMVCFramework. Will be quite powerful but will work since Delphi 10.4+ (is unusable with older versions).
We'll push the changes ASAP.

If you cannot wait (or cannot use it) the @gatosoft suggestion is good.

**Comment by danieleteti** [comment]
Give a look at the new built-in profiler
https://github.com/danieleteti/delphimvcframework#whats-new-in-323-radium-beta
