### ISSUE TITLE
Error on removing default connection

### ISSUE THREAD

**Issue by marcelojaloto** [danieleteti/delphimvcframework#581]
On the event OnAfterRouting in the class TMVCActiveRecordMiddleware the DMVC framework try to remove default connection, but when you haven't the "default" connection in the file connection.ini then occurr the erro below:

---------------------------
Debugger Exception Notification
---------------------------
Project Server.exe raised exception class Exception with message 'Unknown connection default'.
---------------------------

The solution for this problem it is just to deactivate the param 'RaiseExceptionIfNotAvailable' in the method RemoveDefaultConnection.

_Unit: MVCFramework.Middleware.ActiveRecord
Line: 131_
```
procedure TMVCActiveRecordMiddleware.OnAfterRouting(AContext: TWebContext; const AHandled: Boolean);
begin
  ActiveRecordConnectionsRegistry.RemoveDefaultConnection(False);
end;
```

@danieleteti 
Can I send a pull request for you with the fix?

**Comment by danieleteti** [comment]
Thank you, I did the change. However, how you reached that situation? The default connection is added in the `OnBeforeRouting` event. Did you remove it manually?

**Comment by marcelojaloto** [comment]
My connection stay in file Connection.ini with other name, then when I adds support to Active Record, the connection name it is set with the other name.

`FMVC.AddMiddleware(TMVCActiveRecordMiddleware.Create('other_connection_name', ''));`

**Comment by marcelojaloto** [comment]
Another point when you remove a connection, it is not necessary to raise an exception case the connection name does not exist.

**Comment by danieleteti** [comment]
I think there is a misunderstanding here.

When you define your firedac connection name (let's say "myconnection"), this connection become your "default" connection in the ActiveRecordConnectionRegistry. So, it is compulsory to remove the connection with the default name, because you actually added it.

**Comment by marcelojaloto** [comment]
@danieleteti 
Yes, exactly. However in the configuration file (Configuration.ini) there is no connection with the name "default" and so the error occurs. I just muted the message that occurs in case this issue happens. 

ok?

**Comment by danieleteti** [comment]
No, the `ConnectionDefName` in the FireDAC connections file is not related in any way with the "default" name in the ActiveRecordConnectionRegistry, it is just a FireDAC connection definition.  You can have a name i the file and another name in the connection registry.
`RemoveDefaultConnection` *must* raise a connection if it is not available. 

Check the code, and the samples, it should be clear.

Let me know

**Comment by marcelojaloto** [comment]
@danieleteti 
There is an error with the default connection name "default", so if the connection named "default" is not found it will trigger an unnecessary error message. I just disabled the error message which is already predicted in the ActiveRecordConnectionsRegistry.RemoveDefaultConnection method.

I have tested it several times and error always occurs. Disabling unnecessary message error on just calling this method works fine because I have another connection with another name and everything works fine.

**Comment by marcelojaloto** [comment]
If there is a connection with the name "default", then the system will remove this connection normally, but if it does not exist there is no reason to display an error message, because another connection will be activated as in my case.

And in the last case a more specific error in other methods will occur because there is no available connection to the database.

**Comment by marcelojaloto** [comment]
I received the file.

There are several semantic errors. And it needs to be evaluated one by one.

Open the DMVC_Swagger.json file in the Swagger Editor:

https://editor.swagger.io/


errors
 
Structural error at paths./api/patients.delete.parameters.0
should NOT have additional properties
additionalProperty: type
Jump to line 26

Semantic error at paths./api/patients.delete.security.0
Security requirements must match a security definition
Jump to line 47

Semantic error at paths./api/patients/source/{sourceName}/healthcare/companies/{companyCode}/structures/{structureCode}/authority/{authorityCode}.put.security.0
Security requirements must match a security definition
Jump to line 97

Semantic error at paths./api/patients/source/{sourceName}/healthcare/companies/{companyCode}/structures/{structureCode}/authority/{authorityCode}.post.security.0
Security requirements must match a security definition
Jump to line 148

Semantic error at paths./api/patients/source/{sourceName}/healthcare/companies/{companyCode}/structures/{structureCode}/authority/{authorityCode}/slave.delete.security.0
Security requirements must match a security definition
Jump to line 196

Semantic error at paths./api/patients/source/{sourceName}/healthcare/companies/{companyCode}/structures/{structureCode}/authority/{authorityCode}/slave.put.security.0
Security requirements must match a security definition
Jump to line 247

Structural error at paths./api/patients/source/{sourceName}/healtcare/companies/{companyCode}/structures/{structureCode}/authority/{authorityCode}/status/{status}.put.parameters.4
should NOT have additional properties
additionalProperty: type
Jump to line 289

Semantic error at paths./api/patients/source/{sourceName}/healtcare/companies/{companyCode}/structures/{structureCode}/authority/{authorityCode}/status/{status}.put.security.0
Security requirements must match a security definition
Jump to line 317

Semantic error at paths./api/orders/source/{sourceName}/healthcare/companies/{companyCode}/structures/{structureCode}/authority/{authorityCode}.put.security.0
Security requirements must match a security definition
Jump to line 367

Semantic error at paths./api/orders/source/{sourceName}/healthcare/companies/{companyCode}/structures/{structureCode}/authority/{authorityCode}.post.security.0
Security requirements must match a security definition
Jump to line 416

Semantic error at paths./api/report/source/{sourceName}/healthcare/companies/{companyCode}/structures/{structureCode}/authority/{authorityCode}.post.security.0
Security requirements must match a security definition
Jump to line 462

Semantic error at paths./api/events/order/authority/{authority}/timestampUTC/{timestampUTC}/countryCode/{countryCode}/orderId/{orderID}.get.security.0
Security requirements must match a security definition
Jump to line 512

Semantic error at paths./api/events/documents/destination/{destinationName}/count/{eventCount}.get.security.0
Security requirements must match a security definition
Jump to line 548

Semantic error at paths./api/events/patients/destination/{destinationName}/count/{eventCount}.get.security.0
Security requirements must match a security definition
Jump to line 584

Semantic error at paths./api/events/reports/destination/{destinationName}/count/{eventCount}.get.security.0
Security requirements must match a security definition
Jump to line 620

Semantic error at paths./api/events/orders/destination/{destinationName}/count/{eventCount}.get.security.0
Security requirements must match a security definition
Jump to line 656

Semantic error at paths./api/events/destination/{destinationName}/eventId/{eventId}/status.put.security.0
Security requirements must match a security definition
Jump to line 694

Semantic error at paths./api/patientcd/orders/uuid/{orderUUID}/status.post.security.0
Security requirements must match a security definition
Jump to line 731

Semantic error at paths./api/events/patientcd/destination/{destinationName}/count/{eventCount}.get.security.0
Security requirements must match a security definition
Jump to line 769

Semantic error at paths./api/events/configuration/companies/{companyCode}/structures/{structureCode}/destinations/{destinationName}/authority/{destinationAuthorityCode}.put.security.0
Security requirements must match a security definition
Jump to line 822

**Comment by danieleteti** [comment]
Sorry, I still don't get the point. Can you send me a self contained sample which show the problem?

**Comment by Microcom-Bjarne** [comment]
@marcelojaloto 
Do you have a BASE controller? (one from which all other decend from)?
If you do - you could try this approach via tha OnBeforeAction event.

Skip adding the ActiveRecord Middleware

`FMVC.AddMiddleware(TMVCActiveRecordMiddleware.Create('important_connection', ExtractFilePath(GetModuleName(HInstance)) + 'MyConnections.ini'));
`
and simply maintain the ActiveRecordConnectionsRegistry manually.

```
  if not FDManager.ConnectionDefFileLoaded then
  begin
    FDManager.ConnectionDefFileAutoLoad := false;
    FDManager.ConnectionDefFileName := ExtractFilePath(GetModuleName(HInstance)) + 'MyConnections.ini';
    FDManager.LoadConnectionDefFile;
  end;

  if FDManager.IsConnectionDef('important_connection') then // needed for some reason!
  begin
    ActiveRecordConnectionsRegistry.AddDefaultConnection('important_connection');
  end;
```

And then remember to remove default connection in OnAfterAction 
`ActiveRecordConnectionsRegistry.RemoveDefaultConnection(false);`

This works for me :) 

If you don't like this solution or it can't fit in your setup - then please ignore this.

**Comment by danieleteti** [comment]
@marcelojaloto and @Microcom-Bjarne 
Guys, it seems that there is a problem (I don't know if real or not) regarding the ActiveRecordMiddleware, but I still don't understand what it is. The proposed solutions should not be necessary at all. 
Please, send me a reproducible example which show the problem.

**Comment by marcelojaloto** [comment]
> 

@danieleteti 

As soon as I have some free time, I'll try to send you an example.

@Microcom-Bjarne 

I'd like it to reflect the following: If you need to remove a DEFAULT connection that doesn't exist, then the RemoveDefaultConnection method assumes that it has already been removed. Right?

DMVC already provides this in the RaiseExceptionIfNotAvailable parameter of the RemoveDefaultConnection method.

Otherwise, justify me why an exception must be generated that impairs the proper functioning of the system?

Does your solution work fine, but will everyone who uses DMVC need to implement it or another solution, if you just passing False in the parameter of the RemoveDefaultConnection method in the OnAfterRouting event call?

I really appreciate your contribution, if my PR doesn't get approved I'll try to take it into consideration.

I made this contribution hoping to help the entire community.

**Comment by Microcom-Bjarne** [comment]
@danieleteti 

Here is modified sample application using 2 databases.
If this is not the correct way - when using ActiveRecord - then please advice on how.

Please adjust connections.ini and fddrivers.ini to match your setup.
I've used the supplied activerecorddb.fdb database - just made a copy so I have 2.

With this setup type - I cannot see a way of using the Middleware setup. Since it will only add the "default" connection.
Then I will have to do something similar for second connection.

This will get more visible when using BOTH connections in one endpoint.
[middleware_activerecord.zip](https://github.com/danieleteti/delphimvcframework/files/9863838/middleware_activerecord.zip)

**Comment by danieleteti** [comment]
@Microcom-Bjarne 
you can just create another custom middleware, register it *after* the `TMVCActiveRecordMiddleware` and then register another connection (with a name <> 'default') in the `ActiveRecordConnectionsRegistry` and it should work.
However, I think I'll change the `TMVCActiveRecordMiddleware` to allow a more pleasant experience in cases like your.

**Comment by Microcom-Bjarne** [comment]
@danieleteti yes - but my current setup allows me to edit the connections.ini file to add or remove connections, without having to stop my api. It will simply reload the connections.ini.
I can send you my source for this - if you are interested.

**Comment by Microcom-Bjarne** [comment]
@danieleteti I'll have a look at it - probably over the weekend.
My current reload scheme is based upon - if the connection does not exist then reload the connections.ini and see if it exists after.
But that is just another way of doing the same thing.

**Comment by danieleteti** [comment]
@Microcom-Bjarne yes, but checking the timestamp allows to reload connections also if something else, apart the connection name, changes (eg. password, hostname, some other configurations). Also what about connection "removing"? I don't know you scenario, maybe this is needed. 
Just my 2c

**Comment by danieleteti** [comment]
any news on this?
