### ISSUE TITLE
MVCSwagIgnorePath doesn't work like previously

### ISSUE THREAD

**Issue by ads69** [danieleteti/delphimvcframework#587]
Hi Previously (about a year ago) If I have something like this in my controller :
```
[MVCPath('/api')]
 [MVCDoc('BODY SAMPLE')]
 [MVCSwagIgnorePath]
TDocController = Class(TMVCController)
```
this controller didn't appear in the Swagger.
Now I have in the Swagger : [Controller.Doc.TDocController]

Best regards

Armindo

**Comment by ads69** [comment]
puting [MVCSwagIgnorePath] at the first line makes it working again.

**Comment by salehkmeshi** [comment]
thanks bro
