### ISSUE TITLE
Special Characters not supported when rendering

### ISSUE THREAD

**Issue by thealgorithms10** [danieleteti/delphimvcframework#589]
common special characters was not support when rendering - enye example. Please see the image attached

![image](https://user-images.githubusercontent.com/82137662/199429933-fec0c300-20a6-466b-bbb4-b171e517da51.png)

**Comment by danieleteti** [comment]
Is it reproducible with the repo version?

**Comment by thealgorithms10** [comment]
yes i tried also to the latest version but still doesn't work. And also, it is - using simple render with header of application/json and utf8. I'm using MySQL 8.0 btw

![image](https://user-images.githubusercontent.com/82137662/199494384-2e8f1435-3bb0-4e13-a5b2-094b7e6dab70.png)

**Comment by thealgorithms10** [comment]
For your question about properly configured, not quite sure if this might be helpful but yeah this was working in all my projects related in DelphiMVC - except on this matter.

![image](https://user-images.githubusercontent.com/82137662/199495572-07f0cf7e-040e-4725-98d5-b23944a5c813.png)

**Comment by thealgorithms10** [comment]
@danieleteti

**Comment by danieleteti** [comment]
If you read the dataset using "DataSet FieldByName('field').AsWideString" the string is correct?

**Comment by danieleteti** [comment]
I double checked, AFAIK It works (dmvc is used in china, japan, korea etc... so unicode is correctly supported since age).
What you see in the renders sample happend because the connection is not configured for unicode (the database is not unicode). I updated the sample and the qryCustomers to use unicode characters. Please, check it.

**Comment by danieleteti** [comment]
This is one record rendered by the `/customers/simple` router


![image](https://user-images.githubusercontent.com/1428644/200409722-b84b39b2-4795-4c5d-af06-6dc99e351a0b.png)
