### ISSUE TITLE
May be we can get some useful info form QDAC3

### ISSUE THREAD

**Issue by 674395896** [danieleteti/delphimvcframework#59]
Hi,

delphimvcframework is a very good Framework, but incomplete.

May be we can get some useful info form QDAC3.

Like qxml, qmsgpack, qamf, qmacros and so on.

And we can get QDAC3 form
SITE：http://blog.qdac.cc/?page_id=139
SVN：svn://www.qdac.cc/QDAC3

Thanks.

**Comment by danieleteti** [comment]
Please, expose your needs not other framework to just "get info". It is a time waste for the dmvc team. Many things that QDAC3 does are already provided by DelphiMVCFramework, so just ask about specific things and we'll try to help you.

**Comment by 674395896** [comment]
Macros and Xml support

**Comment by danieleteti** [comment]
XML support is in the roadmap and it is not complet to do, but it is simply not so requested by the user so it is not a priority right now.

About "Macros" I've some problem to understand. I found QMacros (https://sourceforge.net/projects/qdac3/files/3.0/QMacros/) but it is a library, what you need from that library that dmvcframework doesn't support?

**Comment by 674395896** [comment]
Macros is like stringReplace, but faster and easy use. 
It is very useful for web page.

**Comment by danieleteti** [comment]
Did you checked mustache in dmvc? It is already used for the server side views and it is much better than a simple string replace. Check the server side view samples.

**Comment by 674395896** [comment]
Thanks, I'll check it completely.
