### ISSUE TITLE
[EInOutError] I/O error 105 [PathInfo "POST /mypath"] (Custom message: "Global Action Exception Handler") [dmvcframework]

### ISSUE THREAD

**Issue by pejuangdelphi** [danieleteti/delphimvcframework#592]
I just try to convert console app to windows service App.
How to solve the issue above?

**Comment by danieleteti** [comment]
Is there some WriteLn in the code?

**Comment by pejuangdelphi** [comment]
Hello Danieletete,

Yes. After deleting all lines with WriteLn, working properly now.

Thank you so much for the direction
