### ISSUE TITLE
How can an enum set be passed as a parameter for JSONRPC?

### ISSUE THREAD

**Issue by rjantz3** [danieleteti/delphimvcframework#598]
If there is an enum defined as `TEnum = (a1, b2, c3, d4)` and a set defined as `TEnumSet = set of TEnum` how can `[b2, d4]` be passed as a single parameter through the `TJSONRPCRequestParams`?

**Comment by HealthOneNZ** [comment]
At this stage you would have to do some custom marshalling as there is no direct support for custom enumerations apart from boolean.
![image](https://user-images.githubusercontent.com/92825816/204687566-61bd5834-a6f7-4a72-afe9-14e57e8034f6.png)
So that means code like this will not work
```  TEventFunctions = class
  public
    function Test(data: TEnumSet): string;
```
However I'm sure you could pass a json array of strings that represent your enumeration set, or numbers that represent the underlying bit values, and then write a simple deserialisation routine.

Show us the code you have tried ?

**Comment by HealthOneNZ** [comment]
Actually on further investigation, the parameter matching code in the RPC controller does not handle sets at all. You could have a go at writing something and contributing it back to the library.

**Comment by HealthOneNZ** [comment]
If you need some code to convert string representations back to an enumerated type I often use code like this, you'd need to use some RTTI to make it more generic as this has a specific enumerated type within it.
```
function TFHIROperationParameterUseFromString(Value: string): TFHIROperationParameterUse;
begin
  Result := TRttiEnumerationType.GetValue<TFHIROperationParameterUse>(Value);
  if (Result < Low(TFHIROperationParameterUse)) or (Result > High(TFHIROperationParameterUse)) then
    raise Exception.CreateFmt('Could not convert %s to FHIR OperationParamterUse', [Value]);
end;
```

**Comment by danieleteti** [comment]
Please, check your version. It already works as you need.

Using a server method like the following
```delphi
function TMyObject.GetSetBySet(Value: TSetTest): TSetTest;
begin
  Result := [];
  for var lItem := ptEnumValue1 to ptEnumValue4 do
  begin
    if lItem in Value then
    begin
      Result := Result - [lItem];
    end
    else
    begin
      Result := Result + [lItem];
    end;
  end;
end;
```

you can issue a request like the following and get the correct result

```json
{
  "jsonrpc":"2.0",
  "id":1234,
  "method":"GetSetBySet",
  "params":["ptEnumValue1,ptEnumValue2"]
}

```

**Comment by danieleteti** [comment]
Maybe the client side proxy could be more elegant in case of single sets/enums parameter...

**Comment by rjantz3** [comment]
I did eventually get this to work after realizing that the parameters on the server were expecting an array of enum values instead of a typed set. I then built up a comma separated string like this `'[a1,c3,d4]'` and then it worked.
