### ISSUE TITLE
How to use MVCValueAsType attribute?

### ISSUE THREAD

**Issue by Microcom-Bjarne** [danieleteti/delphimvcframework#600]
in latest version of `MVCFramework.Serializer.Commons` line 80 

`MVCValueAsTypeAttribute = class(TCustomAttribute)` is declared.

How to use this attribute correct? 
**I cannot see any uses in any samples or in the dmvc book.**

My example on how to use it is :

```
[MVCNameCase(ncLowerCase)]
[MVCTable('EMPLOYEE')]
TEmployee = class(TMVCActiveRecord)
private
  [MVCTableField('ISBOSS')]
  fIsBoss_bool: boolean;
public
  [MVCValueAsType(System.TypeInfo(integer))]
  property IsBoss: boolean read fIsBoss_bool write IsBoss_bool;
end;
```

Where ISBOSS is an integer field in a FireBird database.

field is added _bool to its name - to make sure we hit this code in 

`MVCFramework.Serializer.Commons` line 1144  procedure `MapDataSetFieldToRTTIField`

```
        // sqlite doesn't support boolean, so are identified as integers
        // so we need to do some more checks...
        if (aRTTIField.FieldType.TypeKind = tkEnumeration) and (aRTTIField.Name.ToLower.Contains('bool')) then
        begin
          aRTTIField.SetValue(AObject, AField.AsInteger = 1);
        end
		else if (aRTTIField.FieldType.TypeKind = tkEnumeration) then
        begin
          TValue(AField.AsInteger).ExtractRawData(PByte(Pointer(AObject)) + aRTTIField.Offset);
        end
```

This will produce boolean true/false for a field with 0/1 value in the firebird database.

**Comment by danieleteti** [comment]
It is related only to property/field of type `TValue`. It allows to serialize such properties/fields "as-another-type".
Check [Here](https://github.com/danieleteti/delphimvcframework/blob/master/unittests/common/MVCFramework.Tests.Serializer.Entities.pas#L94)
