### ISSUE TITLE
swaggerdoc sample Access Violation

### ISSUE THREAD

**Issue by radexpol** [danieleteti/delphimvcframework#603]
1. Run the project
2. Follow the link: http://localhost:8080/swagger/
3. POST /people -> **Try it Out**
4. **Execute**

**{
  "classname": "EAccessViolation",
  "detailedmessage": "",
  "apperrorcode": 0,
  "items": [],
  "statuscode": 500,
  "reasonstring": "Internal Server Error",
  "message": "Access violation at address 00825D37 in module 'SwaggerDocApi.exe'. Read of address 00000004",
  "data": null
}**

**Comment by salehkmeshi** [comment]
you need to use the endpoint "http://localhost:8080/api/swagger"
to get answer
