### ISSUE TITLE
Crash when attempting to deserialize an array when a JSONRPC response is empty.

### ISSUE THREAD

**Issue by rjantz3** [danieleteti/delphimvcframework#606]
On our local system we inserted `if lIntf.ResultAsJSONArray <> nil then` at line 2831 of `MVCFramework.JSONRPC` but there may be better ways to handle it.

**Comment by rjantz3** [comment]
Actually it may be better to handle it at a lower level, maybe like line 3939 of `MVCFramework.JSONRPC` and insert `  if not assigned(JSONArray) then
    Exit;` so that anything coming into `TJSONUtils.JSONArrayToArrayOfRecord<T>` is checked.

**Comment by danieleteti** [comment]
Can you show me a self-contained sample about this issue?
I need an JSONRPC method which raises an error for the reason you noted.

**Comment by rjantz2** [comment]
Using the latest code on this branch I am not able to duplicate the problem.

I'm fine with closing this issue and related pull request and reopening it at a later date if necessary.
