### ISSUE TITLE
Feature Request: Custom mime types for StaticFiles Middleware

### ISSUE THREAD

**Issue by fastbike** [danieleteti/delphimvcframework#607]
The TMVCStaticFilesMiddleware class has a hard coded list of allowable extensions and mime types.

We have an application where we are redirecting users to download a browser extension - for Firefox this is an *.xpi file with a mime type of "application/x-xpinstall"

The constructor of the middleware calls a private method AddMediaTypes which adds a static list to a mapping dictionary.

My suggestion is to either:

1. add a read only property to the class to make the private TDictionary accesible

```
  TMVCStaticFilesMiddleware = class(TInterfacedObject, IMVCMiddleware)
...
  public
    property MediaTypes: TDictionary<string, string> read fMediaTypes;
...
end;
```
or
2. make the private method protected/public and virtual so it could be overridden. A little clunkier as then the class needs to be sub classed to change the behaviour.
```
  TMVCStaticFilesMiddleware = class(TInterfacedObject, IMVCMiddleware)
...
  public
    procedure AddMediaTypes virtual;
...
end;
```
or
3. Add an optional parameter to the constructor allowing additional media types to be mapped.

My preference is for solution 1 as it provides default behaviour out of the box, is backward compatible, and allows full control of allowable media types i.e. the application writer can remove existing default values if desired.

**Comment by danieleteti** [comment]
Check the updated `\samples\middleware_staticfiles\` and let me know if it works for your case.

**Comment by fastbike** [comment]
That looks good, thanks for the enhancement.
