### ISSUE TITLE
How to handle MVCFromQueryString exceptions

### ISSUE THREAD

**Issue by radexpol** [danieleteti/delphimvcframework#608]
`procedure AddNumbers(const [MVCFromQueryString('Value1')] Value1: integer;
                                         const [MVCFromQueryString('Value2')] Value2: integer);`

http://localhost:8080/api/addnumbers?Value1=aaaaabbbccc&Value2=aaaaabbbccc

an horrible and unreadable for end-user error message is displayed:

_{"classname":"EMVCException","detailedmessage":"","apperrorcode":0,"items":[],"statuscode":400,"reasonstring":"Bad Request","message":"Invalid Integer value for param [Value1] - [CLASS: EConvertError][MSG: 'aaaaabbbccc' is not a valid integer value]","data":null}_

How to handle such errors to force friendly error message? Without this possibility this feature seems to be unusable :( Maybe default value could be used instead of raising error? Or maybe there is error handler where I can catch the method and display my own error message.

**Comment by fastbike** [comment]
There is a global exception handler on the FMVC instance, where you can do custom logging (e.g. stack trace etc) and format the response message

**Comment by radexpol** [comment]
OK, I'll handle it in OnError, I met the CustomExceptionHandling while browsing the code under debug, I hope that;s the place you are talking about. Thanks. Should I close this Issue or leave it for others?

**Comment by fastbike** [comment]
You can see how it can be used in the examples
https://github.com/danieleteti/delphimvcframework/tree/master/samples/custom_exception_handling

**Comment by radexpol** [comment]
@fastbike thank you very much, closing issue
