### ISSUE TITLE
SSE Messages in one request

### ISSUE THREAD

**Issue by radexpol** [danieleteti/delphimvcframework#612]
The SSE mechanism implemented in dmvc does not seems to be implemented correctly but I can be wrong :)
The online graphs showing the SSE data transfer suggest that there is only one request /getMessages from the web and no more requests are done from the browser: [Screen](https://turkogluc.com/content/images/size/w2000/2021/01/Blank-diagram--1--1.png) Both of  DMVC samples makes a flood of requests to get data instead of waiting for data. This does not make sense if no data waiting on server side. In my opinion the server side should send the data in never-ending loop and the method RenderSSE should use existing connection initiated with correct headers (event-stream) and post the data in loop such as:

```
procedure TSSEController.Index;
begin
  RenderSSEHeader;

  while client.Connected do
  begin
     RenderSSEData(id+1, 'the time is '+Now(), 'time'); 
     sleep(1000);
   end;
end
```

**Comment by danieleteti** [comment]
The "waiting" logic is charge to the server. If the server doesn't "wait" it's just a polling. 

However, WebBroker (the fundation technology of dmvcframework) doesn't support streaming response, cannot be sent multiple SSE responses in a single HTTP response.
