### ISSUE TITLE
[SSE] Server Sent Events

### ISSUE THREAD

**Issue by radexpol** [danieleteti/delphimvcframework#613]
@danieleteti sorry I'm again with SSE Issue :) I've realized the correct implementation of SSE in the MVC framework using an access to the base indy class TIdHTTPAppResponse, short part of solution I've done for testing purposes and it is a working SSE.

```
procedure TSSEController.Index;
var
  id: Integer;
begin
  inherited;
  const EOL = #13#10;

  var rawContext := TTIdHTTPAppResponseAccess(GetContext.Response.RawWebResponse).FThread;

  with rawContext.Connection.IOHandler do
  begin
    WriteBufferOpen;
    WriteLn('HTTP/1.1 200 OK');
    WriteLn('Content-Type: text/event-stream; charset=UTF-8');
    WriteLn('Cache-Control: no-cache');
    WriteLn('Connection: keep-alive');

    WriteLn;
    WriteBufferClose;

    id := 0;
    while (rawContext.Connection.Connected()) do
    begin
      WriteBufferOpen;

      //demo 1 item in send queue , replace with "while data.count > 0 do"
      Inc(id); //next id
      Write('id: ' + inttostr(id) + EOL);
      Write('event: currentTime'+ EOL);
      Write('data: '  + Format('{"now":"%s"}', [DateTimeToStr(now)]) + EOL + EOL);  //raw text

      WriteBufferClose;
      Sleep(10000); // sample wait
    end;
  end;
end;

```

So... I think that we could:
1. include the correct SSE mechanism in MVCFramework.pas where the access to low-level sockets may be much more professional version then the one I implemented for testing

OR

2. create the Middleware that expands the event OnGetNewData(const queue: TArray<TRecord[id, event, data]>; const startIndex: integer = 0 _{if you dont use buffers i.e. sending the temperature or time}_) and it will be the only part of code for end-user he must implement - "give me the queue of sse events", all this low-level sh* could be hidden in the MVCFramework or SSEMiddleware.

What do you think? I can help implement 1. or 2. solutions but I'm too new in your framework (moving from mORMot) so I would need help from you, at least which way is better.

If you are not interested in SSE continuation just close this issue, I will use this solution for my internal use only.

**Comment by danieleteti** [comment]
I'm very interested to your solution, but we have to find a way to make it works in Apache modules and ISAPI.

**Comment by danieleteti** [comment]
However I'm more for solution 1

**Comment by radexpol** [comment]
Hmm, no experience with Apache or ISAPI. Actually I'm learning the framework to find a good place to add the sse feature, seems that MVCFramework.pas only prepares data, it does not flush to socket, so I'll try to find another way.

**Comment by radexpol** [comment]
After evaluating the code, I think the future solution is middleware such as:
```
MVCSSEMIddleware.pas
----------

type
  TSSERecord = record
    event: string; //optional
    data: string;
   end;
end;

webModule.pas
------------------
  MVC.AddMiddleware(TMVCSSEMiddleware.Create(
    '/listener', 'UTF-8',
      procedure(out data: TArray<TSSERecord>)
      var
        dataList: TArray<TSSERecord>;
        rec: TSSERecord;
      begin
        while not table.eof do
        begin
          if table.fieldByname('INCOME') then
          begin
            rec.event := 'moneyIncome';
            rec.data := Format('{"amount: %d", "moneySource":"%s"},[table.fieldByname('AMOUNT'), table.fieldByname('MONEYSOURCE')]);
          end 
          else
            rec.event := 'moneyOutcome';
            rec.data := Format('{"amount: %d", "moneyRecipient":"%s"},[table.fieldByname('AMOUNT'), table.fieldByname('MONEYDESTINATION')]);
           end;         
          dataList := dataList + [rec];
          table.Next;
        end;  
        data := dataList;
      end; 
    );
```
still analysing, feel free to add your hot comments

**Comment by danieleteti** [comment]
I don't know if middleware is the better solution here.
What do you think about something like the following

```delphi
procedure TMyController.MyAction;
begin
  StartSSE(
      procedure (out data: TMVCSSEMessages)
      var
        dataList: TMVCSSEMessages;
        rec: TSSEMessage;
      begin
        while not table.eof do
        begin
          if table.fieldByname('INCOME') then
          begin
            rec.event := 'moneyIncome';
            rec.data := Format('{"amount: %d", "moneySource":"%s"},[table.fieldByname('AMOUNT'), table.fieldByname('MONEYSOURCE')]);
          end 
          else
            rec.event := 'moneyOutcome';
            rec.data := Format('{"amount: %d", "moneyRecipient":"%s"},
               [table.fieldByname('AMOUNT'), table.fieldByname('MONEYDESTINATION')]);
           end;         
          dataList := dataList + [rec];
          table.Next;
        end;  
        data := dataList;
      end; 
    ););
end;
```

`StartSSE` could receive an anonymous method, a method pointer or a class instance implementing a specific interface.

**Comment by radexpol** [comment]
I'm not sure Daniele, the Controller is a part of REST based framework. The SSE, Websocket, Socket, named pipes etc. are not related to the REST standard, they can send any stream (not json, non-standard data, video etc), that's why I though that like static files middleware, the SSE (and maybe websockets in the future) should use their own plugin (middleware). I will think tomorrow.

**Comment by radexpol** [comment]
Couldn't sleep, so I made it work as I proposed - middleware. I'm attaching the files, not yet finished (reconnect etc.), but have a look if this piece of code is good written according to your framework, as I told I'm new here so the core of requests, responses flow may be misunderstood by me.

Zipped files:
(https://github.com/danieleteti/delphimvcframework/files/10317263/MVCFramework.Middleware.SSE.zip)

and working result:

![SSE](https://user-images.githubusercontent.com/35150005/209893975-ce7f11bd-7413-4699-83a8-32eac60cf099.jpg)

**Comment by radexpol** [comment]
And my testing page, you must refresh the page to see the listen event in the list and change in html file.

(https://github.com/danieleteti/delphimvcframework/files/10317270/testCC6.0Listen.zip)

**Comment by danieleteti** [comment]
Good Job @radexpol 
I'm thinking to another solution.
Controllers are not related to REST; they are just a way to use the internal router mechanism to map an HTTP request to a class method. So, I was thinking to a specialized controller. Something like `TMVCSSEController` where you can inherit and override some methods. I'm not so favorable to the middleware because middlewares are intended to do  "low level stuff" and usually no user code is executed by middlewares. Also, middleware are scanned at each and every requests, loading the routing phase. This is the reason because middleware should not be abused. What do you think about the specialized controller?

**Comment by radexpol** [comment]
As I see, the Controllers cannot be initialized manually by configuration data and getSSEData( ) event handler, so everyone must modify the MVCSSEController.pas to fit their needs :(

For example in middleware solution I can pass all required configuration data in: MVC.AddMiddleware(TMVCSSEMiddleware.Create(sseData, '/listen', True)) -> that's all you must do to start SSE

in controller version I cannot do similar:
MVC.AddController(TMVCSSEController.Create(sseData, '/listen', True)));  -> instead I have to open the MVCSSEController.pas and modify the endpoint name, keepOrder param, characterEncoding param etc, so the MVCSSEController.pas cannot be even in the root of DMVC Source Files, but in /samples. In opposite, the MVCSSEMiddleware.pas could be in common sources, nobody needs to make any changes in that file.

But I agree with you, I optionally need an access to logged user, because the events are separate for each user and probably access to all other data available when I use Controllers, so again I feel confused :( Need suggestion. How to combine the convenience of use with DMVC events flow.

**Comment by danieleteti** [comment]
> As I see, the Controllers cannot be initialized manually by configuration data and getSSEData( ) event handler, so everyone must modify the MVCSSEController.pas to fit their needs :(

Controllers construction is fully configurable.
Check https://github.com/danieleteti/delphimvcframework/blob/master/samples/activerecord_restful_crud/WebModuleU.pas#L82

So we can inject anything.

> But I agree with you, I optionally need an access to logged user, because the events are separate for each user and probably access to all other data available when I use Controllers, so again I feel confused :( Need suggestion. How to combine the convenience of use with DMVC events flow.

I'm thinking about the following "high-level" utilization pattern


```delphi
  FMVC.AddController(TMySSEController,
    function: TMVCController
    begin
      Result := TMySSEController.Create("all the initializationdata you need");
    end);

```

This `TMySSEController` is controller inherited from `TMVCSSEController`.
The `TMVCSSEController` contains all the low level code to handle SSE while the `TMySSEController` just overrides a virtual `DoGetMessages(LastEventID: String)` method which returns the new message to send to the client.

IMHO it is a more OO and clean solution. What do you think about?

**Comment by radexpol** [comment]
@danieleteti , I implemented it as suggested - using a controller seems to work fine. Please take a look at the files, I hope that's what you meant.
[SSE2.zip](https://github.com/danieleteti/delphimvcframework/files/10321062/SSE2.zip)

**Comment by radexpol** [comment]
The Delphi SSE Client has been completed, look:

[DelphiSSEClient.zip](https://github.com/danieleteti/delphimvcframework/files/10327994/DelphiSSEClient.zip)

**Comment by danieleteti** [comment]
> The Delphi SSE Client has been completed, look:
> 
> [DelphiSSEClient.zip](https://github.com/danieleteti/delphimvcframework/files/10327994/DelphiSSEClient.zip)

Nice!
Do you want to donate this code (for the client side) to dmvcframework project (you'll mantain the original copyright) or not?

**Comment by radexpol** [comment]
DelphiSSEClient I've written can be freely distributed, I'd be proud If you include it to dmvcframework.

**Comment by radexpol** [comment]
What about my previous message? 

> @danieleteti , I implemented it as suggested - using a controller seems to work fine. Please take a look at the files, I hope that's what you meant. [SSE2.zip](https://github.com/danieleteti/delphimvcframework/files/10321062/SSE2.zip)

What about this?  Continue or wrong way?

**Comment by radexpol** [comment]
I can finish the MVCFramework.SSEController.pas if you want and give you the final file

**Comment by danieleteti** [comment]
Just pushed the revised units and the sample project used to show this feature.
Feel free to complete/implement your thinking. Then we'll talk about it.
Thank you

**Comment by radexpol** [comment]
Well I though that Last-Event-Id will be hidden for end-user and the framework will take care about safe message distribution. That's why I created the message buffer "failoverCache: TDictionary<integer, TSSEMessage>;" which contains the unsent messages and take care about resending messages with correct Last-Event-Id counter internally....

**Comment by danieleteti** [comment]
The last_event_id cannot be hidden to the user because the user must "understand" which is the next message to send so it must understand the criteria used to generate the IDs.
What do you think about the current implementation?

**Comment by radexpol** [comment]
In many cases the last_event_id is not used, this is an optional parameter. BUT even if we want to use message counting - if you expose last_event_id to end-user, you require from him to take care about message flow and reliability of message order etc. so you must add extra OnSentError and other events to allow end-user full control the message orders... it seams to be unnecessary...

In the real world: I want to send the message {"income":"$122"} and next {"outcome":"$122"} to web client. MVC framework should add the eventID=1 to first json, the eventID=2 to second and our low-level engine (MVCFramework.SSEController.pas) should do the "dirty job". Just the comfortable solution for mass developers. Of source, the enhanced version (virtual methods) of MVCFramework.SSEController.pas can give more possibilities to manually steer the message flow.

**Comment by danieleteti** [comment]
The streaming model does not take care of the "unsent messages". If client cannot read message X (or read it and then crashes) is not a server problem, it is just a possibility (this is one of the big advantage compared to classic message buses)
This is how work redis stream and the [dmscontainer](http://dmscontainer.bittimeprofessionals.com/) eventstream and a number of other event stream systems.
If the client doesn't care about order is OK, but if need ordering it *must* decide the ordering criteria and, based on the last "LastEventID" (and only the lasteventid) it must be able to identify the "next" message to send. In case of disconnection it can restart from the "LastEventID" sent by the client and just restart from there.
Does it sound good for you?

**Comment by radexpol** [comment]
I'm not sure about expanding event-id blackbox to enduser, but I'm ok with your interpretation. I can always create my own variation of MVCFramework.SSEController.pas for lazy developers.

1. Remove SSE_KEEP_ORDER, if we do not use internal event counting
2. _Retry: Integer;_ not necessary in record, IMHO should be in:

```

TMVCSSEDefaults = class sealed
  public const
    /// <summary>
    /// Charset of SSE messages encoding
    /// </summary>
    SSE_CONTENT_CHARSET = TMVCConstants.DEFAULT_CONTENT_CHARSET;

    /// <summary>
    /// Force client to reconnect again after specified milliseconds
    /// </summary>
    SSE_RETRY_TIMEOUT = 10000;
end;

constructor Create(const ASSECharset: string = TMVCSSEDefaults.SSE_CONTENT_CHARSET; const ARetryTimeout: integer = TMVCSSEDefaults.SSE_RETRY_TIMEOUT); reintroduce; overload;
```

**Comment by danieleteti** [comment]
Hi, 
I merged all the server changes you proposed. Thanks.
About the Client Side we have a problem.
The Task is continuosly reading from HTTP (as it should), however we cannot "close" the client program in a clean way because the following line doesn't return the control flow to the caller... so the `while` never exit.
The line if the following
```delphi
        fIdHTTP.Get(FURL, fEventStream);
```
The http response never ends so the client code cannot check if the task must ends.
I'm doing some research about this. You can find the sample program (server and client) in the new sample named "samples\serversentevent_for_indy_based_servers\".
Let me know

DT

**Comment by radexpol** [comment]
Fixed file below. The only way to take control over .Get or even .Readln if TIMEOUT parameter.
[DelphiSSEClient.zip](https://github.com/danieleteti/delphimvcframework/files/10362637/DelphiSSEClient.zip)

important changes:
```
constructor TDelphiSSEClient.Create(const AURL: string);
begin
  fURL := AURL;
  IdHTTP := TIdHTTP.Create(nil);
  IdHTTP.ReadTimeout := 100;    ->>>>>>>>>>>>> THIS 
  IdSSL := TIdSSLIOHandlerSocketOpenSSL.Create(nil);
  IdSSL.SSLOptions.Method := sslvSSLv23; //wildcard for accepting all versions
  IdHTTP.IOHandler := IdSSL;
```
and


```

while (workingTask.Status = TTaskStatus.Running) do
    begin
      try
        IdHTTP.Request.CustomHeaders.AddValue('Last-Event-ID', lastEventId.ToString);
        IdHTTP.Get(FURL, EventStream);
      except
        on e: exception do
        if not (E is EIdReadTimeout) then    ->>>>>>>>>>>>>>>>>>>>>> THIS
        begin
          //non blocking Sleep
          nextRetry := IncMilliSecond(Now, ReconnectTimeout);
          while Now < nextRetry do
          begin
            if workingTask.Status <> TTaskStatus.Running then
              Break;
          end;
        end;
      end;
    end;


```

**Comment by danieleteti** [comment]
Yes, I know, but the timeout is not a solution. Think about a continuos stream of messages... the client never reaches a timeout.
Using the new THTTPClient instead of the TidHTTP we may be free from openssl and could use the OnReceiveData event which allows to abort the request even if there are data available.
https://docwiki.embarcadero.com/Libraries/Sydney/en/System.Net.HttpClient.THTTPClient.OnReceiveData

What do this think about?

**Comment by fastbike** [comment]
Using native components rather than Indy caters for a wider audience :+1:

**Comment by radexpol** [comment]
I'm almost ready with THTTPClient.

**Comment by radexpol** [comment]
@danieleteti please verify if that's what you expected:

Working code:

[DelphiSSEClient.zip](https://github.com/danieleteti/delphimvcframework/files/10365287/DelphiSSEClient.zip)

**Comment by danieleteti** [comment]
@radexpol could you apply the changes directly to the committed file named `MVCFramework.SSEClient.pas`, please?

**Comment by radexpol** [comment]
I don't know how to do this. Updated file:

[MVCFramework.SSEClient.zip](https://github.com/danieleteti/delphimvcframework/files/10366307/MVCFramework.SSEClient.zip)

**Comment by radexpol** [comment]
@danieleteti I thought about the responsetimeout method of breaking the never-ending Get request and in my opinion this is a bad way. We have the flood of Get methods every 100 ms or 1 sec. Reconnecting takes time, negotiating certificates, creating session on server side... I'm sure that browsers does not make such attacks to the backend, but the question is, how browsers breaks the waiting request...
I'm afraid that we have to revert the .Get to wait for data continuously. I think about external thread (or mainThread) that makes the fRest.Disconnect, which raise exception and break the loop. I saw such solution in Indy. Tomorrow will continue.

**Comment by radexpol** [comment]
Fixed, change waiting for acceptance.

**Comment by radexpol** [comment]
@danieleteti I found an issue in **MVCFramework.SSEController**:

```
    constructor Create(
      const ASSECharset: string = TMVCSSEDefaults.SSE_CONTENT_CHARSET;
      const ARetryTimeout: UInt32 = TMVCSSEDefaults.SSE_RETRY_TIMEOUT); reintroduce; overload;
```

but when you register controller:

```
TControllersRegister.Instance.RegisterController(TMyController)
```

then our constructor is not executed but inherited constructor from base class, so defaults are not set. Any idea where to set default values if default parameterless constructor is executed ?

**Comment by danieleteti** [comment]
> @danieleteti I found an issue in **MVCFramework.SSEController**:
> 
> ```
>     constructor Create(
>       const ASSECharset: string = TMVCSSEDefaults.SSE_CONTENT_CHARSET;
>       const ARetryTimeout: UInt32 = TMVCSSEDefaults.SSE_RETRY_TIMEOUT); reintroduce; overload;
> ```
> 
> but when you register controller:
> 
> ```
> TControllersRegister.Instance.RegisterController(TMyController)
> ```
> 
> then our constructor is not executed but inherited constructor from base class, so defaults are not set. Any idea where to set default values if default parameterless constructor is executed ?

Sorry to be late... you fixed this in the PR, isn't it?

**Comment by radexpol** [comment]
How to describe controller using SWAG* Attributes (and MVCDoc?) to get the well formatted name of SSE Endpoint?

```
type
  [MVCPath('/v1/events')]
  [MVCSWAGDefaultSummaryTags('Events')]   -> this does not show well-formatted name of endpoint in swagger
  TEventsController = class(TMVCSSEController)
  protected
    function GetServerSentEvents(const LastEventID: String): TMVCSSEMessages; override;
  end;

```

**Comment by danieleteti** [comment]
> How to describe controller using SWAG* Attributes (and MVCDoc?) to get the well formatted name of SSE Endpoint?
> 
> ```
> type
>   [MVCPath('/v1/events')]
>   [MVCSWAGDefaultSummaryTags('Events')]   -> this does not show well-formatted name of endpoint in swagger
>   TEventsController = class(TMVCSSEController)
>   protected
>     function GetServerSentEvents(const LastEventID: String): TMVCSSEMessages; override;
>   end;
> ```

Can you create another issue with this question? So we can close the main issue.
