### ISSUE TITLE
Thread safe TMVCRESTClient

### ISSUE THREAD

**Issue by radexpol** [danieleteti/delphimvcframework#616]
@danieleteti I've implemented the thread safe generic, that allows for safe use of existing objects/interfaces. I've developed it for my own needs by can be useful in MVC project?
Benefits:

1. Once created TMVCRESTClient can be used in any thread
2. Automatic object unlocking from critical section
3. Using one existing persistent connection to server (new connections takes time to connect and eats server thread)

[ThreadSafeController.zip](https://github.com/danieleteti/delphimvcframework/files/10362682/ThreadSafeController.zip)

usage:
```
type
  TForm1 = class(TForm)
  private
     myRest: IMVCRESTClient;
    procedure FormCreate;
    procedure Button1Click(Sender: TObject);
public
   function GetRest: IMVCRESTClient;
  end;

procedure TForm1.FormCreate;
begin
    myRest := TMVCRESTClient.New.BaseURL('127.0.0.1', 8080);
    myRest.SetBearerToken('aaa.bbb.ccc');
end;

function  TForm1.GetRest: IMVCRESTClient;
begin
   Result := TThreadSafeController<IMVCRESTClient>.SafeAccess(myRest).Instance;
   Result.ClearAllParams;
end;

procedure TForm1.Button1Click(Sender: TObject);
begin
  TThread.CreateAnomymousThread(procedure
                                                           begin
                                                                var lRest := Form1.GetRest;   ->>>>> WILL WAIT UNTIL '/testEndpoint2' FINISH EXECUTE 
                                                                lRest.AddQueryParam('myParam', 'myValue');
                                                                lRest.Get('/testEndpoint1');
                                                               sleep(1000);     
                                                           end).Start;

 var lRest := Form1.GetRest;
 lRest.Get('/testEndpoint2');
end;

```

**Comment by joaoduarte19** [comment]
I don't know if I missed something, but I think the ```Async``` method of TMVCRESTClient already does that.

**Comment by radexpol** [comment]
Async if ok when you do not expect the response immediately, you just pass the response method that will execute on successful request.

**Comment by radexpol** [comment]
If the solution does not meets MVC needs, just delete this issue.
