### ISSUE TITLE
Not render nullable properties when they are empty

### ISSUE THREAD

**Issue by Pecaas** [danieleteti/delphimvcframework#630]
Is it possible to configure renders to not render nullable properties when they not HasValue? Thank you.

**Comment by danieleteti** [comment]
Please, check teh README about `MVCSerializeNulls` and let me know if its work for you.

**Comment by Pecaas** [comment]
Thank you for solution, but I still can't Render json without 'null'

I have set `MVCSerializeNulls := False;` in dpr.

Fragment of my class with nullable types:
 
```
TubdBookBase = class(TInterfacedObject)
  private
    FBarva: TNullableInteger;
    FCisloObj: TNullableString;
    FCisPac: TNullableInteger;
    FCisPoj: TNullableInteger;
    FDatNar: TNullableString;
  public
    [MVCSwagJsonSchemaField(stInteger, 'barva', '', False, True)]
    property Barva: TNullableInteger read FBarva write SetBarva;
    [MVCSwagJsonSchemaField(stString, 'cisloobj', '', False, True)]
    property CisloObj: TNullableString read FCisloObj write SetCisloObj;
    [MVCSwagJsonSchemaField(stInteger, 'cispac', '', False, True)]
    property CisPac: TNullableInteger read FCisPac write FCisPac;
    [MVCSwagJsonSchemaField(stInteger, 'cispoj', '', False, True)]
    property CisPoj: TNullableInteger read FCisPoj write FCisPoj;
    [MVCSwagJsonSchemaField(stString, 'datnar', '', False, True)]
    property DatNar: TNullableString read FDatNar write FDatNar;
```

Result json still contains nulls <html><body>
<span><span>
</span></span><span><span><pre class=" microlight" style="display: block; overflow-x: auto; padding: 0.5em; background: rgb(51, 51, 51); color: white;"><code class="language-json" style="white-space: pre;"><span>{
</span><span>  </span><span class="hljs-attr">"barva"</span><span>: </span><span style="color: rgb(252, 194, 140);">null</span><span>,
</span><span>  </span><span class="hljs-attr">"cisloobj"</span><span>: </span><span style="color: rgb(162, 252, 162);">null</span><span>,
</span><span>  </span><span class="hljs-attr">"cispac"</span><span>: </span><span style="color: rgb(211, 99, 99);">1</span><span>,
</span><span>  </span><span class="hljs-attr">"cispoj"</span><span>: </span><span style="color: rgb(211, 99, 99);">114</span><span>,
</span><span>  </span><span class="hljs-attr">"datnar"</span><span>: </span><span style="color: rgb(252, 194, 140);">null</span><span>,
</span><span>  </span><span class="hljs-attr">"datefr"</span><span>: </span><span style="color: rgb(252, 194, 140);">null</span><span>,
</span><span>  </span><span class="hljs-attr">"dateto"</span><span>: </span><span style="color: rgb(252, 194, 140);">null</span><span>,
</span><span>  </span><span class="hljs-attr">"datins"</span><span>: </span><span style="color: rgb(162, 252, 162);">"2022-05-02T13:15:45.000+02:00"</span><span>,</span></code></pre></span></span>
</body>
</html>

It looks like the problematic behaviour is nearby code in MVCFramework.Serializer.JsonDataObjects in TMVCJsonDataObjectsSerializer.TValueToJSONObjectProperty method
```
...
  if AValue.IsEmpty then // this evaluates allways False if there is TNullable* without value set.
  begin
    if AValue.IsArray then
    begin
      AJSONObject.A[AName] := TJDOJsonArray.Create;
    end
    else
    begin
      if MVCSerializeNulls then
      begin
        AJSONObject[AName] := Null;
      end;
    end;
    Exit;
  end;
...
```

I have current Spring library. What is wrong with my code? Thank you.

**Comment by danieleteti** [comment]
To get the desired behaviour you have to use the nullable types from `MVCFramework.Nullables.pas` not them from Spring.

**Comment by Pecaas** [comment]
Perfect! It works. I am sorry that I overlooked used types. Thank you.
