### ISSUE TITLE
Not render JSON empty string or null properties

### ISSUE THREAD

**Issue by tikototh** [danieleteti/delphimvcframework#65]
Hi,

my table contests

| column1 | "this is string" |
| column2 | "" |
| column3 | NULL |

but when call Render(Table) for JSON

the responde only content properties with value 

{
     "column1": "this is a string"
}

I always need all the properties 

{
     "column1": "this is a string",
     "column2": "",
     "column3": null
}

exist any option for this? thanks

**Comment by danieleteti** [comment]
This is the expected behaviour for the older version of Delphi. What's your Delphi version? 
Currently the behaviour is changed and is aligned with your (and all the rest of the world) expectations. Check the test   ```TestDataSetToJSONObjectWithNulls``` in ```FrameworkTestsU.pas```.
