### ISSUE TITLE
JWT authentication failed

### ISSUE THREAD

**Issue by marcelologica** [danieleteti/delphimvcframework#663]
Using the jsonwebtoken example, when we pass the wrong username and password, it does not return the correct http status code (403) but 200, along with an html return.
I'm using repository version of DMVC, Delphi 11.3 patch 1, Windows 11 Pro.
<img width="689" alt="Captura de Tela 2023-05-25 às 13 07 22" src="https://github.com/danieleteti/delphimvcframework/assets/25515866/809ac8a7-4bd5-4be0-9ccb-adadf3598f76">
<img width="1380" alt="Captura de Tela 2023-05-25 às 13 12 00" src="https://github.com/danieleteti/delphimvcframework/assets/25515866/49ccb7c5-ce1f-400b-bc22-83b5b2b02537">

**Comment by danieleteti** [comment]
This (wrong) behavior has been introduced by commit related to https://github.com/danieleteti/delphimvcframework/issues/658
It must be solved in another way.

**Comment by marcelologica** [comment]
Excellent. I'll see if I can help with #658. Thanks.

**Comment by danieleteti** [comment]
Would be great. I'm thinking to change the way Middleware work... but I don't want to break too much code out there
