### ISSUE TITLE
Blob field was not deserializing properly

### ISSUE THREAD

**Issue by thealgorithms10** [danieleteti/delphimvcframework#671]
I am trying to implement object with pictures as Blob - the MySQL column is MEDIUMBLOB. It is working when serializing with Webservice. However, when I want to deserialize the JSON been generated/fetched, the property was at **nil**. I used both TStream and TMemoryStream for the type of the property. Kindly check this concern. I'm using latest 3.3.0-fluorine

Below are the image/screenshot of the concern I've encountered.

![image](https://github.com/danieleteti/delphimvcframework/assets/82137662/5cd215ac-57ff-454a-b9b3-4f659f94e5cd)

**Comment by joaoduarte19** [comment]
Using a TMemoryStream to deserialize a Blob field will work correctly. You have to create the TMemoryStream object at initialization of your class.

```delphi
TClientClass = class
private
  FPicture: TStream;
public
  constructor Create;
  destructor Destroy; override;

  property Picture: TStream read FPicture write FPicture;
end;

implementation

constructor TClientClass.Create;
begin
  FPicture := TMemoryStream.Create;
end;

destructor TClientClass.Destroy;
begin
  FPicture.Free;
end;
```

**Comment by thealgorithms10** [comment]
Ohno! Sorry for that. I forgot that the TMemoryStream/TStream is a class. Hard to find specific reference in this matter due to there were no available samples existed related. Thanks btw! Yes confirmed this is not a bug
