### ISSUE TITLE
Swagger and http protocol

### ISSUE THREAD

**Issue by fastbike** [danieleteti/delphimvcframework#673]
We use a Netscaler device to provide the external endpoint for our public facing APIs. This means we can do clever stuff like have an external address like https://api.example.com/test and internally route it using plain old http to a private hostname of http://api.example.com/test

However, when calling (even setting the protocol to https on the swagger page) a port 80 is added to the calls i.e.
https://api.example.com:80/test

Is there a configuration variable that we can use to prevent the port being added ?

**Comment by fastbike** [comment]
The "offending" line of code is in MVCFramework.Middleware.Swagger.pas
```
procedure TMVCSwaggerMiddleware.DocumentApiSettings(AContext: TWebContext; ASwagDoc: TSwagDoc);
// <snip>
    ASwagDoc.Host := Format('%s:%d', [AContext.Request.RawWebRequest.Host, AContext.Request.RawWebRequest.ServerPort]);
// </snip>
```

I can think of a number of ways to proceed:
- provide an additional param on the constructor for the port
- provide a property on the object to set up
- provide a function to set it (that returns the object for chaining)

I favour the third way

**Comment by fastbike** [comment]
Changes would be
1. to change the class definition
```
  TMVCSwaggerMiddleware = class(TInterfacedObject, IMVCMiddleware)
  private
//<snip>
    fExternalPort: Integer;
  public
//<snip>
    function SetExternalPort(APort: Integer):IMVCMiddleware;
  end;

```
2. new method is
```
function TMVCSwaggerMiddleware.SetExternalPort(APort: Integer): IMVCMiddleware;
begin
  Result := Self;
  fExternalPort := APort;
end;
```
3. And the amended method is
```
procedure TMVCSwaggerMiddleware.DocumentApiSettings(AContext: TWebContext; ASwagDoc: TSwagDoc);
var
  lSwagSchemes: TSwagTransferProtocolSchemes;
begin
  ASwagDoc.Host := fHost;
  if ASwagDoc.Host.IsEmpty then
  begin
   // change single line to these 4 lines
    if fExternalPort = 0 then
      ASwagDoc.Host := Format('%s:%d', [AContext.Request.RawWebRequest.Host, AContext.Request.RawWebRequest.ServerPort])
    else
      ASwagDoc.Host := Format('%s:%d', [AContext.Request.RawWebRequest.Host, fExternalPort]);
  end;
// end of changes
```

**Comment by joaoduarte19** [comment]
I'm working on refactoring the Swagger documentation generator to make it more customizable.

**Comment by danieleteti** [comment]
Hi guys, since 3.4.0-neon we have dotEnv support and any piece of code ca use it. 
Would be enough to put something like

`swagger.baseurl = http://localhost:1111`

to allow the filter (middleware) to be aware of such configuration even without recompilation.

Check the dotEnv support and let me know what you think.

**Comment by fastbike** [comment]
Thanks, I've started looking at the dotenv ideas. Interesting reading at linked site https://12factor.net/
I'm part way there :)

**Comment by danieleteti** [comment]
Any news about this?

**Comment by fastbike** [comment]
The dotEnv idea is interesting.  Years ago we built a wrapper around the TIniFile class ... and a global method pointer to access it.
```
  ISettings = interface
    ['{34E13342-935A-4A07-A2FC-7C4740249DC5}']
    function ReadString(const Section, Ident, Default: string): string;
    function ReadBool(const Section, Ident: string; const Default: Boolean): Boolean;
    function ReadInteger(const Section, Ident: string; const Default: Integer): Integer;
    function ReadDouble(const Section, Ident: string; const Default: Double): Double;
    function ReadISODate(const Section, Ident: string; const Default: TDateTime): TDateTime;
    function ReadISODateTime(const Section, Ident: string; const Default: TDateTime): TDateTime;
    function ReadISOTime(const Section, Ident: string; const Default: TTime): TTime;
    procedure WriteString(const Section, Ident, Value: string);
    procedure WriteBool(const Section, Ident: string; const Value: Boolean);
    procedure WriteInteger(const Section, Ident: string; const Value: Integer);
    procedure WriteDouble(const Section, Ident: string; const Value: Double);
    procedure WriteISODate(const Section, Ident: string; const Value: TDateTime);
    procedure WriteISODateTime(const Section, Ident: string; const Value: TDateTime);
    procedure WriteISOTime(const Section, Ident: string; const Value: TTime);
    function SectionExists(const Section: string): Boolean;
    procedure ReadSection(const Section: string; Strings: TStrings);
    procedure ReadSections(Strings: TStrings); overload;
    procedure ReadSections(const Section: string; Strings: TStrings); overload;
    procedure ReadSubSections(const Section: string; Strings: TStrings; Recurse: Boolean = False);
    procedure ReadSectionValues(const Section: string; Strings: TStrings);
    procedure EraseSection(const Section: string);
    procedure DeleteKey(const Section, Ident: string);
    function ValueExists(const Section, Ident: string): Boolean;
    procedure SetFileName(AFileName: string);
  end;

var
  Settings: function: ISettings = nil;
```
We then provided an implementation for Windows which used the INI file format, and for Mac which used plist (xml) files.
This allowed us to write portable code like
``` 
var EmailServer: string;
begin
  EmailServer := Settings.ReadString('Global','EmailServer','imap://gmail.com');
// etc
```
which would read the settings for the Email Server from the INI file, substituting a value id not explicitly set. And not having to think about how the underlying OS stored the data.
We had the implementation default to looking for values form a file with the same root name as the exe/dll but with an .INI / .plist suffix.  This works very well and has been in our code base for 15+ years, so I can see the pattern.
It still does not remove the need to curate the (often small) differences between environments which we have solved with a simple merge step as part of our build process.
It seems the web world is often playing catchup and reinventing solutions that previous generations of developers handled elegantly :)

**Comment by fastbike** [comment]
Anyway, back to the problem at hand.
Because my code is not available for reuse (IP issues) so I would suggest that the refactor I suggested above would suffice (although it could be set as a simple property, rather than a function that returns the Middleware interface - not sure what I j=had in mind then) and is called by code something like the following
```
    FMVC.AddMiddleware(TMVCSwaggerMiddleware.Create(FMVC, lSwagInfo, '/api/swagger.json').ExternalPort
    := Settings.ReadInteger('Swagger','ExternalPort', 0);
// or the equivalent using dotEnv
    FMVC.AddMiddleware(TMVCSwaggerMiddleware.Create(FMVC, lSwagInfo, '/api/swagger.json').ExternalPort
    :=  dotEnv.Env('Swagger.ExternalPort', 0);
```
With the implementation checking to see if a non zero port has been supplied.
Or provide the complete URL if you have some other levels of redirection, maybe to a test instance etc.

@joaoduarte19  what do you think - does this fit in with your refactor ?
