### ISSUE TITLE
The problem with aBody in the Post request

### ISSUE THREAD

**Issue by wuhao13** [danieleteti/delphimvcframework#678]
```
  Clt := TMVCRESTClient.NEW.BaseURL('http://coolaf.com');// NewRESTClt();
  CltRst := Clt.Post('tool/params?A=1',Format('p=ptest&p=test2',[FEid,FUserName,FPassWord]),'application/x-www-form-urlencoded');
  Writeln(CltRst.Content);
```
request：

```
request params

GET:A=1

POST:

cookie:


Header:
Host:127.0.0.1:1020
Content-Length:0
Content-Type:application/x-www-form-urlencoded;charset=utf-8
User-Agent:DelphiMVCFramework RESTClient/3.4.0-neon-beta
X-Forwarded-For:221.214.*.*
X-Real-Ip:221.214.*.*
Wh_l:zh
Connection:upgrade
Accept:*/*
Accept-Encoding:gzip,deflate
```
Why the server doesn't seem to receive aBody?

**Comment by wuhao13** [comment]
`Clt.Resource('/tool/params?A=2').AddBodyFieldURLEncoded('P','TXT').Post.Content;`
I can add post information by using AddBodyFieldURLEncoded, why is this?

**Comment by fastbike** [comment]
> Why the server doesn't seem to receive aBody?

Because of the content type. _application/x-www-form-urlencoded_ requires the body to be formatted as key/value pairs.
Your body makes no sense, you've got a Format statement that does nothing and have repeated the key for both values.
Have you traced into the code ?

P.S.
Take a look at the specs
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST

**Comment by wuhao13** [comment]
@fastbike That piece of code is just a demonstration, the actual code looks like this, I think it should be submittable.
`
var
  CltRst:IMVCRESTResponse;
  Clt:IMVCRESTClient;
begin
  FData := TSecretByUserData.Create;
  Clt := NewRESTClt();

  CltRst := Clt.Resource(URI)
                             .AddBodyFieldURLEncoded('eid',FEid)
                             .AddBodyFieldURLEncoded('userName',FUserName)
                             .AddBodyFieldURLEncoded('password',FPassWord)
                             .Post;
  //oldcode↓↓see it
  // CltRst := Clt.Post(URI,Format('eid=%s&userName=%s&password=%s',[FEid,FUserName,FPassWord]),'application/x-www-form-urlencoded');
  CltRst.BodyFor(FData);
`

**Comment by wuhao13** [comment]
`Format('eid=%s&userName=%s&password=%s',[FEid,FUserName,FPassWord])` should be equivalent to using .AddBodyFieldURLEncoded, I don't know where the problem is, at least now using .AddBodyFieldURLEncoded can solve my problem And it looks much more elegant than format.
