### ISSUE TITLE
SelectByNamedQuery created exception when using with Microsoft SQL Server

### ISSUE THREAD

**Issue by blitt001** [danieleteti/delphimvcframework#692]
Currently exploring SelectByNamedQuery functionallity and the ActiveRecord. 

My application is generating an exception : [FireDAC][Phys][ODBC][Microsoft][ODBC Driver 18 for SQL Server]Invalid cursor position
In order to identify if the problem is related to my application, I did a test with the example application activerecord_showcase

By using that application also Invalid cursor positions exceptions are generated.

What is the cause of this problem ?

**Comment by danieleteti** [comment]
It seems to be a problem with forwardonly cursors on MSSQLServer. Please, clone the repo version and redo your tests. Let me know, please.

**Comment by blitt001** [comment]
I did some tests and application is now running without issues.
