### ISSUE TITLE
TMVCActiveRecordController - refresh=true

### ISSUE THREAD

**Issue by drcrck** [danieleteti/delphimvcframework#694]
Hi, there's a bug in CreateEntity , if is passed refresh=true.
result data is: 
```
{
    "classname": "EInvalidPointer",
    "detailedmessage": "",
    "apperrorcode": 0,
    "items": [],
    "statuscode": 500,
    "reasonstring": "Internal Server Error",
    "message": "Invalid pointer operation",
    "data": null
}

```
it seems when last line "lAr.free" is called , lAr han been already destroyed by RenderStatusMessage method.

**Comment by thealgorithms10** [comment]
Still it occurs in latest release. 
I use btw a DataModule - with a AdoDataSet, with MySQL 8.0
It occurs when freeing the DataModule after dataset been used.

![image](https://github.com/user-attachments/assets/1afe4d02-8c9e-41ab-ae50-6e2d3847eacd)
