### ISSUE TITLE
[HOW TO] Running on another port - via commandline switch.

### ISSUE THREAD

**Issue by Microcom-Bjarne** [danieleteti/delphimvcframework#696]
This is something I've been using for quite some time.

And it works in the latest 3.4 - neon too :)

How:
Replace the first few lines of code in the RunServer procedure with the following.

```
procedure RunServer(APort: Integer);
var
  LServer: TIdHTTPWebBrokerBridge;
  lPort: string;
begin
  if FindCmdLineSwitch('port', lPort) then
    APort := lPort.ToInteger;
```
Then you can start your api with "MyNiceEndpoint.exe -port 8037"

Hope this can be of use for others.

**Comment by danieleteti** [comment]
Nice snippet. With 3.4.0-neon+ you can achieve the same using `.env` too.
With the next release 3.4.1-sodium (mostly a bug fix release) it works also using the following approach.


```batch
C:\Projects\Win32\Debug>set dmvc.server.port = 9999 & Project6.exe
** DMVCFramework Server ** build 3.4.0-neon
Listening on port 9999
CTRL+C to shutdown the server
```

**Comment by Microcom-Bjarne** [comment]
And that is very nice. But we have several endpoints running as services - and sometimes it's just easier to change the startup cmdlineswitch directly.
