### ISSUE TITLE
Character % doesn't work in URL anymore

### ISSUE THREAD

**Issue by alberteije** [danieleteti/delphimvcframework#697]
Hi guys, I'm using this scheme to manager filters at server side: https://github.com/nestjsx/crud/wiki/Requests, I have adapted it to my Delphi Server. I can't change that because I have a client app made in Flutter that consumes some Server Applications (including my Delphi Server).

So, in the client side I mount the URL like that: 

http://localhost:8085/my-endpoint/?filter=name||$cont||%

In this case it should brings all records from the server. Of course there is a handle on server side to limit the amount of records.

It was working properly in some old version of DMVC. I updated to Neon version and now get this error:

Exception class EConvertError with message ''$' is not a valid integer value'

But the problem is not about the "$" character, so If I use the follow URL it works great:

http://localhost:8085/my-endpoint/?filter=name||$cont||john

However, if I try to escape the "$" like that:

http://localhost:8085/my-endpoint/?filter=name||\$cont||%

Then I get 2 errors:

Exception class EConvertError with message ''$' is not a valid integer value'
Exception class EConvertError with message 'Error decoding URL style (%XX) encoded string at position 27'

Any idea?

**Comment by danieleteti** [comment]
Hi, can you write how the action is declared?

**Comment by alberteije** [comment]
Yes, sure. It is like that:

    [MVCDoc('Returns a list of objects')]
    [MVCPath()]
    [MVCHTTPMethod([httpGET])]
    procedure GetList(Context: TWebContext);


procedure TTributOperacaoFiscalController.GetList(Context: TWebContext);
var
  FilterWhere: string;
  FilterObj: TFilter;
begin
  FilterWhere := Context.Request.Params['filter'];
  try
    if FilterWhere = '' then
    begin
      Render<TModel>(TService.GetList);
    end
    else begin
      FilterObj := TFilter.Create(FilterWhere);
      Render<TModel>(TService.GetListFilter(FilterObj.Where));
    end;
  except
    on E: EServiceException do
    begin
      raise EMVCException.Create
        ('Error [GetList] - Exception: ' + E.Message, E.StackTrace, 0, 500);
    end
    else
      raise;
  end;
end;

**Comment by fastbike** [comment]
Is this similar ?
https://github.com/danieleteti/delphimvcframework/issues/513

**Comment by alberteije** [comment]
I don't think so, because I'm expecting a parameter there and I have no problems with "$" character.

**Comment by danieleteti** [comment]
`$` is a reserved char for URL. Old versions allows to use it but it was an error.
Check this
https://developers.google.com/maps/url-encoding?hl=it#:~:text=All%20characters%20to%20be%20URL,to%20their%20UTF%2D8%20character.

The best think you can do is to encode the `$` and try it.

**Comment by alberteije** [comment]
Yes, it solved. Now I can consume servers like that:

http://localhost:8085/my-endpoint/?filter=name||\$cont||%25

I've tested on Delphi MVC Server and PHP server and worked great.

Thanks a lot
:)
