### ISSUE TITLE
Error: No mapping for the Unicode character exists in the target multi-byte code

### ISSUE THREAD

**Issue by tibaros** [danieleteti/delphimvcframework#707]
I am consuming a rest api that returns a .zip file. I use the DelphiMVC client.

```delphi
var
  RESTResponse: IMVCRESTResponse;
begin
  RESTResponse := TMVCRESTClient
                             .New
                             .BaseURL(url)
                             .AddHeader('Authorization','Bearer '+api_token)
                             .AddHeader('Content-Type', 'application/zip')  
                             .AddHeader('Accept', '*/*' )
                             .AddHeader('Accept-Encoding', 'gzip, deflate, br' )
                             .Get;

end;
```

It does not complete the process and gives the following error:  No mapping for the Unicode character exists in the target multi-byte code

I have used another client (RESTRequest4Delphi) and there are no problems.

**Comment by danieleteti** [comment]
This code works correctly. Can you test please? Which dmvcframework version are you using?

```delphi
uses
  MVCFramework.RESTClient;

procedure TForm13.Button1Click(Sender: TObject);
var
  RESTResponse: IMVCRESTResponse;
  lURL: String;
begin
  lURL := 'http://corsi.bittimeprofessionals.it/downloads/public/test.zip';
  RESTResponse := TMVCRESTClient
                             .New
                             .BaseURL(lURL)
                             .AddHeader('Content-Type', 'application/zip')
                             .AddHeader('Accept', '*/*' )
                             .AddHeader('Accept-Encoding', 'gzip, deflate, br' )
                             .Get;
  var lFile := TFileStream.Create('test.zip', fmCreate or fmOpenWrite);
  try
    RESTResponse.SaveContentToStream(lFile)
  finally
    lFile.Free;
  end;
end;
```

**Comment by tibaros** [comment]
Dear Danielle:The code is exactly the same as the one I use, the only difference is that I do a GET to an HTTPS url.I use the latest version and I have tried the previous ones and it is the same. I am using Delphi 11.1 but I have tried it in Delphi 10.3 and Delphi 10.4 and the same result.The code you sent me works perfectly because the url is not HTTPS.Thank you for your message, a big hug from Peru.
-- 
Tito Esteban Rojas CruzDesarrollador de Software Teléfonos: +51 1 6829995, ***@***.***
 

    El sábado, 4 de noviembre de 2023, 12:18:48 PET, Daniele Teti ***@***.***> escribió:  
 
 


This code works correctly. Can you test please? Which dmvcframework version are you using?
uses
  MVCFramework.RESTClient;

procedure TForm13.Button1Click(Sender: TObject);
var
  RESTResponse: IMVCRESTResponse;
  lURL: String;
begin
  lURL := 'http://corsi.bittimeprofessionals.it/downloads/public/test.zip';
  RESTResponse := TMVCRESTClient
                             .New
                             .BaseURL(lURL)
                             .AddHeader('Content-Type', 'application/zip')
                             .AddHeader('Accept', '*/*' )
                             .AddHeader('Accept-Encoding', 'gzip, deflate, br' )
                             .Get;
  var lFile := TFileStream.Create('test.zip', fmCreate or fmOpenWrite);
  try
    RESTResponse.SaveContentToStream(lFile)
  finally
    lFile.Free;
  end;
end;

**Comment by danieleteti** [comment]
Hi Tito, can you provide a reproducible self contained example?

Greeting from Rome :-)

**Comment by tibaros** [comment]
I attach a complete demo where the error is shown.
Greetings,
[demo.zip](https://github.com/danieleteti/delphimvcframework/files/13257938/demo.zip)
