### ISSUE TITLE
The TUserPasswordChecker class does not exist

### ISSUE THREAD

**Issue by mohamadkh** [danieleteti/delphimvcframework#708]
In chapter 11 of the book
There is a class called TUserPasswordChecker that is not defined anywhere.
It is not present in the framework examples either.
What is the structure of this class?

**Comment by danieleteti** [comment]
Hi, the `TUserPasswordChecker` in an entity defined in `EntitiesU.pas`.
Check the official repository (just updated for dmvcframework-3.4.1.sodium).

https://github.com/danieleteti/dmvcframeworktheofficialguideexamples/blob/main/municipal_library_api_ver_4/EntitiesU.pas#L193
