### ISSUE TITLE
Error when compile to Linux

### ISSUE THREAD

**Issue by fabriciohausman** [danieleteti/delphimvcframework#709]
Hi, i'm trying compile MVC Framework to Linux Target but doesn't work.
**This message was showed by Dephi compiler: "[DCC Error] E2597 C:\Program Files (x86)\Embarcadero\Studio\20.0\bin\ld-linux.exe: error: cannot find -lcurl"**
I'm using Delphi 10.3 and the Linux SDK is Ubuntu 20.04.
This error occurrs when I try compile the Logger Package. 
Somebody help me?

**Comment by isysoftware** [comment]
Which version of RadStudio are you using?

**Comment by fabriciohausman** [comment]
10.3 update 3

**Comment by isysoftware** [comment]
Professional? Architect? Ultimate?

**Comment by fabriciohausman** [comment]
Architect

**Comment by fastbike** [comment]
What searches have you done ? e.g.
https://www.google.com/search?q=lcurl
returns loads of similar errors
