### ISSUE TITLE
Does not compile in Delphi Seattle

### ISSUE THREAD

**Issue by dsonda** [danieleteti/delphimvcframework#71]
I've updated the framework to the last version and now it's not compiling any more.
It seems to be after commit https://github.com/danieleteti/delphimvcframework/commit/03d904185b6114470cff1d08fbb9478fb7738d6e.
I'm using Delphi 10 Seattle.

Errors:
[dcc32 Error] MVCFramework.pas(1650): E2010 Incompatible types: 'Byte' and 'AnsiChar'
[dcc32 Error] MVCFramework.pas(1656): E2250 There is no overloaded version of 'GetString' that can be called with these arguments

At unit MVCFramework.pas:

function TMVCWebRequest.Body: string;
var
Encoding: TEncoding;
Buffer: TArray<Byte>;
I: Integer;
begin
if (FBody = '') then
begin
if (FCharset = '') then
begin
SetLength(Buffer, 10);
for I := 0 to 9 do
Buffer[I] := FWebRequest.RawContent[I];
TEncoding.GetBufferEncoding(Buffer, Encoding, TEncoding.Default);
SetLength(Buffer, 0);
end
else
Encoding := TEncoding.GetEncoding(FCharset);
FBody := Encoding.GetString(FWebRequest.RawContent);
end;
Result := FBody;
end;

**Comment by danieleteti** [comment]
Closed in 2.1.4 (beryllium)
