### ISSUE TITLE
Model with multiple Primary Key.

### ISSUE THREAD

**Issue by intracloud** [danieleteti/delphimvcframework#712]
I have a model to represent a relationship MN between two tables, where two attributes are primary key

```
  [MVCNameCase(ncLowerCase)]
  [MVCTable('tableName')]
  TAlergiasAlimentos = class(TMVCActiveRecord)
  private
    [MVCTableField('idFirstTable', [foPrimaryKey])]     
    fID_ALERGIAS: Integer;
    [MVCTableField('idSecondTable', [foPrimaryKey])]
    fID_ALIMENTOS: Integer;

    fALERGIA: String;
    fALIMENTO: String;
  public
    constructor Create; override;
    destructor Destroy; override;
    property ID_ALERGIAS: Integer read fID_ALERGIAS write fID_ALERGIAS;
    property ID_ALIMENTOS: Integer read fID_ALIMENTOS write fID_ALIMENTOS;

  end;
```

but when instance object crash with this exception
**No fields defined [HINT] Use MVCTableField in private fields (xxx)**

if only one attribute are foPrimaryKey don't crash.

Thanks for all.

**Comment by danieleteti** [comment]
Currently a model can only have one field in the PK.
If you really neel multiple fields as primary key, you can sponsor the functionality in [PATREON](https://www.patreon.com/delphimvcframework)

**Comment by intracloud** [comment]
hi daniel,

By definition M:N relationships create a new table where the primary key of that table is the primary key of the first and second tables.

In my database model I have all these M:N relationships like this.

When you tell me that I can sponsor the function, how can I do it? How soon could DelphiMVCFramework have this new functionality?

Thanks for your time,

**Comment by danieleteti** [comment]
Please, contact me at d(dot)teti(at)bittime(dot)it

**Comment by danieleteti** [comment]
Any news?
