### ISSUE TITLE
ActiveRecord: TableName property readonly.

### ISSUE THREAD

**Issue by drcrck** [danieleteti/delphimvcframework#714]
Hi, in last version TableName property was modified to read only.  In my use case, i need to change dynamically table name during the creation of my object, due to the context of my app.
 (table's structure are identically but with different prefix to manage many deposit)

es: 

```delphi
constructor TeF15Anag.Create;
begin
  inherited;
  Self.TableName :=    TNome_Tabella.Singolo_f15ANAG ;  <------- i need this,  
end;
```

Now in not more possible.
there's another way to do this or is possibile to restore tableName in write mode? 
thanks

**Comment by danieleteti** [comment]
TableName Is now read-only, as you noticed. What we're trying to add is to pass the TableName as (optional) constructor parameter. Does this solve your issue?

**Comment by drcrck** [comment]
mm, no not really :( 
because now it can works well with TMVCActiveRecordController without any external parameters.

**Comment by danieleteti** [comment]
Can you explain your latest comment? The parameter is an addition to the current behavior, so what work today will continue to work.

**Comment by drcrck** [comment]
because my code is inside all my ActiveRecord classes, in the constructor!  
but , maybe, I can access directly to fTableMap.fTableName  :)  i see now that's protected, no private :)

**Comment by danieleteti** [comment]
I'm working on a solution valid for all the cases. PLease, wait for an update and redo your tests, please.

**Comment by danieleteti** [comment]
Please, update the repo and check hot the `GetCustomTableName` method works.
https://github.com/danieleteti/delphimvcframework/commit/d68b102d14dae83e0d931586d6cac0122cdb5630#diff-ccd4b1a1370e0101769b2624049548af36e8e3d55d736864033aa16ba06019a0R149

`TMVCActiveRecord.GetCustomTableName` allows to overwrite the tablename defined in the `MVCTableName` attribute. Just overwrite the method in descendant classes and return the tablename to use for the current instance.

**Comment by danieleteti** [comment]
any news?

**Comment by drcrck** [comment]
Hi Daniele :) 
With previous version i just workaround in this way :

```
constructor TeMYACTIVERECORDCreate;
begin
  inherited;
  Self.fTableMap.fTableName := CRRECT_TABLE_NAME ; 
end;
```

I tried now woth your new idea , and it works well :)
It's more transparent solution,  thanks :) :)

**Comment by danieleteti** [comment]
Great! Thank you for your feedback
