### ISSUE TITLE
[Question] Alternative to FireDac usage for RPC calls to DB Query

### ISSUE THREAD

**Issue by Basti-Fantasti** [danieleteti/delphimvcframework#719]
Does anyone know of an alternative to the Firedac drivers which are used e.g. in the **articles_crud** sample project to send the Dataset directly to the client as a Memtable via JSONRPC?

AFAIK the zeos components do not have a memtable component

Any help is appreciated

**Comment by danieleteti** [comment]
You can render any tdataset descendants.

DMVCFramework as whole is agnostic regarding the db access. The only part
which is, currently, tied to firedac is tmvcactiverecord.

Il ven 15 dic 2023, 11:37 Bastian ***@***.***> ha scritto:
