### ISSUE TITLE
JsonToDataset error

### ISSUE THREAD

**Issue by RDP1974** [danieleteti/delphimvcframework#726]
I'm trying to convert a json string to a fdmemtable

```delphi
function JsonToMemTable(const S: string): TFDMemTable;
var
  lSer: TMVCJsonDataObjectsSerializer;
  lJsn: TJDOJsonObject;
begin
  Result := TFDMemTable.Create(nil);
  lJsn := StrToJSONObject(S);
  lSer := TMVCJsonDataObjectsSerializer.Create;
  try
    lSer.JsonObjectToDataSet(lJsn, Result, [], TMVCNameCase.ncLowerCase);
  finally
    lSer.Free;
    lJsn.Free; // testare
  end;
end;
```
I get error there: (invalid character in string at 1,339)

```delphi
function StrToJSONObject(const aString: String; ARaiseExceptionOnError: Boolean = False): TJsonObject;
begin
  Result := MVCFramework.Utils.StrToJSONObject(aString, ARaiseExceptionOnError);
end;
```

however the string is correct JSON and works fine with other serializer tested
how to solve?

**Comment by danieleteti** [comment]
Can you provide a reproducible example? Also, the dataset structure but be
defined before load JSON. If you want to create structure too you need to
use metadata JSON.

Il gio 11 gen 2024, 21:52 Roberto Della Pasqua ***@***.***>
ha scritto:
