### ISSUE TITLE
Method EMVCActiveRecordNotFound.AfterConstruction Variable FHTTPStatusCode is undeclared

### ISSUE THREAD

**Issue by HPCanonsson** [danieleteti/delphimvcframework#727]
I updated to DelphiMVCFramework 3.4.1-sodium. The compiler Delphi 12.0 gives the Error E2003 for FHttpErrorCode when building activerecord_showcase.

Error:
```
procedure EMVCActiveRecordNotFound.AfterConstruction;
begin
  inherited;
  FHTTPStatusCode := http_status.NotFound;
end;
```

Reason:
The field is declared as protected in the parent class.
```
 EMVCException = class(Exception)
  protected
    FHttpErrorCode: UInt16;
```

**Comment by danieleteti** [comment]
I cannot reproduce the problem. Also, check your description because it seems contraddictory. Thanks
