### ISSUE TITLE
Can't compile in Delphi 10.2  MVCFramework.ActiveRecord;  AddTableMap method

### ISSUE THREAD

**Issue by jairgza** [danieleteti/delphimvcframework#728]
When compiling package dmvcframeworkRT for Delphi 10.2 I got an error on method TMVCTableMapRepository.AddTableMap on the line 4546

`if not fTableMapDict.TryAdd(lKey, TableMap)`

It seems that  TObjectDictionary has no TryAdd method on my Delphi version.

I modified that line like a previous version "fTableMapDict.Add " and all compile.

Regards

**Comment by mivimicrocom** [comment]
I have same problem, and I have also for now just modified the previous version.

**Comment by danieleteti** [comment]
Is `fTableMapDict.TryGetValue` available in Delphi 10.2?

**Comment by isysoftware** [comment]
https://docwiki.embarcadero.com/Libraries/Tokyo/en/System.Generics.Collections.TDictionary.TryGetValue

**Comment by danieleteti** [comment]
Please, check the repo version.
