### ISSUE TITLE
Possible wrong http error code when authenticating

### ISSUE THREAD

**Issue by zaniniflz** [danieleteti/delphimvcframework#732]
Perhaps the authentication middleware is returning 403 (forbidden) incorrectly.
In this code snippet the error 401 (not authorized) should be returned, as the user's identity is not yet known.

https://github.com/danieleteti/delphimvcframework/blob/cc5789d56e4bc8c5e11b8c3a653d6bb92b6207ac/sources/MVCFramework.Middleware.JWT.pas#L419C8-L424

**Comment by danieleteti** [comment]
More info here
https://auth0.com/blog/forbidden-unauthorized-http-status-codes/
