### ISSUE TITLE
Feature Request: Mustache as render engine

### ISSUE THREAD

**Issue by nigrosimone** [danieleteti/delphimvcframework#75]
just a feature request, using Mustache as render engine https://github.com/synopse/dmustache for render html pages.

Thanks!

**Comment by danieleteti** [comment]
It's already avialable since last year or so :-)
Check serversidepages sample.

**Comment by nigrosimone** [comment]
Hi @danieleteti i have self-closed this issue after i found this example!

thanks for your framework, very great!

sorry for my poor english!

Ciao!

**Comment by danieleteti** [comment]
Ok, 
Ciao.

DT
