### ISSUE TITLE
Question about hosting project and SSL certificate

### ISSUE THREAD

**Issue by giorgioindelicato11** [danieleteti/delphimvcframework#756]
Hi, I apologize in advance if I am asking this question in the wrong way or in the wrong place, but surely i am missing some piece of information. 

I developed the back-end for my mobile app using DMVCFramework that let users login with email and password, get a JWT and make requests with it to access resources (such as Products information, registered in MySQL Database). The project compiles in .exe file, running on a specific port (in my case 4435), but i know i may need to compile as dll (for Windows server). 

I own a DynDNS subscription with a domain configured in DDNS on my router and port - forwarding rule on port 4435, so my the url for my requests looks like this 

 `my.dyndnstest.it:4435/api/products`

I configured my project to use SSL (because i want to use HTTPS in my mobile app) following the procedures listed on `delphimvcframework/samples/sslserver/` obtaining .pem files signed as localhost. 

My question is : where do i need to host this app in order to be reachable and usable from mobile app? When i try to make requests from mobile , i receive the error

>  java.security.cert.CertPathValidatorException: Trust anchor for certification path not found. 

Who is responsibile for the creation of SSL certificate ? Should I get digicert/ comodossl and use them in the project and/or on IIS ? 

Developing 
on Windows 10 
with Delphi 12 
with DMVC Framework : 3.4.2-magnesium RC1

**Comment by danieleteti** [comment]
Hi, this is a configuration problem. What I can suggest is to use CaddyServer as reverse proxy and let it to handle the certificate.
