### ISSUE TITLE
 "Runtime error 236 at 506D0BA6" in  dmvcframeworkDT only D12

### ISSUE THREAD

**Issue by marcosnielsen** [danieleteti/delphimvcframework#759]
Hy

In Delphi 12, when trying to install the package ".\packages\d120\dmvcframeworkDT.dproj" I do receive the error "Runtime error 236 at 506D0BA6" and Ide close.

https://github.com/danieleteti/delphimvcframework/assets/24677471/5c82ddb9-14f3-4078-88db-3c8940f45ed3

can help?

i Try install to **"rMyCleanConfig"** 
with "C:\Program Files (x86)\Embarcadero\Studio\23.0\bin\bds.exe" -pDelphi -rMyCleanConfig

**Comment by danieleteti** [comment]
Sorry, I cannot reporoduce it in any way. DO you have abother machine to do the test? Did you use the latest repo version?

**Comment by marcosnielsen** [comment]
Yes I understand,
That's why I sent the video showing what happened in the IDE

Did you use the latest version of the repository?
Yes!

The worst part is that this error message does not show a trace or a log to identify whether it is a Windows DLL or an access violation in the IDE.

it just appears.

I will test this same installation process on a VM with Windows 11 PT-BR (Brazilian Portuguese) and report the result here.

Thank you for your time spent on this issue,

**Comment by marcosnielsen** [comment]
## 🛠️ Technical Feedback – *Runtime error 236 at %s* when using multiple RAD Studio versions

**Hi @danieleteti,**

I'd like to share some feedback that may help others encountering the following error:

> **"Runtime error 236 at %s"**

### ✅ Scenario

I had **two versions of RAD Studio** installed on the same machine:
- **Delphi 11 (Alexandria)**
- **Delphi 12 (Athens)**

While installing and using components that rely on `.bpl` packages, I started getting the runtime error mentioned above.

### 🧩 Identified Cause

After investigating, I discovered that the issue was related to the **order of paths** in the Windows `PATH` environment variable.

RAD Studio installers **automatically add different directories** to the `PATH` variable depending on the installed version:

- Paths for Delphi 11 BPLs
- Paths for Delphi 12 BPLs

This mix causes conflicts when loading libraries from different versions, resulting in runtime errors.

### 🛠️ Applied Solution

I manually adjusted the `PATH` environment variable to **prioritize the directories of the version I'm actively using** (in this case, Delphi 12).

After correcting the order of the paths, both installation and execution worked correctly.

### 📷 Illustrative Screenshots

#### Conflicting `PATH` environment setup:
![Image 1](https://github.com/user-attachments/assets/062b023e-3925-4300-9b3c-8458ddb0a00e)

#### Incorrect directory order:
![Image 2](https://github.com/user-attachments/assets/2504616c-e27d-409d-bd86-c8ea0a796307)

#### Corrected path order (manually adjusted):
![Image 3](https://github.com/user-attachments/assets/69edc892-7ef8-4ed2-87ec-35de88a712f5)

---

### 💡 Suggestion

It would be great if the RAD Studio installers:

- Avoided adding paths from different versions to the global `PATH` environment variable by default, or  
- At least warned users about potential conflicts when multiple versions are installed
