### ISSUE TITLE
activerecord under the hood

### ISSUE THREAD

**Issue by RDP1974** [danieleteti/delphimvcframework#768]
hi,
can I ask, the pipeline of tactiverecord under the hood is using firedac?
Do you create a connection, transaction, query for each call?
Do you use pooled capability of the firedac?
Using pooling you can avoid the time in connecting to the db, usually a bottleneck.
In fdquery you can set readonly and requestlive off.
This will enhance the speed on rendering from sql select queries.

Example:

procedure InitPool;
var
  oParams: TStrings;
begin
  oParams := TStringList.Create;
  oParams.Add('DriverID=MYSQL');
  oParams.Add('CharacterSet=utf8');
  oParams.Add('Password= ); 
  oParams.Add('Server=);
  oParams.Add('Database=');
  oParams.Add('Pooled=True');
  oParams.Add('POOL_CleanupTimeout=3600000');
  oParams.Add('POOL_ExpireTimeout=600000');
  oParams.Add('POOL_MaximumItems=200');
  FDManager.Close;
  while FDManager.State <> dmsInactive do Sleep(0);
  FDManager.Open;
  FDManager.AddConnectionDef('MySQL_Pooled', 'MySQL', oParams);
  oParams.Free;
end;

constructor TDB.Create;
begin
  inherited;
  DBConn := TFDConnection.Create(nil);
  DBConn.ConnectionDefName := 'MySQL_Pooled';
  DBConn.LoginPrompt := False;
  DBConn.FetchOptions.Unidirectional := True;
  DBConn.UpdateOptions.RequestLive := False;
  DBTrans := TFDTransaction.Create(nil);
  DBTrans.Connection := DBConn;
  DBConn.Transaction := DBTrans;
  DBConn.UpdateTransaction := DBTrans;
  DBQuery := TFDQuery.Create(nil);
  DBQuery.Connection := DBConn;
  DBQuery.Transaction := DBTrans;
  DBQuery.UpdateTransaction := DBTrans;
  DBQuery.FetchOptions.Unidirectional := True;
  DBQuery.UpdateOptions.RequestLive := False;
..

**Comment by danieleteti** [comment]
Connections are handled by firedac definitions. MVCActiveRecord doesn't create connections, just use them. 
Regarding the fdquery configuration, many optimization are already in place. Did you check the current code?

`DBQuery.FetchOptions.Unidirectional := True;` should be already in place since years
`DBQuery.UpdateOptions.RequestLive := False;` has been applied.

**Comment by danieleteti** [comment]
The FDQuery factory configure its result as shown [here](https://github.com/danieleteti/delphimvcframework/blob/master/sources/MVCFramework.ActiveRecord.pas#L4804)
