### ISSUE TITLE
Disable default log for a single route?

### ISSUE THREAD

**Issue by Microcom-Bjarne** [danieleteti/delphimvcframework#774]
Hi.

Does anyone know if I can disable logging to the default - dmvcframwork log file - for a single route?
Looking at the example customlogger .... try add another route to the existing endpoint - "nolog" (GET) ... that does not log anything.

Can this be done? Or must it be implemented different?

**Comment by danieleteti** [comment]
You can create your custom logger and then pass it to the LoggerPro Proxy (check https://github.com/danieleteti/delphimvcframework/blob/master/lib/loggerpro/LoggerPro.Proxy.pas)

**Comment by Microcom-Bjarne** [comment]
So - I cannot disable log for a route (1 endpoint on a controller with multiple).
But I can setup an entirely new log - and then avoid logging for that single endpoint.

Is that correct?

**Comment by danieleteti** [comment]
If you are on some stable versions, yes. This is the only way.

The repo version contains a new approach which uses the new `TLogWriterDecorator`. Please, check this sample project https://github.com/danieleteti/delphimvcframework/tree/master/samples/customlogger
