### ISSUE TITLE
Error in MySQL8.0 when using ActiveRecordMiddleware 

### ISSUE THREAD

**Issue by thealgorithms10** [danieleteti/delphimvcframework#785]
I encountered the ODBC 8.0 error when using ActiveRecordMiddleware 
![image](https://github.com/user-attachments/assets/b18cfaeb-f7bc-4067-a25b-33d56db6da91)
Btw, this has a DataModule that uses some AdoDataSets

**Comment by danieleteti** [comment]
Can yoy reproduce the problem in a self-contained project?
