### ISSUE TITLE
Memory Leaks Reported

### ISSUE THREAD

**Issue by abebuch** [danieleteti/delphimvcframework#79]
Hi,

tried

\DMVC\samples\serversideviews\ServerSideViewsEx.dpr

on Delphi XE7. Just starting the server and stopping give memory lears.

![image](https://cloud.githubusercontent.com/assets/6401040/25909308/cc31ec68-357a-11e7-9e7c-c189b278190f.png)

**Comment by danieleteti** [comment]
Closed
