### ISSUE TITLE
Question - DeSerialization of null returned from controller via IMVCResponse.

### ISSUE THREAD

**Issue by Microcom-Bjarne** [danieleteti/delphimvcframework#792]
Controller :
Returns data via IMVCResponse like this
```
        Result := MVCResponseBuilder
          .StatusCode(HTTP_STATUS.OK)
          .Body(ObjectDict.Add('dataobject', lMyObj))
          .Build;
```
This works perfectly - and Im getting something like this as result.
`{ "dataobject" : { "name" : "Daniele" } }`

When lMyDataObject is nil this is returned. And this is very clear to me, that the contents is "empty".
`{ "dataobject" : null }`

But when deserializing - I get an error. 
`    GetDefaultSerializer.DeserializeObject('{ "dataobject" : null}', lMyObj, stDefault, nil, 'dataobject');`

If I deserialize an empty object - it works. 
`    GetDefaultSerializer.DeserializeObject('{ "dataobject" : {}}', lMyObj, stDefault, nil, 'dataobject');`

I've attached a demo project.
I know I can get around this in numerous ways. Demo shows one way to wrap my object.
But is there any way to fix this - or is it as designed?

[Project1.zip](https://github.com/user-attachments/files/17588771/Project1.zip)

**Comment by danieleteti** [comment]
It makes sense.

**Comment by danieleteti** [comment]
https://github.com/danieleteti/delphimvcframework/issues/792
