### ISSUE TITLE
BUG "Error decoding URL style (%XX) encoded string at position 10" 

### ISSUE THREAD

**Issue by NewBotanik** [danieleteti/delphimvcframework#793]
Hello.
I got an error `{
    "classname": "EConvertError",
    "message": "Error decoding URL style (%XX) encoded string at position 7"
}` 
when performing **POST** for **JSON**, in which there is a sign **%**, followed by a call of  **Context..Request.ParamNames**, for example `{"query_name": "Test%"}`.
This is due to the fact that in the TMVCWebRequest.GetParamNames procedure, rules used for URLs are applied to content.

![изображение](https://github.com/user-attachments/assets/8e1b9d92-9ee5-48e1-bfbf-2184213cd763)

![изображение](https://github.com/user-attachments/assets/4c49d3dc-f430-422e-ba48-48e03ad8b065)

![изображение](https://github.com/user-attachments/assets/7c4c073f-6579-43a2-b29a-b6b0e565689e)

![изображение](https://github.com/user-attachments/assets/796e8cec-c1e4-4d81-9347-4699000342c0)

[ErrorTestProj.zip](https://github.com/user-attachments/files/17660590/ErrorTestProj.zip)

**Comment by danieleteti** [comment]
When you send a JSON object in the body you have to read the body params using `Context.Request.Body*` or (better) using the `[MVCFromBody]` attribute. Content params are intended to be used with form-url-encoded html submit.
