### ISSUE TITLE
Dataset Serializer: Error with float field and very small value

### ISSUE THREAD

**Issue by drcrck** [danieleteti/delphimvcframework#795]
Hi,
After a recent change in the serializer, I encountered an issue with float fields and numbers close to zero.
Previously, these values were automatically rounded to zero, but now they are serialized using exponential notation.

Example:
Here is the JSON value serialized using the TMVCObjectDictionary.add function:

```
[...cut other fields]
{"tot_m3":1E-5.0}
```

This value results in a corrupted JSON output.
Neither mvcDatasetDeserializer nor other online tools are able to parse it correctly.

maybe should be :  {"tot_m3":1E-5}

thanks

**Comment by drcrck** [comment]
I just created a simple demo do demonstrate error.

[Project2.zip](https://github.com/user-attachments/files/17873944/Project2.zip)

**Comment by danieleteti** [comment]
Issue has been fixed in the parent project with https://github.com/ahausladen/JsonDataObjects/issues/78
