### ISSUE TITLE
Method PATCH

### ISSUE THREAD

**Issue by RobyGasp1986** [danieleteti/delphimvcframework#797]
In the MVCFramework. RESTClient.Indy unit the method httpPATCH is not implemented because it was not supported by the TidHTTP in function TRESTClient.SendHTTPCommandWithBody. We tryed to change the code with "FHTTP.Patch(AResource, RawBody, Result.Body);" and this work for us. We are using DMVC with Delphi 10.2, 10.4, 11.3 and 12 and it works. Is it possible to update DMVCFramework?

**Comment by danieleteti** [comment]
Please, update from repo and test it.

However, did you check the new RESTClient? The Indy based is deprecated.
