### ISSUE TITLE
missing unit 

### ISSUE THREAD

**Issue by seguraalfaro** [danieleteti/delphimvcframework#800]
[dcc32 Fatal Error] dmvcframeworkRT.dpk(120): F1026 File not found: '..\..\sources\MVCFramework.ApplicationSession.pas'

**Comment by HealthOneNZ** [comment]
Building OK for D12, which version are you building ?

**Comment by seguraalfaro** [comment]
10.4 and is trying to compile the rc2 version to take a look at

**Comment by seguraalfaro** [comment]
![image](https://github.com/user-attachments/assets/aba3bb4c-d1ab-43dd-bc3f-c75584d5502f)

**Comment by danieleteti** [comment]
Fixed with https://github.com/danieleteti/delphimvcframework/commit/1a092f2fec509881a672f384a46f3327e79286d9
