### ISSUE TITLE
The serializer for text/plain could not be found.  No other informations available

### ISSUE THREAD

**Issue by marcosnielsen** [danieleteti/delphimvcframework#81]
Hello!
i try rum delphimvcframework 3 RC 5 in  \dmvcframeworksamples\sessions\SessionSample.dpr

Hello I'm running example"dmvcframeworksamples\sessions\SessionSample.dpr" of DMVC 3 RC5, and I'm trying a "The serializer for text/plain could not be found." error
Is this a bug or configuration error?

Att
Marcos Nielsen

**Comment by danieleteti** [comment]
Fixed in RC6+
