### ISSUE TITLE
Can not use delphimvcframework from a package

### ISSUE THREAD

**Issue by jadeade** [danieleteti/delphimvcframework#82]
I am getting this error when trying to compile a package that uses the client features of the delphimvcframework (changes.txt dates 28/06/2016, head is at b7604897773121324c11614e4b692f16ed843d33):

[dcc32 Error] E2223 $DENYPACKAGEUNIT 'Web.WebBroker' cannot be put into a package

As far as I know, WebBroker is just server technology, so I understand that there's some kind of dependency that forces WebBroker to be included into my code. Furthermore, we are currently using packages as "code container" and statically linking. The restriction that Embarcadero introduced was because the old wrapped technology cannot live on a DLL, so we would not even be affected by this annoying problem

Is this "fixed" on newer versions or there's a way to avoid adding WebBroker if I don't need server features? or a way to fool RAD Studio and force compilation without modifying RAD Studio sources?

Thanks in advance

**Comment by danieleteti** [comment]
No, also in Delphi 10.2 TOKYO is not possibile to put Web.WebBroker in a package. This is the reason because there isn't a packae for dmvcframework itself...
