### ISSUE TITLE
TMVCConfig.SaveToFile cannot be loaded by TMVCConfig.LoadFromFile

### ISSUE THREAD

**Issue by fastbike** [danieleteti/delphimvcframework#86]
If the config values contain a file path i.e. have the "\" character then the resulting file content is not valid JSOn and cannot be parsed by teh file loading method.

The fix is to add a ToJSON method to the class and output the data as escaped JSON.

I will try to create a simple test case and a fix.

**Comment by danieleteti** [comment]
Any news about it? Please start with the RC7 now.

**Comment by danieleteti** [comment]
FIXED in RC9
