### ISSUE TITLE
Not compatible with XE5 in current state

### ISSUE THREAD

**Issue by Fulgan** [danieleteti/delphimvcframework#87]
Hello,

We integrated DMVC into a new project of ours and we had to make many minor modification to the framework in order to compile (and use) it under Delphi XE5. This should only be a temporary issue for us since we're going to upgrade the whole team to 10.2 shortly.

However, I noticed in the readme that XE5 is supposed to be in the list of supported IDEs and that made me wonder if I should submit a compatibility patch - knowing that I will not be able to maintain a dedicated XE5 branch

**Comment by danieleteti** [comment]
dmvcframework, as you read, is compatible with all version since XE3. However, we need mantainer for each version. Currently I'm mantaining 10, 10.1, 10.2. Your XE5 patches would be great but we need some mantainer for it.
