### ISSUE TITLE
[Question] Can I add actions to a controller programmatically?

### ISSUE THREAD

**Issue by jadeade** [danieleteti/delphimvcframework#99]
I am designing a server and for customisation's sake I would like to add the possibility to add actions to a controller programmatically (for example, loading a bpl at runtime and registering it or loading a config file), but if I follow the documentation, seems that the only way to add actions is statically and using attributes

Is there an existing method to achieve this? 

Thanks in advance

**Comment by danieleteti** [comment]
You can add controllers (with actions) at any moment. However, there isn't a demo about it, we have to write it.

**Comment by jadeade** [comment]
Then if I register different controllers with the same base path, they
would melt together and work like if I had register a whole controller with
both functionalities, am I right?

--
Ignorance is bliss

**Comment by danieleteti** [comment]
Yes. However take care to the actions name. Name collisions mame unaccessible all the actions but the first.

**Comment by cdac901** [comment]
Sorry for reopen this question, I have this problem exists any demo or could write a simple example here.

 Thanks for the help
